### ISSUE TITLE
Reporting pose data depends on the state of the document?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#1041]
In https://immersive-web.github.io/webxr/#protect-poses there's a per-frame check based on the document associated with the session. This seems like it may have unexpected UX consequences, as the user is no longer interacting with that document, since they have a headset on.

**Comment by asajeffrey** [comment]
This came up in #1030, in conversation with @Manishearth

**Comment by asajeffrey** [comment]
As an example, `magazine.com` might have an advert from `car-manufacturer.com` with VR content (which the magazine cam bless as a feature on the `iframe` containing the ad). If the user enters the ad, but while they're in the headset, accidentally clicks or scrolls away from the advert, the pose data will stop being reported.

**Comment by Manishearth** [comment]
cc @avadacatavra

/agenda for discussions of security implications

**Comment by Manishearth** [comment]
I'm also a bit uneasy about this _throwing a SecurityError_, i'd rather it make the pose null. See https://github.com/immersive-web/webxr/issues/1042 for more discussion about that.

**Comment by Manishearth** [comment]
Related: https://github.com/immersive-web/webxr/issues/1042

**Comment by avadacatavra** [comment]
@Manishearth can you elaborate on why you're uneasy about throwing a Security Error?

**Comment by Manishearth** [comment]
@avadacatavra I'm totally for throwing the security error in _some_ of the cases there.

In general for web specs errors should be thrown in cases where the application _did something wrong_ (and thus, should only be thrown in cases which are preventable). In other words, if an error is being thrown, the user should be able to restructure their code to avoid it.

This is possible for the case when realms don't match ("don't call `iframe.contentWindow.currentFrame.getPose()`"), but the other cases are unpredictable. It's possible to have a race condition with the "hidden" state, and it's not possible at all to handle this focus condition well. Throwing a security error when the user switches focus seems wrong because we're telling the author that "they did something wrong", but the user switching focus is not something the author can easily detect so there is no better thing to do here.

This is why I think a null pose instead of an error makes sense. Null pose means "no pose for you", an error means "you did something wrong, please fix it".

**Comment by Manishearth** [comment]
This is fixed in https://github.com/immersive-web/webxr/pull/1058 : the document being hidden causes webxr to report null or emulated (cached) poses.

**Comment by asajeffrey** [comment]
Where "this" is returning null rather than throwing an exception, not the original issue that I don't think we should be doing this check at all!

**Comment by Manishearth** [comment]
alright, udpated the PR to not close this issue

**Comment by Manishearth** [comment]
There seems to be general consensus that we can return `null` here instead of throwing an exception

**Comment by Manishearth** [comment]
There seems to also be general leaning towards a feeling that this check is unnecessary, and that `visibilityState` (which we already handle) should be enough here.

I'm going to keep the changes in https://github.com/immersive-web/webxr/pull/1058 that replace the `SecurityError` with a `null`, but after that lands I can open a PR that removes that language altogether where the final discussion can be had.

**Comment by Manishearth** [comment]
With https://github.com/immersive-web/webxr/pull/1058 the check is no longer an error. I'll open a PR for removing it entirely or making it a bit more UA-dependant.

**Comment by Manishearth** [comment]
Opened #1067 to make this UA-choice. Also open to removing it entirely

**Comment by asajeffrey** [comment]
I'd prefer just removing this check altogether unsurprisingly.
