### ISSUE TITLE
Upstream monkey patches

### ISSUE THREAD

**Issue by annevk** [immersive-web/webxr#1044]
It seems this document modifies the HTML Standard, e.g., the `getContext()` method. This should be defined there.

**Comment by annevk** [comment]
Upon a closer look perhaps it's WebGL 1/2 that are being patched?

**Comment by Manishearth** [comment]
Somewhat both, getContext() gets a new flag but it mostly affects context creation from the webgl spec

**Comment by Manishearth** [comment]
So the issue here is that WebGL _patches itself_ when talking about attributes too. The context creation algorithm does not really look at attributes, instead [the attributes are defined by their impact on context creation](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2).

We could potentially use language similar to theirs -- instead of patching an algorithm, we can say that "this attribute when set makes the context creation do xyz"

**Comment by Manishearth** [comment]
We can also ask them to mention this flag upstream with a "full semantics defined in the webxr spec"

**Comment by annevk** [comment]
Yeah, I think there needs to be a path from HTML to XR, but going through WebGL is reasonable as there's nothing changed in HTML directly. How the dictionary passed as second argument is handled is entirely up to WebGL at the moment as HTML takes `any`.

**Comment by annevk** [comment]
I'm not really sure how that PR addressed my concern?

**Comment by Manishearth** [comment]
@annevk It defined these attributes the same way as the webgl spec itself defines similar attributes. We do hope to eventually move this into that spec, but until then this is the best we can do.

**Comment by annevk** [comment]
You could file an upstream issue and point to that from the specification?

**Comment by Manishearth** [comment]
Yeah, I think @toji is actively discussing this stuff with the WG though, I don't know the full status of that. Maybe he can file the issue?
