### ISSUE TITLE
windows mixed reality problem visor cardboard recognize

### ISSUE THREAD

**Issue by runtimevic** [immersive-web/webxr#1060]
Hello:
Why does it recognize a windows mixed reality device as if it were a cardboard viewer, since the split-screen in two equal parts appears to me in the Internet browser Firefox?
testing the examples of the following link:
https://immersive-web.github.io/webxr-samples/
Thank you Victor.

**Comment by toji** [comment]
Hi @runtimevic,

This repo is for development of the WebXR spec, and isn't a good place to get support for browser implementations. Since it sounds like you're having trouble with Firefox specifically, I suggest looking at https://support.mozilla.org/ to see if you can find a solution or ask a question.

Good luck!

**Comment by runtimevic** [comment]
Hello @toji 
happens to me also with google's browser.
best regards, Víctor.
