### ISSUE TITLE
XRViews should be marked as inactive after the frame that produced them ends

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1092]
With the addition of the [first person observer](https://immersive-web.github.io/webxr-ar-module/#first-person-observer), some views might always be in the current list of views.
Currently, there's is no checking to see if the `XRView` was from a previous frame but no longer in the list of views. Should this be added to the `getViewPort` algorithm?

**Comment by toji** [comment]
The https://immersive-web.github.io/webxr/#dom-xrwebgllayer-getviewport algorithm does currently check to ensure that the `XRFrame` which produced the `XRView` is valid:

```
1. Let frame be view’s frame.
2. ...
3. If frame’s active boolean is false, throw an InvalidStateError and abort these steps.
```

So that's been covered previously. However, I think that this pattern breaks down now that #1088 has landed, in that the same `XRFrame` object is able to be re-used every frame. As a result we'll want to update this to have each XRView track its own "active" state.

**Comment by cabanier** [comment]
@toji Should I close this one and let you open another issue to move the `active` boolean to the view?
This will also cause changes in the WebXR Layers spec.

**Comment by toji** [comment]
No need for a new issue. I just changed the title of this one to better reflect what needs to happen.

**Comment by Manishearth** [comment]
I suspect this can be fixed with the same stuff that fixes https://github.com/immersive-web/webxr/issues/1090 , if done right

**Comment by Manishearth** [comment]
I'll take a crack at both these issues
