### ISSUE TITLE
Is it possible to record a webXR AR canvas

### ISSUE THREAD

**Issue by FuzzyWobble** [immersive-web/webxr#1106]
Hello! Not sure this belongs here but can't seem to find a solution in the threejs community. 

I am trying to record a webXR AR. Using RecordRTC or canvas.toBlob I am only getting all black frames. Maybe I am not pointing at the right canvas target?

Is there a straightforward way for someone less technical like myself to grab the webXR AR canvas data? I looked [at this](https://immersive-web.github.io/webxr-samples/spectator-mode.html) but it was a bit overwhelming/confusing. 

Thanks so much.   ( :

**Comment by Manishearth** [comment]
This isn't, this is for discussing the specification.

WebXR uses a separate framebuffer so `canvas.toBlob` probably won't work. You could maybe copy stuff to the main framebuffer though and toBlob it from there.

**Comment by klausw** [comment]
I think there are legitimate specification issues here in the sense that this is a common use case with no good solution, see for example previous discussions in https://github.com/immersive-web/proposals/issues/36 and https://github.com/immersive-web/webxr/issues/694 which have unfortunately stalled. I think it would be helpful to distinguish local capture (the user wants a screenshot or recording for their own use) from remote sharing (the web site has full access to the captured data) since those have very different security implications.

Currently, In Chrome's WebXR AR mode, the camera image is separately combined with the drawn WebGL content from the framebuffer, and the JS application doesn't have access to camera images. (This is being worked on, the goal is to allow opt-in camera access as a separate feature, with a access permission request distinct from the XR permission.)

If you are comfortable using Android ADB over USB, you can try something like this:
```sh
adb shell screenrecord /sdcard/screenrecord.mp4
# Ctrl-C to end recording
adb pull /sdcard/screenrecord.mp4
```

Be careful, I almost dropped my laptop when filming [dinosaurs in a garage](https://aframe.io/blog/webxr-ar-module/) this way.  Android 11 appears to be getting a built-in [screen record](https://www.androidpolice.com/2020/03/19/screen-recording-is-back-in-android-11-and-this-time-it-actually-works/) function to make this easier.

**Comment by blairmacintyre** [comment]
Don't Android phones just have a "record screen" capability, like iOS?

**Comment by FuzzyWobble** [comment]
Thanks for the response. It feels important to have this in the specification. Capturing AR efficiently is a widespread use case. Native AR apps do it very well. 

I've tried a number of external screen capture apps and they all seem to degrade the performance severely. FPS drops to 10. Also, it captures the UI.

**Comment by klausw** [comment]
@blairmacintyre wrote:
> Don't Android phones just have a "record screen" capability, like iOS?

There's currently only a screenshot function, built-in screen recording is apparently finally coming in Android 11.

@FuzzyWobble wrote:
> I've tried a number of external screen capture apps and they all seem to degrade the performance severely. FPS drops to 10. Also, it captures the UI.

The "adb screenrecord" method keeps the phone in full screen mode, so the capture doesn't have any extra UI. You can add flags, i.e. `size 1440x720 --bit-rate 4M` to tune it, and performance seemed OK in my unscientific testing.

**Comment by FuzzyWobble** [comment]
@klausw thanks. Good to know. Will give a shot. The webXR experience and recorder will need to be released to public so it's only a temp solution.

**Comment by PozitronikTech** [comment]
Is there any way to access the webgl canvas where webxr is broadcasting while holding the session? I mean, has there been an update about these issues? 
I've been looking at this for a long time and I don't see an update yet.

**Comment by toji** [comment]
You can access the rendered contents of the WebGL canvas, but it won't include the AR camera feed. That's happening in a separate compositing step that's opaque to the page.

Since this issue was last updated, though, platform-level screen recording functionality has gotten quite a bit better. Android now has (easier to access) screen recording, and Meta's Quest headsets have begun capturing the full composited WebGL + camera feed view when recording AR sessions. So hopefully that helps satisfy at least some use cases.
