### ISSUE TITLE
Should the `WEBGL_depth_texture` automatically be enabled?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#1175]
WebXR Layers allows you to pass different formats for the color and depth textures.
We wrote validation code that checks that the passed format is allowed but now a default projection layer can no be created on a plain WebGL context because `WEBGL_depth_texture` is not enabled by default.

Should this extension be automatically enabled? How else would you be able to use depth with the default WebGLLayer?

**Comment by toji** [comment]
Apologies, I swear I left a comment on this immediately after you opened it but either my memory is faulty or I neglected to hit the button when I was done.

WebGL framebuffers are allowed to have depth/stencil renderbuffers without any extensions, it just can't be sampled as a texture afterwards. Also because the WebGLLayer framebuffer is opaque we don't give users a way to read back what's attached there anyway. As a result an implementation could easily use the renderbuffer route behind the scenes to implement a valid XRWebGLLayer, or could use depth/stencil textures under the hood without treating the extension itself as if it's enabled. (There's an assumption that the underlying implementation of a WebGL context may not always have the same limits as the user-facing API.)

**Comment by cabanier** [comment]
Thanks! That clarifies the issue.

I actually filed a similar problem against the WebXR Layers spec and you replied to that one.
