### ISSUE TITLE
DOMException XRFrame access outside the callback

### ISSUE THREAD

**Issue by JakeJustLearning** [immersive-web/webxr#1225]
Hello I am trying to follow the example on how to use targetRaySpace in order to get the pose. 

I am using Three.JS with WebXR. 

currently I am creating an onSelect event that looks like the following 
` arApp.session.addEventListener('select', (event) => {
      if (event.inputSource.targetRayMode == 'screen') {
        let frame = event.frame
        let targetRaySpace = event.inputSource.targetRaySpace
        let targetRayPose
        frame.session.requestReferenceSpace('viewer')
          .then(refSpace => {
            console.log({ targetRaySpace, refSpace, frame })
            targetRayPose = frame.getPose(targetRaySpace, refSpace)
            console.log(targetRayPose)

          })
      }`

This however does not work and produces the error '
`index.html:1 Uncaught (in promise) DOMException: XRFrame access outside the callback that produced it is invalid`

I can't tell what if anything I am doing different from the example. my code can be viewed at [this git repo](https://github.com/JakeJustLearning/lizard)

**Comment by AdaRoseCannon** [comment]
I am pretty sure it is because of the asynchronous nature of frame.session.requestReferenceSpace you should use https://threejs.org/docs/#api/en/renderers/webxr/WebXRManager.getReferenceSpace to get the current referenceSpace being used by your scene instead.

This issue board isn't so much for this kind of issue though it's for issues with the API shape itself, try stack overflow instead.
