### ISSUE TITLE
Please add the ability to zoom in or out of VR videos

### ISSUE THREAD

**Issue by Djsuperman** [immersive-web/webxr#1237]
Could you guys please add the the ability to zoom in or out of VR videos?
A lot of the times I would watch a VR video online like on Youtube, etc, and the scale of the videos would be too gigantic, like I am an ant looking at a 20 foot tall person, and I would like the option to be able to zoom in or out of the video to make it smaller and more life-sized, like with DeoVR Video Player on the Oculus Quest 2 VR headset.

**Comment by toji** [comment]
Thanks for the issue, but I think this is the wrong place for it. Zoom functionality like you describe isn't something that the WebXR API (what this repo covers) controls, but instead is something an application built on top of WebXR could implement.

Though since you mentioned YouTube, which doesn't use WebXR at this time, you're probably actually looking for a feature in the YouTube app or a browser that has configurable video projection settings like the Oculus Browser.
