### ISSUE TITLE
How do I interact with 3D objects if mode is "immersive-ar"？ 

### ISSUE THREAD

**Issue by yilinchenXD** [immersive-web/webxr#1240]
i want to interact with 3d objects that  hit-test  produce.   for example，change the color when touching 3d-obj  on screen. how can i  make it.

**Comment by AdaRoseCannon** [comment]
Hit-test is for interacting with the real world objects.

For interacting with 3D objects you will need to use something like a Ray aster your 3D library of choice should have this functionality built in. Here are the docs for three.js https://threejs.org/docs/#api/en/core/Raycaster

Closing this issue because it is not a specification bug
