### ISSUE TITLE
Does WebXR support full body tracking?

### ISSUE THREAD

**Issue by yuripourre** [immersive-web/webxr#1247]
Hello, I've read the current specification but didn't  find anything related to body tracking. Is body tracking planned for future releases?

Can I assume that it would be implemented similarly to the hand tracking (a list of bones that can be assigned to the mesh)? Or it would take a different approach?

Thank you for your time.

**Comment by toji** [comment]
There's no explicit support for body tracking in the spec. It might be something the group will consider later, but at the moment there hasn't been a lot of interest shown in it because the body tracking setups that are available are non-standard and essentially creative hacks. We'd want something that looks as if it's going to become a more common standard among vendors before we'd consider adding it to the WebXR spec. 

I do suspect that if that should happen it probably would resemble how hand tracking is exposed.

On some WebXR implementation you may be able to pull off the same sort of creative hacks as native desktop apps by simply tracking additional inputs beyond the left hand/right hand, but on anything that is implemented on top of OpenXR (which all Chromium-based desktop browser are) you won't ever see more than the two hand's inputs due to restrictions with how OpenXR's input mapping system works.

**Comment by yuripourre** [comment]
@toji thank you for the reply. I am looking forward for the future, then.

**Comment by yuripourre** [comment]
Related to: https://github.com/immersive-web/webxr-samples/pull/178
