### ISSUE TITLE
I can´t enter vr on the taste page

### ISSUE THREAD

**Issue by Deadterm1nator** [immersive-web/webxr#1274]
I just downloaded chrome, so it is the latest version. In the flags page of chrome, it only appears me: _WebXR Incubations_ and _Force WebXr Runtime_ , i enable it and disabled it but nothing happens. Im using an oculus rift s, i put oculus as the openxr run time. I made all the possible things to fix this but sincerely i dont know what to do now. 

Thanks.

**Comment by Deadterm1nator** [comment]
Also i have enabled the _Oculus Public Test Channel_

**Comment by Nawarius** [comment]
+1. Same problem. Also Oculus Rift. The last time I tested webxr was until February 2022, everything was ok. Now writes errors:

`Could not create a session because: Something went wrong initializing the session in the runtime`
`XRSession creation failed: The specified session configuration is not supported.`

**Comment by cabanier** [comment]
This is an implementation and not a spec issue. Please contact the vendor for support
