### ISSUE TITLE
frame.getDepthInformation(view) returns null Samsung Galaxy S20+(with ToF camera)

### ISSUE THREAD

**Issue by guo1017138** [immersive-web/webxr#1315]
Hi Experts,

I've enabled depth sensoring in immersive-ar as following. It works on one of android phone without ToF camera. But on Samsung Galaxy S20+, frame.getDepthInformation(view) returns null always. Anyone knows what I'm missing here with ToF camera? Any flags need to be set?

```
                sessionParams.requiredFeatures.push('depth-sensing');
                sessionParams['depthSensing'] = {
                    usagePreference: ["gpu-optimized", "cpu-optimized"],
                    dataFormatPreference: ["float32", "luminance-alpha"],
                };
```

**Comment by bialpio** [comment]
If you're using Chrome for Android, this is probably https://crbug.com/1193828. No flags should be needed - the device sends us a quite high-res buffer which we artificially suppress due to privacy concerns.

The best way to make progress is to probably file feedback through your browser, this repo is not really supposed to be used for issues with specific implementations.

**Comment by guo1017138** [comment]
@Manishearth Thanks for guiding. I will check the details in your link.
