### ISSUE TITLE
WebXR camera-access textures bug.

### ISSUE THREAD

**Issue by ogodeverest** [immersive-web/webxr#1319]
It seems that adding camera-access to the required features brakes three.js mesh textures. 

const session = await navigator.xr.requestSession(“immersive-ar”, {
  requiredFeatures: [“camera-access”]
});

![image](https://user-images.githubusercontent.com/22114017/231782993-1deb66ce-ac86-4116-b9b5-a515797f8b21.png)
The meshes texture gets replaced by the camera feed instead.  In the example, I am loading a texture and mapping it to a plane geometry but it is instead overwritten by the camera feed. This also happens for gltf models.

**Comment by cabanier** [comment]
This looks like a bug in Chrome (and not in the WebXR specification).  You can file your problem [here](crbug.com).

**Comment by orb-ar** [comment]
I am having the same problem as well. 
There has been a reported (and fixed) bug in chrome related to camera-access feature (see [here](https://issues.chromium.org/issues/350939008)). Although i do not think it is related.

Description: I got an AR experience built using WebXR and ThreeJS. The experience works great and requires only "dom-overlay" feature from webxr.
The issue happens as soon as I add the "camera-access" feature to the list of required features when requesting a webxr session (no other changes done in the code, and the code does not try to access the camera frame at all). When doing this, every texture used in the scene gets replaced with the camera feed.

I did notice that the issue happens when there is only a single visible textured object. If there are 2 or more different **visible** objects in front of the user then the above issue does not happen.
[Example video](https://drive.google.com/file/d/1bW16BNH7ZVVa8x7PrbgiRM_bmbSCIXyz/view?usp=share_link)
Both the objects in the experience are loaded from a .glb file via Three's GLB loader.
Note: I tried adding a glb file that contains more than one textured child -> it works normally. So I am pretty sure it is related to number of rendered textures.

The only explanation I could think of is that there is a collision between webxr's camera-access feature and threejs's renderer when trying to optimize the rendering for a single object in the scene...

The problem occurred on more than one Android device:
- Xiaomi Redme Note 11S.
- Samsung S23.

Any ideas / suggestions?
