### ISSUE TITLE
Should we have the ability to distinguish between opaque and see-through devices?

### ISSUE THREAD

**Issue by ssylvan** [immersive-web/webxr#145]
Right now WebVR apps have to assume that the HMD is opaque, but in some cases the app might want to do something different if they know the devices is transparent (e.g. they may skip rendering "background" visuals).

Should we have some way of checking that? It would be tempting to put in the device capabilities, but it seems like some HMDs will use pass-through video feeds to simulate the HMD being see-through, which means that the value can change from frame to frame, and might not even be a binary choice.

Perhaps the VRFrameData could have an HMDOpacity value that goes from 0 to 1? On typical VR devices it would be 1, on something like a Hololens it would be 0, and if any future devices has the ability to change it continuously it would be somewhere in-between.

Thoughts?

**Comment by toji** [comment]
What would a HMDOpacity of 0.5 represent? Having a hard time picturing such a device. Definitely think that this is a valuable thing to communicate, though.

A few thoughts:
- If a device supports pass-through video, that seems like something that the app will want to/need to explicitly account for, even if it's just a flag that says "yes I want passthrough/no I don't". Event if it's just for performance purposes. (Using the passthrough camera feed will always have an associated perf cost.)
- That same flag is nonsensical for see-through devices like HoloLens. You can't "turn off" the real world, but you can paint over the whole thing.
- Seems like Windows Holographic already needs to deal with both classes of devices. Any documentation that we can be pointed at for how it's handled there?
- It does seem like whether we communicate opacity as a binary state or a float we'll want an event that communicates if it changes. I'd like to think that should be in the apps control completely, but I'm guessing that won't prove true long term.

@judax has been looking at dealing with passthrough cameras on Tango, he'd probably have some valuable insight on this subject.

**Comment by ssylvan** [comment]
I'm not fully convinced having opacity be continuous is desirable - so would love to hear from others. 

Imagine something like an Oculus and a Vive but with two cameras on the outside and a "pass through" mode that just shows you the real world instead of VR. Since the "real world" is a matter of blending textures, they could choose to make the real world 10% opaque or any arbitrary fraction (e.g. for safety reasons? or in response to user controls?).

**Comment by brianchirls** [comment]
For that matter, I wonder if there's relevant information about how the
graphical content is overlayed on the real world. Is the FOV different? Is
the overlay fully opaque? Does black work? Is there blending? What kind?

Maybe it's too early to fix this in place.

**Comment by blairmacintyre** [comment]
If we're going down this route, it would be great to think about what we need to support transparency and pass-through video robustly in terms of calibration:  is the current set of viewing parameters sufficient to account for an optically see-through device in terms of the viewing specs and the relationships between the tracker, the user's eyes and the HMD displays? 

Similarly, to be able to use video, you need to know the intrinsic (camera calibration) and extrinsic (pose of the camera, in this case relative to the tracking system) parameters of the camera.   Android (optionally)  supports intrinsic calibration info for the camera on a device;  I don't think any other platform does. It would be great if it was possible for a device (that has a built in camera, like the Vive) to provide this info. 

I too would be interested in hearing @judax's views on this.

**Comment by judax** [comment]
While working with Tango from Google (a camera based VR/AR device) I have been playing around with the concept of VRSeeThroughCamera inside the VRDisplay. This new data structure provides the camera metrics so the correct visualization of the video feed can be achieved by the app. Of course, the VRDisplayCapabilities also reflect the existence or not of the see through camera.

There are still many uncertainties as this thread clearly shows. This is just one a approach that solves a specific problem. See through cameras like Tango's require a thorough time stamp synchronization for correct pose estimation. The current approach has been to "occlude" this information to the app and estimate that if a frame from the camera has been requested, the timestamp will be used internally to return the correct pose.

I really believe this approach may fit well with HTCVive and Tango like camera based devices. I will be starting a conversation with the Hololens team soon to better understand their approach on this.

**Comment by blairmacintyre** [comment]
One question I have is which things should be part of WebVR, and which should leverage other WebAPIs.  Could WebRTC and proposed standards like the media-capture-depth do what you need?  The implementation might be tightly coupled on devices that need to support both (e.g., Tango) but then those devices and capabilities won't be so intimately coupled with WebVR (and, thus, only usable in immersive VR mode).  We could say the same thing for the head tracker and other sensors;  why aren't the sensor api's being used?

**Comment by cvan** [comment]
Filed #97 for spec'ing behaviour for passthrough cameras (e.g.,  HTC Vive's) - likely using WebRTC.

**Comment by judax** [comment]
I do like the "webby" approach of leveraging APIs like deviceorientation and maybe "deviceposition" for tracking of not just an HMD but even any object that could be tagged etc, The same could be applicable for other things like the camera or how it has happened with the 6DOF controllers, the gamepad API. But I guess that: 

a) These are defined specs that would take involving people that are not just interested in VR.
b) The WebVR has started already and advanced and adopted enough that a complete redo might be impossible

I am not sold on how to render/activate a see through camera, but at least being able to specify that the device (VRDisplay) has this capability makes sense in the current WebVR spec. I am still doing some research on how other options could be a good fit to render/use the camera. For now, the render is completely out of the VRDisplay and it is done using WebGL.

**Comment by blairmacintyre** [comment]
(a) could be problematic, but doesn't have to be.  For example, WebRTC seems to have a goal that aligns with end-to-end latency reduction, so reducing latency on the front end (getting video into the browser) isn't completely orthogonal to their mission.  However, I agree that if there are tradeoffs (in design, and priorities) they may not align with our needs.
(b) I agree with that for the most part.  It's clear that the folks who have been working on WebVR have done a great job:  getting VR working in browsers, with the speed issues that had to be addressed, is pretty amazing.  So, clearly, nobody will want to break things without good reason.  But as we consider various things (like video, here, or like multiple sensors or frames of reference that the MS folks suggested), I'd suggest there shouldn't be sacred cows.  At some point, there might need to be big changes;  those might need to be held off for major version jumps (WebVR 2! 3!).  

I also think we have to be careful about which kinds of integration are good. "deviceposition" and deviceorientation are ambiguous.  On mobile, the screen and "machine" are one and the same.  On a laptop or desktop?  Not as much.  The device orientation APIs already struggle with this.  Now, we're talking about separate displays, potentially.  It may be that the values spit out by deviceorientation/position are the same as we get for the user pose in WebVR, but they might also be different.

Especially if we start expanding the use case.  Right now, WebVR is about opaque VR displays, attached to the head.  What about supporting things like CAVEs or AR setups like RoomAlive (projection AR)?  Decoupling displays from "user pose", stepping back from "stereo vs mono" to "multiple displays", are small things that could enable a significantly bigger and more varied application space.

Anyway, these are all just things to think about.  As you say, your integration isn't too tightly coupled.  It's pretty easy for me to imagine (for example) that the video stream returned from WebVR may look and act like something returned from WebRTC, even though it was "created" through a different approach.  Creating the video stream directly has some nice advantages: WebVR (hopefully) would know what video stream(s) are for what (e.g., imagine stereo cameras on a future Tango phone), and the act of initializing WebVR on a display with cameras could be taken as permission to access the camera (perhaps not, but it could), obviating the need to ask the user if the app can use the camera(s) and requiring the app or the user to figure out which camera to use.

**Comment by ssylvan** [comment]
IMO it would be nice if we could specify the concept in a way that doesn't tie it to a specific implementation. As has already been mentioned in this thread, it's kinda tricky to synchronize and correctly map the image(s) so that it doesn't look (too) weird - it seems desirable that this complexity is handled by the user-agent and lower layers (e.g. SDKs) rather than each web developer.

Moreover, I we already have at least 3 obvious versions of "see through" HMDs:

1. A single outward facing camera.
2. Two outward facing cameras.
3. An actual transparent display. 

Getting too low level might make the API unsuitable for some of these (or other versions coming in the future).

Not saying I now exactly what the best abstraction is, but personally I'd prefer something higher level that deals with "display is/can be see-through" (as well as "please modify the opacity" if it's something that can change) that each browser/HMD vender can den do a great job at, rather than just "here's what the camera can see - figure it out!". Not to say that you couldn't *also* provide camera data, of course (even for uses unrelated to making an HMD appear see through).

**Comment by blairmacintyre** [comment]
Good points @ssylvan 

I (and I suspect @judax) have an (implicit) assumption that we'll want the video potentially available to the web developer in case that want to do computer vision on it, and to do that you also need the camera intrinsics.  But, my working hypothsis (when I've been talking to the WebRTC folks, for example) is that we'll need to ask for the video in multiple ways (texture?  javascript buffer?  just display it for me?) depending on your needs.

I'm also very concerned with eventual privacy issues, and being able to "just display it" is something I think we'll want, since a user may be comfortable have the browser grab and display video, but less comfortable handing it to an arbitrary web app.

**Comment by judax** [comment]
Computer vision in JS? :) No, my assumption was, how can the video be rendered in a very easy an intuitive way? In order to do that, similarly as some other APIs have done, I came up with the idea of overloading the WebGL texImage2D function with the VRSeeThroughCamera parameter. This way, the developer can decide when and where to display the video and the "magic" is done underneath the surface. I am not saying this is the right approach, but I deeply believe is simple and yet powerful. Use cases:

* Rendering the camera as a quad to be the background of a fullscreen Tango experience.
* Rendering the camera from the Vive on top of one of the controllers (as Vive does if requested).
* Applying some fragment shader effects to the camera: Vive's background shader, chroma key, ...
* Some shader-level processing could be done :). Better than JS.

Then again, this ties the VRSeeThroughCamera to WebGL so I am not completely sold. I also believe it will be complicated to add this to the Khronos WebGL spec (I might be wrong).

**Comment by blairmacintyre** [comment]
Eventually, yes, computer vision in JS!  In the long run, I believe we need 2 things:
- the ability to display the video (and render the depth data and/or generated room mesh) with low latency
- the ability to do computer vision on the video (and perhaps the depth and/or generated mesh)

Right now, we are limited in our choices, but should be thinking about the long term.   As a starting point, your approach is a good experiment, since it can be done now, and integrates with minimal changes.

But, I don't think it's the right long term solution.  I think we should be aiming to do three things.

1. get the video frames efficiently in a texture, as you are doing.  This will be necessary for certain kinds of visual effects
2. get the video frames efficiently in a Javascript buffer.  This will be necessary for computer vision.  One approach might be to make WebRTC work with low latency for this case.  Another might be to introduce a concept like "videoWorkers" that are a kind of webWorker that is tied to the delivery of video frames (and may be set up to run some webAssembly on the frames).  We could further introduce some ideas like asynchronous and synchronous workers, depending on the needs of the vision algorithms
3. leverage WebVR layers, and render the video/depth information into a background layer that is composited with the web-app's layer by the engine.  

I've been thinking about this approach and bouncing the idea off some folks, and it seems to have a lot of potential benefits.  First, if opens the door to greater efficiency, because it can be implemented in the browser.  Second, it decouples the rendering of the background video from the web app, which simplifies the web app and reduces the coupling of the app to the platform (e.g., hololens could just render black+depth; tango video+depth;  vive renders video; normal phone renders video).  _This seems like it fits in with the original question:  a way to distinguish between different kinds of displays, without requiring significant extra work on the part of the web app author._

Third, we've seen some interesting potential in Argon to have "custom views of reality" implemented separately from the web apps, and rendered in a background view;  we could do something similar here, allowing the end user to control how they view and interact with AR apps. Fourth, it gives us some opportunities to observe user privacy because unless the app needs the video (in a texture or javascript buffer, for advanced rendering or vision), we never have to hand the video or the depth/background mesh to the web apps.  While most AR systems right now are not doing anything to take care of user privacy, this will be a big deal when AR on the web is more pervasive ...

So, I'd really like to have you (and others) consider this idea of rendering the background into a layer, separate from the app.  This will require some changes to the spec, perhaps, but I think it will be the right way to go in the longer term.

**Comment by cvan** [comment]
If I'm understanding your use cases correctly, there is a **[Shape Detection API](https://wicg.github.io/shape-detection-api/)**, which lets you do these things with JavaScript _today_ in [Chrome Canary](https://www.google.com/chrome/browser/canary.html).

There are two relevant APIs that are quite interesting: the **[Face Detection API](https://paul.kinlan.me/face-detection/)** and **[Barcode Detection API](https://paul.kinlan.me/barcode-detection/)**.

Just make sure you enable this flag in Chrome Canary: `chrome://flags/#enable-experimental-web-platform-features`.

Also, I would recommend checking out the following APIs:

* [Media Capture and Streams](https://www.w3.org/TR/mediacapture-streams/)
* [Media Capture and Streams with Workers](https://w3c.github.io/mediacapture-worker/)
* [`MediaRecorder`](https://www.w3.org/TR/mediastream-recording/)
    * [great collection of code samples](https://mozdevs.github.io/MediaRecorder-examples/)
    * [cool demo](https://www.darktrojan.net/test/green/green.html)
    * [helpful article on Hacks](https://hacks.mozilla.org/2016/04/record-almost-everything-in-the-browser-with-mediarecorder/)

**Comment by toji** [comment]
Update: We had a vote on features that should be in scope for WebVR 2.0 today and indicating transparent displays was voted in. We should put together a proposal pull request soon for how to handle this.

**Comment by toji** [comment]
Raising this issue back from the dead after our vote previously, I'd like some clarity on how developers are intended to use this information.

I see that the equivalent functionality in Windows Mixed Reality is [`HolographicDisplay.IsOpaque`](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicdisplay#Windows_Graphics_Holographic_HolographicDisplay_IsOpaque_) which at least enforces the idea that this probably should be a simple boolean. But I can't find much about recommended uses or example code that takes it into account. Beyond that, though, in the absence of environmental data of some kind (at least a floor plane, but ideally an environment mesh or something similar) it seems like there's not really any reasonable action a developer can take if they know the display is transparent? If your experience renders over the full-frame then it doesn't matter much anyway. And my understanding is that devices like HoloLens can't really render black, so if you have an experience that's mainly "objects in space" clearing the screen to black works well in either scenario?

I'd love some further explanation of expected use cases for this boolean, and if there's not much that can be usefully done in absence of environmental data I'd suggest deferring it till those are present.

**Comment by blairmacintyre** [comment]
Interesting.  I've been dealing with this in our argon.js library, which was initially designed for AR but now supports WebVR for rendering as well.  I need to distinguish between "AR" and "VR" situations, and I think a simply boolean like that might do it.

For me, any design of "WebAR" will need to support the idea of rendering your graphics and having the browser "render reality" ... that might be "nothing" (see-through display), "nothing + depth" (hololens, etc), "video or something based on a collection of video inputs", or some other representation of reality (streetview, streaming remote video, a model of some space in the physical world, etc).

With this design, a page mostly needs to know if it should render a background:  is it "VR" or some form of "AR".  "AR" where the API has handed your page the video and wants you to render it is, more or less the same as VR (you're rendering everything).  But, knowing that there is "something" behind your page, and that you should render a transparent background, is probably good enough. 

Other flags can deal with telling you if there is camera video available (as @judax did in his Tango demo) or perhaps provide more details about the underlying background (as we do in argon.js).

**Comment by toji** [comment]
Thanks for the feedback, Blair!

I should mention that I consider AR via passthrough video to be a distinct scenario from a transparent display. In the passthrough video case you'll need to take explicit steps to determine that a video feed is available and composite it into your scene. (Exact mechanisms still in flux, likely provided as a WebGL texture or a future VRLayer type. @judax continues to do good work in this area.) Since the developer need to take action to enable passthrough it falls into a different segment of the API than true transparency, even if the end effect may be superficially similar.

Setting aside that question for a moment, though: Even with a passthrough video, if we assume you can't perform any inspection/modification of the video feed itself and no other information about the environment is supplied, what effects does that enable?

**Comment by blairmacintyre** [comment]
What do you mean "what effects does that enable"?    Also, I think "can't perform any inspection/modification of the video feed itself and no other information about the environment is supplied" is a very specific subset of the use cases -- I would expect that the API would provide pose (like WebVR) for rendering, and could provide a variety of APIs that fall short of "everything, the video and depth".  For example, the API could provide ways to retrieve tracked planes (like ARKit does) or the depth at a certain point (under the finger / center of screen), and could still provide occlusion via depth buffer and compositing.

Right now, AR examples on Tango and Hololens (for example) provide very little detailed information about the world, aside from things like the mesh/depth buffer, and (through them) and ability to find things like planes.  These are generally used (in most apps) to occlude and content on surfaces.  Without application access to world structure, things are weaker (e.g., the content can't sit on much besides the floor, and no "path finding" through the world is possible), but still possible.

For example, if we want to do a bunch of the Hololens demos (put some piece of content in the room with us to discuss), we just need tracking in a common coordinate system.  And to "point and place something somewhere", we could provide that as a capability of the underlying system (give me the depth and surface normal at the selected point) without providing video and depth mesh to the app.

I think it should be _possible_ for the apps to get all this information, of course, but it should also be _possible_ for users to run (possibly degraded) apps without giving up their privacy.  This is especially important in the context of the web (oh, look, I just gave some random scammer website a texture mapped 3D model of my house or desktop/conference room at work!)

**Comment by toji** [comment]
Right, sorry this is a bit confusing. I'll try to clarify a bit more.

The feature in question for this issue is a simple `isTransparent` or `isOpaque` boolean, which is what the implementors group has indicated they'd like to have as part of the initial API draft. Certainly there are a great many other AR features that we want to add down the line, but they're being tracked separately. So the question is: What can the developer do if the *only* AR-centric API you are given is `isTransparent`? If the answer is "Not much" then it may be better to wait until it can be released alongside other AR features like environment meshes/depth buffers.

> I think "can't perform any inspection/modification of the video feed itself and no other information about the environment is supplied" is a very specific subset of the use cases -- I would expect that the API would provide pose (like WebVR) for rendering

Correct, we'll still be providing the best pose data we can regardless of the display transparency. The reason I brought that up at all is that a video feed that is silently composited into the frame for you is roughly equivalent to a transparent display anyway. In either case you'd be doing rendering with no indication as to what's behind your scene (or should be occluding it).

> Right now, AR examples on Tango and Hololens (for example) provide...

Everything you describe in your last three paragraphs is additional AR APIs. We all want them, but for the sake of getting things done in a faster, incremental way we're deferring them for the moment. The singular thing that's been requested to be in the WebVR core is a boolean to indicate if the display is transparent or not, which is trivial to add but of questionable utility.

So to rephrase my question slightly: If you are using the WebVR API with two different HMDs and I tell you "This one is opaque, this one is transparent. Both will give you a valid pose, but neither can tell you anything about the environment. No scene mesh, no depth map, no surface normals, no plane identification." Will you still render your content differently because I told you the display is transparent?

**Comment by blairmacintyre** [comment]
Ok, fair enough. Sorry for "dumping too much"! :)

Answer:  yes.  If anything, "I won't render a background, just the content" is the high-bit. 

I just created a bunch of examples for an AR/VR art class I did with high school kids (with glitch.com, argon.js and aframe).  If AR mode (your transparent) I assumed AR, assumed I was on campus and rendered just the content in the "appropriate place."   If opaque, I assumed VR and rendered a virtual version of the campus and allowed them to teleport around.

when/if we add video like @judax did, that tells us if we need need to render it, or just use it in other ways.  But even without that, it lets us make simple choises based on simple assumptions.

**Comment by toji** [comment]
Thanks for your perspective! It helps. The core concept of "I'll provide a virtual background it it's opaque, and none if it's transparent" seems reasonable. One follow up question:

> If AR mode (your transparent) I assumed AR, assumed I was on campus and rendered just the content in the "appropriate place."

Out of curiosity what did the "appropriate place" mean to you in this scenario?

**Comment by blairmacintyre** [comment]
In my case, since Argon4 (the AR web browser we are using) supports geolocation-based AR, it meant just assume I was outside and display the content (which was geolocated) in the right place.  

For Hololens (or Tango), if I was building an experience that I had authored to a certain space, that would imply having the map already built.  So, I'd load that map and display the content, I think.

This scenario makes more sense in the context of doing AR/VR _with respect to a pre-defined place_ as opposed to what most demos do (put content in the place you happen to be in, using the world as a "backdrop" but not really doing anything related to the world).  Right now, that may be a "minor" use, but I actually think that over time, experiences in places will be more common.

**Comment by NellWaliczek** [comment]
Looks like this issue was addressed by #366
