### ISSUE TITLE
2D Canvas Support in WebVR

### ISSUE THREAD

**Issue by RafaelCintron** [immersive-web/webxr#153]
Current versions of the WebVR spec state that valid values of `VRSource` are `HTMLCanvasElement` and `OffscreenCanvas`.  

Chrome and Firefox currently do not support 2D canvas as a `VRSource`, only WebGL canvases.  Chrome throws an exception when you call submitFrame with a 2D canvas.  Firefox crashes.  

I see that there are tutorials and tests on the Internet that use 2D canvas in WebVR:
* https://developer.mozilla.org/en-US/docs/Web/API/WebVR_API/Using_the_WebVR_API
* https://github.com/mdn/webvr-tests

**Is using WebVR with 2D canvas something we want to support for v1.1?**  

Note that since the developer must call `getContext` on canvas before it can become a 2D canvas or a WebGL canvas, `requestPresent` is too early to reject canvas elements of the wrong kind.  `submitFrame` is our best bet.

**Comment by brianchirls** [comment]
In my experience, calling `getContext` to set up webgl can be quite a long
blocking call. So even if it's allowed, it's maybe not best practice to
`requestPresent` before that's happened. Also you need to set up shaders,
buffers and textures etc. after creating the context and before you start
drawing anything significant.

Although maybe there's a case for it? Perhaps the time after you put the
headset on and before your eyes adjust is the best time for a delay. What
do you all think?

**Comment by kearwood** [comment]
Perhaps if there were some new CSS attributes to enable HTML elements to be projected onto planes (or model surface textures) in 3D space, this could be used to present simple interfaces or "loading" screens that can be visible until the first requestPresent call.  Perhaps this could also be used for use cases that may have been desireable with the 2d canvas?  Combined with media queries, this could also enable "scalable" 2d sites for better use of real estate when used in VR.

If wishing for these elements to remain visible and be composited together with WebGL content, a flag or additional VRLayer could be passed into rewuestPresent.

Would such functionality cover the use cases that required 2d canvas support otherwise?

**Comment by mkeblx** [comment]
Yes there are some clear use cases @kearwood indicates from loading screens, etc. Maybe much less so the linked to MDN examples where 2D canvas would do entire world rendering. 

**For 1.1/1.2** perhaps not, until we hammer out more complex `VRLayer` scenarios with multiple `VRLayers` composited which can come later. Ideally in the future layer `VRSource`'s would include even broader support of Video, Image, HTMLCanvasElement (2D); well any `HTMLElement`.

Is there any issue to making explicit to a WebGL context for now and then expanding in future?

**Comment by RafaelCintron** [comment]
@mkeblx I have no issues with making WebGL be the only supported context for v1.1.  Edge will only support WebGL for v1.1.

**Comment by kearwood** [comment]
Firefox v1.1 support will be WebGL-only layers.  WebVR 2.0 now describes layer types; the first one being VRCanvasLayer.  Do we want 2d canvas support within VRCanvasLayer, or perhaps would we really want a VRDivLayer or similar thing, which creates a floating 2d-plane with any HTML content?

**Comment by toji** [comment]
I don't think it would be a big development burden (in Chrome, at least) to allow the canvas layer to accept canvases with 2D contexts. I just question the practicality of it. It strikes me as something where you're far more likely to want to draw to the canvas and project it as a quad in space than an API you'd actually be rendering a stereo view with.

I also feel that a `VRDivLayer`/`VRDomLayer` of sorts could be *extremely* valuable, but I'm guessing that there be dragons. Probably not something we should got too distracted by while 2.0 solidifies, and something that we should approach thoughtfully in the future.

**Comment by kearwood** [comment]
I agree with @toji above.

For 2.0 we should just ensure we are not precluding the possibility of a `VRDomLayer`.  We should ensure that a 2.x update could add support for this without breaking changes to the spec.

In the Firefox implementation, the VR rendering path hooks deeper into WebGL for performance reasons.  Rather than supporting 2D canvases for stereo content, IMHO, that effort would be better spent to support more generally useful `VRDomLayer`-like functionality.

**Comment by toji** [comment]
Closing this as "Yes, but why?" ;D Never gonna happen for WebVR and in WebXR if we find a compelling use case it can become a layer type.
