### ISSUE TITLE
Toward standardization of WebVR?

### ISSUE THREAD

**Issue by dontcallmedom** [immersive-web/webxr#210]
[As posted on the mailing list](https://lists.w3.org/Archives/Public/public-webvr/2017Mar/0000.html):
One of the conclusions of the [Web & VR workshop we held in October 2016](https://www.w3.org/2016/06/vr-workshop/report.html)
was that WebVR was a key component needed to make the Web a viable
platform for VR, and that work on standardizing it should be part of
W3C's roadmap.
  

For those not necessarily familiar with the W3C process, the benefits of
the formal W3C standardization process (compared to the spec development
in a Community Group) includes:
* Royalty-free licensing commitment with the protections from the W3C
Patent Policy

* Strengthening of the specifications via so-called "horizontal reviews"
from other W3C groups in the fields of accessibility,
internationalization, security, privacy

* More cross-pollination with other spec-developing Working Groups, esp.
through the participation to the annual W3C Technical Plenary week

* Assistance from the W3C staff with designated staff contact(s) who can
help with process, public communication (press release, conferences,
etc) and coordination with other groups and external liaisons

I've been watching the great progress the community group is achieving
on the WebVR API, and have started inquiries about the timing to start
the formal standardization work on that API.

Some of the early feedback I got was that the work should continue its
incubation for a bit more time, and that during that time, it would be
helpful for W3C to identify and ideally smooth any obstacle that the
consensus-based standardization process might bring.

I am now thus seeking input from the Community Group at large on two
main questions:
* what would be the criteria that you would see as relevant to determine
that WebVR is mature enough to start its path on the standardization
process? From my reading of our own internal [best practices on the topic](https://www.w3.org/Guide/standards-track/), WebVR ticks pretty much all of the boxes, but there may be
constraints specific to this spec or community that would be worth
knowing about.

* what risks or obstacles can you think of that the standardization
process might bring? I can imagine for instance that getting an early
understanding of the impact of some of the horizontal reviews (e.g.
accessibility) would help, but again, would prefer to get as clear a
picture as possible to pave the way forward.  Since horizontal reviews
address issues that help implementation and  deployment, not just
standardization, how can we help those reviews to fit, for example with
early use of self-review checklists.

I'm also happy to give more context and clarifications as needed.

**Comment by anssiko** [comment]
>* what would be the criteria that you would see as relevant to determine
that WebVR is mature enough to start its path on the standardization
process? From my reading of our own internal best practices on the topic, WebVR ticks pretty much all of the boxes, but there may be
constraints specific to this spec or community that would be worth
knowing about.

This group clearly satisfies all the W3C's [requirements][2] for advancing to formal standardization. In addition, with the work now starting on the [WebVR API "v2.0"][1], the timing for such advancement would be particularly great.

Given the work mode of the Community Group would remain largely the same after transition, but with the above-mentioned benefits in the mix, I see no concerns in making the transition.

>* what risks or obstacles can you think of that the standardization
process might bring? I can imagine for instance that getting an early
understanding of the impact of some of the horizontal reviews (e.g.
accessibility) would help, but again, would prefer to get as clear a
picture as possible to pave the way forward.  Since horizontal reviews
address issues that help implementation and  deployment, not just
standardization, how can we help those reviews to fit, for example with
early use of self-review checklists.

Since the formal W3C standardization process *is not* about rubber-stamping an input spec (that is discouraged^), if standardization is not started early enough, I see a risk of not being able to improve the work this Community Group has started based on wider review. That'd be harmful in the long run.

>^[Standards-track criteria][2]: "Is it clear the proposers are not seeking a rubber stamp from W3C?"
>"Proposers of Recommendation-track work should be prepared for the Working Group to make substantive changes to the initial draft in response to feedback."

[1]: https://w3c.github.io/webvr/index_wip.html
[2]: https://www.w3.org/Guide/standards-track/#criteria

**Comment by toji** [comment]
I'm probably not the best individual to communicate Google's views on the timing of standardization, but I did want to make sure that one thing was clear: WebVR "2.0" is intended to be the first complete version of the spec. The (admittedly terrible) 2.0 branding is for disambiguation of internal discussions and to signify that it's a large breaking change from what has been published before.

That version of the spec is coming together quickly, though there's still a couple of large outstanding question marks. We intend to put it up for TAG review once those are resolved, explicitly to get the sort of wider review that @anssiko mentioned.
