### ISSUE TITLE
Origin Security in WebVR navigation

### ISSUE THREAD

**Issue by jeffcarp** [immersive-web/webxr#245]
Hi, I saw in [Brandon Jones's WebVR Origin Trials update on blink-dev@](https://groups.google.com/a/chromium.org/d/msg/blink-dev/XiGelyI27sE/F-X2K7KwAwAJ) that a recent development is navigation between WebVR origins without exiting WebVR. I'm super excited about this! I also have a question about security. [In the spec](https://w3c.github.io/webvr/spec/1.1/#security) it states:

> When navigating between pages in VR the browser should display trusted UI elements informing the user of the security information of the site they are navigating to which is normally presented by the 2D UI, such as the URL and encryption status.

Assuming WebVR controls 100% of the pixels the user sees, the following situation is possible:
- User visits evil.com in VR and clicks on a button titled 'Login with Google' that is not a link
- evil.com does not navigate the user, but displays a UI identical to the browser's notification for switching origins notifying the user they're navigating to accounts.google.com and shows a page that is identical to accounts.google.com
- Phishing ensues

Has there been any discussion around how to prevent this type of attack? I can't wait to surf all around the internet in 3D.

**Comment by brianchirls** [comment]
Your link is to the 1.1 spec. But the [same thing](https://w3c.github.io/webvr/spec/latest/#trustedenvironment-security) is in the 2.0 spec in progress.

I think it should not be necessary to show the trusted UI elements if the link is to another URL on the same origin (with HTTPS). Showing non-diagetic browser UI breaks immersion and should be balanced against security concerns.

**Comment by kearwood** [comment]
To avoid phishing, the trusted UI could be designed in such a way that it can't be replicated by content.  It should be composited with the WebGL content in a buffer that does not allow it to be read back.

If the browser presents the trusted UI with a user specific unique visual cue (ie. a custom icon), the untrusted content would not be able to replicate the interface without knowledge of the visual cue needed.

I'm sure there are some additional methods possible, which would be up to the UA to implement.

**Comment by toji** [comment]
For the sake of clarification: The feature list in the email you read was feedback that we had received from developers about what they would like to see in WebVR, not a list of features that we have committed to including. I would personally like to have page-to-page navigation sooner rather than later, but it's not something that we can promise until we've worked out the ergonomics and security issues (like the one that @jeffcarp brought up.)

Two broad thoughts on the subject: While we may be able to get away with not showing trusted UI at every transition (like the aformentioned same origin links) I think it's important to realize that complete and uninterrupted immersion is probably not a priority (or even a desired feature) for a browser. Doesn't mean we should throw unnecessary UI in the users face all the time, but I expect that we'll generally err on the side of caution when it comes to things like security-centric UX. (Certainly early on. These things do shift over time.)

And I do agree with @kearwood that there should be ways to present trusted UI that can't be easily spoofed by content. Custom icons, user themes, reserved hardware buttons, etc. can all work together to give the user a good sense of when they're in a trusted space.

**Comment by jeffcarp** [comment]
Got it, thanks for the quick replies and clarification.

> And I do agree with @kearwood that there should be ways to present trusted UI that can't be easily spoofed by content. Custom icons, user themes, reserved hardware buttons, etc. can all work together to give the user a good sense of when they're in a trusted space.

I'm not a security expert but this sounds tricky to get right. A secret icon (or any trusted UI) only the UA and user know about is an example of a positive security indicator[1], which have [historically not worked very well](https://security.stackexchange.com/questions/26347/is-sitekey-a-valid-defense-against-phishing). Bank of America used to have you select a security icon that they'd show you during login, but ended up removing it since [97% of users on a phishing site will gladly enter their password](http://www.usablesecurity.org//emperor/emperor.pdf) despite not seeing their icon. This is the same reason why EV TLS certificates [aren't a great defense](https://security.stackexchange.com/questions/52387/does-google-use-extended-validation-certificates) (for example, [google.com](https://www.google.com) doesn't run one). Relying on reserved hardware buttons sounds like the safest bet from a security perspective.

[1] As opposed to a negative indicator, like a broken/red lock

**Comment by kearwood** [comment]
For very sensitive UI, such as entering user passwords, payment information, etc, a more active verification could be added using the "secret icon" approach:
- The "secret image" would be something generated by the user and never selected by a different user.  This could be a scribble done with a controller, picture taken with the camera, etc..
- Before unlocking the password entry form, the user would be asked to choose their "secret image" among a set of others.

This makes it an active process involving the user, which can't be ignored.  If a site tries to mimick this secret image selection UI, it would not include the users "secret image" as would be possible on some of the banking sites that simply asked you to pick the image from a set of a few fixed options.

I wouldn't suggest this extra step be taken for all cases, though, such as choosing to "accept" navigating to a previously untrusted origin.  In these cases, the code at the untrusted origin wouldn't be able to present the phishing UI that requests the access to begin with, let alone grant the privilege if it weren't the actual UA's dialogue.

It would be necessary for cases where sensitive information entered by the user needs protection only.

**Comment by NellWaliczek** [comment]
Closing in favor of #382 and #383
