### ISSUE TITLE
Is XRLayer useful?

### ISSUE THREAD

**Issue by domenic** [immersive-web/webxr#268]
Right now it's an empty interface. Do we anticipate putting things there in the future, so that having a common base class is desirable? If so, that would be great material for the explainer.

**Comment by toji** [comment]
It is indeed intended as a future extension point. At the very least we anticipate needing a new layer type for the unnamed explicit graphics API that will follow WebGL, but we also have discussed using layers for performance, ease of use, and security enhancements for things like DRM video.

We do reference or hint at the intent to allow multiple layers in the future a couple of times, but there's not a really good explicit statement of intent anywhere. I'll look at adding that.

**Comment by domenic** [comment]
But, will the base class ever actually contain anything? If it always remains empty, then it seems better to omit the base class, and just use union types. Do you anticipate polymorphic behavior or data being added to VRLayer in the future?

**Comment by toji** [comment]
Ah, I see what you're getting at. That's a good question, and I'll bring it up with the rest of the group. Related to #258 somewhat.

In the meantime I've added text to the explainer that makes the intent to have multiple layer types and composite multiple layers more explicit.

**Comment by NellWaliczek** [comment]
Potentially related to the work now happening in https://github.com/immersive-web/layers

**Comment by ddorwin** [comment]
Do we need `XRLayer` for extensibility? We only need to worry about current applications working on future user agents that support other layer types, right? There's a good chance we'll need other changes at that time anyway (i.e., #670). Even if not (i.e., adding a layer to support WebGPU), though, it should be fairly straightforward for those user agents to maintain backwards compatibility.

Specifically, future versions of the spec can either:
1. Redefine `XRWebGLLayer` in terms of a base type, which shouldn't affect existing applications.
1. Have `XRRenderStateInit` take a union and provide some other mechanism of obtaining the layer from `XRRenderState`

Since existing applications can still pass and obtain a `XRWebGLLayer`, this shouldn't break them.

@domenic, is there a reason that redefining a type in terms of a base type in the future would be a problem?


<br/>As an aside, it seems that most [1] members of [`XRWebGLLayer`](https://immersive-web.github.io/webxr/#xrwebgllayer) would also be shared with an eventual WebGPU layer and thus might eventually be moved to an `XRGraphicsLayer`. Alternatively, maybe `XRWebGLLayer` could be refactored such that it can be a more generic and renamed to `XRGraphicsLayer`.

[1] It appears that the only WebGL-specific members are:
* `[SameObject] readonly attribute XRWebGLRenderingContext context;`
* `[SameObject] readonly attribute WebGLFramebuffer framebuffer;`

**Comment by ddorwin** [comment]
Related to the aside above, https://github.com/immersive-web/webxr/issues/679 proposes removing the `context` attribute. Then we'd just need to find a solution for the `framebuffer` attribute.

**Comment by domenic** [comment]
> @domenic, is there a reason that redefining a type in terms of a base type in the future would be a problem?

It is theoretically possible for applications to break, e.g. if they do `XRWebGLLayer.prototype.hasOwnProperty('something')` for feature detection, and `something` moves to a base class, then that would start returning false. Partly for this reason, we tend to encourage people to feature detect with `'something' in XRWebGLLayer.prototype` instead, which would continue returning true.

There other esoteric code you could write that would also detect the difference (e.g. directly checking `someXRWebGLLayer.__proto__.__proto__.name`) but I don't know of anything that would see realistic use besides the potential feature-detection code.

 In practice we've successfully done these sorts of redefinings before with no issues.
