### ISSUE TITLE
Change "exclusive" session parameter to "immersive" ?

### ISSUE THREAD

**Issue by speigg** [immersive-web/webxr#320]
The specification currently states that the UA renders only **one** "exclusive" session to an XR hardware device at a time. This makes a lot of sense for VR apps, but not so much for AR apps. For example, via the Argon Browser (a web-based AR browser developed at Georgia Tech) we have been exploring the architectural and UX design issues that emerge from supporting multiple independently-authored AR applications within a single shared view of reality. Given such a use-case, I suggest we rename the "exclusive" session creation parameter to "immersive", and change the semantics slightly for AR apps. 

The rationale here is that the UA would be able to support XR apps in either a non-immersive "magic window" mode or an immersive mode (or both), with the additional distinction that there can only be one immersive VR session per XR device, while there can be multiple immersive AR sessions per XR device. This implies that there also needs to be a way to distinguish between sessions for AR apps and sessions for VR apps (particularly for XR devices that support both AR and VR). In [mozilla/webxr-polyfill](https://github.com/mozilla/webxr-polyfill), this is accomplished with an additional session creation parameter, named "type", which denotes that a session can be either a "reality" session or an "augmentation" session (in other words, VR apps would create a "reality" session, while AR apps would create an "augmentation" session). 

To better illustrate, I've modified the current explainer text to clarify this proposal:

--- 
### Sessions

A `XRDevice` indicates only the availability of an XR device. In order to do anything that involves the device's presentation or tracking capabilities, the application will need to request an `XRSession` from the `XRDevice`.

Sessions can be created with one of two levels of access:

**Immersive Access:** Requested with the `immersive: true` dictionary argument. Immersive sessions present content directly to the `XRDevice`, enabling immersive presentation. Immersive sessions must be created within a user gesture event or within another callback that has been explicitly indicated to allow immersive session creation.

**Non-Immersive Access:** The default mode, but can be explicitly requested with the `immersive: false` dictionary argument. Non-immersive sessions do not have the ability to display immersive content on the `XRDevice` but are able to access device tracking information and use it to render content on the page. This technique, where a scene rendered to the page is responsive to device movement, is sometimes referred to as "Magic Window" mode. It's especially useful for mobile devices, where moving the device can be used to look around a scene. Devices like Tango phones and tablets with 6DoF tracking capabilities may expose them via non-immersive sessions even if the hardware is not capable of immersive, stereo presentation. Any non-immersive sessions are suspended when an immersive session is active. Non-immersive sessions are not required to be created within a user gesture event.

Sessions can be created as one of two types:

**Reality Session**  The default session type, but can be explicitly requested with the `type: 'reality'` dictionary argument. Reality sessions denote that an application intends to render a complete environment, and are thus suitable for VR applications. Only one immersive reality session per XR hardware device is allowed at a time across the entire UA.

**Augmentation Session** Requested with the `type: 'augmentation'` dictionary argument. Augmentation sessions denote that an application intends to augment an existing environment, and are suitable for AR applications. When using an augmentation session, the rendering context is transparent and the UA may composite in a view of reality behind the session layer, if necessary (this would not be necessary for optical see-through displays). Multiple immersive augmentation sessions per XR hardware device may be allowed at the discretion of the UA, with their layers composited together by the UA.

**Comment by blairmacintyre** [comment]
We talked about this on the call, but I thought I would follow up.  

I understand that folks don't want to dive into considering how to deal with multiple simultaneous sessions, as Nell and I chatted about months ago, but I don't think that's what @speigg is really suggesting here (he discussed it as context and background).  He's interested in this capability, in the context of his experimental browser (soon, "ArgonXR") and suggested that changing "exclusive" (i.e., the semantics are that you know you have complete control and are the only display) to "immersive" (i.e., you are requesting to display an immersive experience) would leave that option open to browsers if they wanted to implement it.

I worry about the long term impact of giving application authors the ability to demand "exclusive" control.  Right now, I agree we don't want to have multiple apps at a time as a requirement (for performance reasons, for example, but also because we don't understand how the UI would work, don't know how to deal with security issues, and so on).  So, "immersive" will mean the same thing as exclusive right now.  It would be up to the UA to decide if it wants to allow multiple immersive apps at once (in AR or VR or both).

I'm not seeing what the issue with this is that is the responsibility of WebXR.  Yes, there are massive questions of UI, security, user understanding, and so on:  but, aren't these browser issues?

It seems (to me) that if at some point in the future UI metaphors emerge to support some sort of "multi-app" ecosystem, and browsers or OSs support the capability, that the choice of "shared or exclusive" display is the sort of decision a user should make, not an application.  So giving applications the option to demand "exclusive" access to the display and devices doesn't make sense to me. 

Looking back at the evolution of 2D window systems shows a similar evolution, and how assumptions about what the App could expect evolved and caused many apps to break, or be frustrating to use.  At the time, developers (of systems, and apps) didn't conceive of the kinds of window systems that "won" (overlapping windows with multiple applications running at once).
