### ISSUE TITLE
WebGL: INVALID_FRAMEBUFFER_OPERATION: drawArrays: cannot render to a WebVR layer outside of a frame callback

### ISSUE THREAD

**Issue by playground** [immersive-web/webxr#377]
I couldn't find an answer to this error, I hope this is the right place for this question.  Please see this https://github.com/makimenko/angular-template-for-dummies/issues/9.  Looks like something is getting place when the click on anchor, just not rendering the model (fox).

**Comment by toji** [comment]
In WebXR we have introduced a requirement to only render VR or AR content in the callback provided to an `XRSession.requestAnimationFrame` call. This is necessary because that's the only way to actually get pose data out of the API.

When using WebGL directly to render the context of this error will typically be a bit more obvious, but when using a library like Three.js it can get obscured. Fortunately I know that the newest versions of Three.js have WebXR support and several examples showing it working relatively well, so the first step I would take is to ensure you are using the latest version of the Three.js library.

Second, it would appear from the linked issue that you ARE able to render something, and as another comment pointed out the fox simply appears really tiny. WebXR enforces a consistent scale of 1 unit == 1 real-world meter, so in general I would try to create or scale your 3D models in advance to match that.

**Comment by playground** [comment]
Thank @toji scaling up the model, it shows it's rendering the .png file instead.

![image](https://user-images.githubusercontent.com/243495/42659257-b9f4f988-85f5-11e8-8104-082e30e5e241.png)

**Comment by toji** [comment]
Hm. Given that you're getting any rendered results at all, this feels like a library specific issue that I won't be much help with, sorry!

**Comment by playground** [comment]
Hmm, it basically is a direct port from this example https://codelabs.developers.google.com/codelabs/ar-with-webxr/#6, I must be doing something wrong :-(
