### ISSUE TITLE
WebXR Modes

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#394]
Putting aside entirely for a moment the question of how `XRSession`s are created and managed, recent conversations with Chrome's Privacy and Security team have shuffled Google's perspective on what contexts AR data should be accessible from. Fortunately, in conversations thus far, most other teams have found the shift agreeable and/or closer to what they were hoping to do anyway, so there does not appear to be much controversy. It does mean, however, that we need to re-examine the various modes an `XRSession` can operate in. This issue attempts to lay out one proposal for how it might work.

XR Mode
-------

Sessions will operate with a specific “XR Mode” at any given time. The XR mode represents the way that WebXR content from that session is presented to the user. It's tempting to call this a "display mode" but I've actually come to think about this more in terms of defining how users will interact with the content rather than dictating how and where it's displayed. (I believe that [Blair has advocated for that approach](https://github.com/immersive-web/webxr/issues/388) in the past.)

The necessary modes as I see them today (names subject to bikeshedding) are:

 - **Inline**: Content shows as an embedded element on a page, and is denied access to any environmental data. This should be the “default” mode if the API shape allows for it.

    In keeping with previous discussions regarding a Unified Rendering Path (aka: [Poseless sessions](https://github.com/immersive-web/webxr/issues/367)) I would propose that inline sessions also do not expose any motion tracking data by default. Sessions with that configuration should be guaranteed to be consent-free by the UA so that developers have a predictable baseline to start from, ensuring that content can consistently be rendered with a single draw loop no matter how the `XRSession` is configured. Inline sessions should be accessible without user activation or frame focus.

    Motion tracking data (such as orientation for phones or actual head-relative-to-page tracking for zSpace-like devices) should still be requestable, likely as a “feature”, which would allow the UA to request user consent if desired. Frame focus would likely be required. Even in the absence of head tracking, the nature of WebXR's render loop allows this content to be rendered in stereo if applicable, providing another benefit to using this mode over a simple WebGL canvas.

    This mode should be restricted to Simple Input Model only, with no controller tracking. (Interactions with an in-XR browser using a controller would be treated as traditional pointer input against the canvas, which is then converted into simple “select” events)

 - **Immersive VR**: Effectively the same as the immersive mode we have today. The term is under discussion but I'll continue using it here since everyone by now understands how it's used in the spec. This mode would enable controller tracking and the Advanced Input Model in addition to the Simple Input Model. Only accessible with user activation and frame focus.

    In the case where the headset is transparent, this becomes a sort of forced AR mode. Your content just shows up in the real world whether you want it to or not. We inform authors of this via the `environmentBlendMode` attribute. Authors should use the appropriate mode (below) if they are intending to render on the real world. In the future, devices may support both VR and AR on the same display, so it is important that authors choose the appropriate mode. This mode should be limited from accessing environmental data.

 - **Immersive AR**: Please ignore the name, we can bikeshed that later. This is the new ["AR Mode"](https://github.com/immersive-web/privacy-and-security/blob/d1a8ded7262e7d3d8c368fd57093a69b5fc53536/ARModeExploration.md). Environmental data (camera feed, environment meshing, etc.) is accessible in this mode, though access to that data ends when the mode is exited. This mode should only be accessible with user activation and frame focus, and should be treated as an “exclusive” mode, just like immersive is today.

     A crucial distinction is that it would display “as immersively as possible” for the given device. That is, on a phone it would simply be a fullscreen mode while on an AR headset it would be fully immersive. It’s an open question for me if the same approach is valuable for Immersive VR as well.

(Though I'm not focusing much on API details here, the above suggests the XR mode be passed as an enum rather than a simple "immersive" boolean. That also means it could be extended in the future if needs be. [@ddorwin](https://github.com/immersive-web/webxr/blob/f064e47ca7a5696501a86a6b6bd11eb39388226f/session-creation-explainer.md#what-level-of-confidence-should-supportssession-provide.) suggested this a while back, though I don't recall if it was internally to Google only or ever made it out to a GitHub issue.)

Feature detection
-----------------

It's generally agreed upon that we need the ability to feature detect at a high level to decide whether or not to show users buttons to enter into one of the user activation-required modes. This test should only consider the XR Mode. This is due to the fact that we want to minimize fingerprinting and not require that the underlying systems be spun up just to check feature availability, so individual features (like lighting, environment meshing, or camera access) should not be testable prior to starting a session.

My expectation is that users will generally be able to understand what it means for content to be "VR" or "AR", but beyond that the details get a lot more technical and nobody needs or wants to display buttons for more detailed modes than that. Thus checking for the high level mode is important because it allows the page to communicate the availability of AR/VR features at the broadest level.

Other features beyond the XR mode should be requested as a group to ensure the UA has the ability to request consent for them as in a non-obtrusive way to the user. It's expected that some UAs will offer the user the option to reject some features but not others. In those cases the features with revoked consent should appear to the page as identical to a missing feature. Reporting a feature as being supported beforehand would leak information about it's presence and the user's privacy preferences.

HTML Overlay
------------------
With the addition of the explicit [AR Mode](https://github.com/immersive-web/privacy-and-security/blob/d1a8ded7262e7d3d8c368fd57093a69b5fc53536/ARModeExploration.md), in my view it's critical that this mode provides a way to display an HTML element (and its subtree) composed over the AR content, similar to how the fullscreen API presents a single element in a modal way. That'll make content authoring significantly easier for developers, and discourage them from using JS-only libs like AR.js simply because it allows for better integration with standard HTML controls. (Note that I view the HTML overlay as a distinct concept from displaying DOM in 3D space.)

Setting the HTML overlay seems like it could be well handled as a separate call from the mode transition, and UAs should have the ability to reject the request to set an overlay if the given device/mode/UA combo can’t support it. (Support for overlays should also be communicated ahead of time so that we don’t get content transitioning to XR, failing an overlay, and immediately transitioning back out.) No concrete proposals are being made for how such an overlay would be specified at this time, I’m only earmarking it as a topic I feel is important.

One of the possibilities that could be opened up with a simple overlay system is a forward compatibility mode to ensure that content made for 2D screens does not become inaccessible to users with AR headsets. As such, the contract should be something more along the lines of this: If you use an overlay (and the UA accepts it) the UA will ensure that the overlaid element will be accessible in some capacity, but not make many guarantees about how it will be presented.

That way while the phone AR case is clearly the immediate goal more advanced devices can experiment with various compatibility modes such as:
 - Having the overlay HTML be a floating window in space
 - Attaching it to your wrist
 - Pinning it to a wall
 - Showing/hiding it with the push of a button

This is significantly complicated if we expect (as I do) that developers will try to create content that aligns DOM elements from the overlay with content rendered in the WebGL layer. I don’t have a good solution to this at this time, and would love to gather the communities thoughts. Some initial approaches that I can think of would be to either offer explicit APIs to communicate the spatial relationship of the WebGL and HTML content to make said alignment reliable OR double down in the other direction and explicitly make such alignment nearly impossible. :)

It’s worth noting that in order to maintain maximum UA freedom when compositing elements like this, we may want to update the spec to either indicate that the `XRWebGLLayer` depth buffer contents may be used by the UA for compositing, or at the least allow developers to indicate that the values they are leaving in the depth buffer are well formed. (ie: Don't fill the depth buffer with garbage or clear it at the very end of your frame or anything silly like that.) Of course the UA can choose to discard or preserve the depth information as needed.

Thoughts?
-------------

I’m eager to get the rest of the community group’s feedback on this idea, especially if the idea of restricting AR content to one of the “exclusive” modes is problematic for known content that you or your users want to produce. If there’s no big red flags sent up on this I’ll try and get out a pull request for the explainer with more concrete IDL/functionality proposals soon. Thanks!

**Comment by TrevorFSmith** [comment]
Great work on finding the balance for so many competing concerns! In general, this feels like it's on the right track.

As I'm writing an app framework that treats XR as a responsive display mode along side the current flat display mode, the framework needs to able to answer the following questions:

## Does this device offer inline, portal + overlay, and/or headset display modes?

## Is it possible to provide a view of reality (regardless of see-through or pass-through)?

The app author can then decide how to present the user with UI for transitioning between display modes,  be it buttons for "AR" and "VR" or less tech-oriented feature buttons like "See this on your wall".

**Comment by TrevorFSmith** [comment]
For the depth buffer, we should ensure that apps can present a virtual environment for part or all of what is an "AR mode" session. You can see this in glorious action in [this recreation of the old A Ha! music video](https://youtu.be/V7CKH2cq49E). So, if the UA is going to use the depth buffer for occlusion we need to add guidance so that authors can indicate that they don't want occlusion for part or all of a render.

**Comment by blairmacintyre** [comment]
(First, I generally agree with this direction, and have chatted with "Brandon & Co" 😸 about this already.  Good work, team!)

> My expectation is that users will generally be able to understand what it means for content to be "VR" or "AR", but beyond that the details get a lot more technical and nobody needs or wants to display buttons for more detailed modes than that. Thus checking for the high level mode is important because it allows the page to communicate the availability of AR/VR features at the broadest level.

What are you thoughts on multiple devices and conflicting modes?  I can imagine a future where I have a few displays that are wired and wirelessly paired with my device (be it a phone or computer), and so I have a few different available devices of each mode.  

As a developer, I might want to know that there are N devices offering one or more of each of the modes, and making each of the "enter AR", "enter VR", etc buttons pop up a menu if there are multiple choices.

Or, I could imagine that we just have one button for each mode, and when we do "enter AR", one part of the permission / dialog that the UA pops up lets the USER pick which to use (if there is more than one device that matches the mode).

**Comment by blairmacintyre** [comment]
> This is significantly complicated if we expect (as I do) that developers will try to create content that aligns DOM elements from the overlay with content rendered in the WebGL layer. I don’t have a good solution to this at this time, and would love to gather the communities thoughts. Some initial approaches that I can think of would be to either offer explicit APIs to communicate the spatial relationship of the WebGL and HTML content to make said alignment reliable OR double down in the other direction and explicitly make such alignment nearly impossible. :)

I think that if we help devs understand that they are in HMD vs portal mode (i.e., the Overlay is a real overlay, or it's going to be positioned at an arbitrary place in space by the UA), they can decide when or when not to do this.

We may heavy use of CSS3 3D Transforms and the Perspective properties to align DOM content with WebGL and real world content in Argon;  heck, if you look at our Argon+AFrame demos, we have AFrame components to align DOM elements in the scene graph.  It's very powerful.  So, people will want to do it.

I could imagine going one step further here, btw:  since the DOM overlay is being treated (and possibly rendered) in a special way, we might even want to give the developer the option to mix the Z buffer.  Then we could really put DOM content in 3D.  

On the other hand, we may want to discourage this, because heavy use of 3D parts of the DOM is pretty innefficient (because of repaint/repair overhead when you set a transform);  it's the elephant in the room with poor AFrame performance on non-trivial scenes, after all.

**Comment by toji** [comment]
Ooh! Lots of great feedback really fast! Love it!

>  Does this device offer inline, portal + overlay, and/or headset display modes?

> I think that if we help devs understand that they are in HMD vs portal mode (i.e., the Overlay is a real overlay, or it's going to be positioned at an arbitrary place in space by the UA), they can decide when or when not to do this.

Concrete IDL proposals are in the works, but at the moment I"m leaning towards a direction that would have you ask "I want immersive AR" and have the framework respond with something along the lines of "That's supported, will be displayed on a 2D screen, and is compatible with overlays." Give the developer enough info up front to decide if the content's presentation will match their requirements.

> So, if the UA is going to use the depth buffer for occlusion we need to add guidance so that authors can indicate that they don't want occlusion for part or all of a render.

Yeah, the depth buffer thing is probably the least thought-out part of all of this. It's been something that have come up in the past for VR, since it can help with things like reprojection on desktops, so I'm mostly just carrying that musing forward.

> What are you thoughts on multiple devices and conflicting modes?

When talking about something like multiple headsets being connected I think my opinions are largely unchanged: The UA should have a default device that they can change at a UA or system level. There's maybe some leeway for saying "Hey, device 0 doesn't support AR but device 1 does, so I'm going to switch silently" but that probably leads to unnecessary complications in both GPU context compatibility and navigation.

> one part of the permission / dialog that the UA pops up lets the USER pick which to use

This is more realistic in a world where we don't allow inline AR, sure. I still worry about context compatibility in that case but it may be a moot point depending on the platform. Probably best left to the UAs discretion?

**Comment by TrevorFSmith** [comment]
> I'm leaning towards a direction that would have you ask "I want immersive AR" and have the framework respond with something along the lines of "That's supported, will be displayed on a 2D screen, and is compatible with overlays." Give the developer enough info up front to decide if the content's presentation will match their requirements.

Perfect!

**Comment by RafaelCintron** [comment]
**Re: Overlays**
> (Note that I view the HTML overlay as a distinct concept from displaying DOM in 3D space.)

For all practical purposes, what is the difference between these two concepts?  Is the overlay rendered in a different manner that I am missing?  One you go down the route of doing the things you brought up (attaching to write, pinning to wall, etc) the "in 3D space" part becomes important.  

How will input be handled for this overlay?  Can you scroll the HTML content or type in an edit box?  I presume we'll be punting on this problem initially but just making sure.  :-)

> UAs should have the ability to reject the request to set an overlay if the given device/mode/UA combo can’t support it.

What is an example of a device/mode/UA combo that will not be able to support overlays?  

**Re: Depth buffers**
WMR lets you submit a depth buffer to help with re-projection.  It works for more than just desktops, Hololens as well.  

I agree that if we do this, the web developer will need to be aware and treat the depth buffer as an "output" just like the color texture. For opaque framebuffers, we have a depth buffer we can use.  For the [WebGL 2 based approach](https://github.com/immersive-web/webxr/issues/317), the API can provide an optional depth buffer that serves this purpose.

**Comment by speigg** [comment]
This is great!

First, I assume that either of the two Immerisve modes (both Immerisve VR and Immerisve AR) would run “as immerisvely as possible” on a given device.

Secondly, I take it that “Immerisve” is now being used a synonym for “XR”, which I would define as: the use of sensing and display technologies to engage a user within a 3D environment (physical, virtual, or mixed) which can be freely navigated (by the user) in three or six degrees of freedom.

Thirdly, I believe that drawing a distinction between an “AR mode” and a “VR mode” is 100% the basis for the right architectural model, as this distinction is what is needed to ensure maximum future flexibility in how multiple XR applications might be composited together by the UA. 

Nevertheless, I would suggest moving away from the terms “AR” and “VR”, as they carry a lot of assumptions that are unnecessarily limiting for an XR architecture. My suggestion is to use the following terminology for the three XR modes:

- Immersive Environment mode (instead of Immersive VR mode) for applications that present a virtual environment 
- Immerisve Augmentation mode (instead of Immerisive AR mode) for application which present content that is meant to be composited against an existing environment
- And Inline mode is fine for inline presentation

**Comment by blairmacintyre** [comment]
> When talking about something like multiple headsets being connected I think my opinions are largely unchanged: The UA should have a default device that they can change at a UA or system level. There's maybe some leeway for saying "Hey, device 0 doesn't support AR but device 1 does, so I'm going to switch silently" but that probably leads to unnecessary complications in both GPU context compatibility and navigation.

Funny, that's the reverse of what I'd imagined (I imagined reactive, like WebRTC, picking a device as part of session permissions), but this greatly simplifies things if it would work.  I don't have any sense at all of how this might manifest and how much friction it would add (e.g., I hit enter XR, realize I had the wrong device selected, need to cancel and reload the page possibly, after changing the device).

But, this could very much be a UA thing.  You could imagine that when a page is loaded that supports XR, a UA button (on a 2D browser) could appear that allows you to pre-select the device. 

And all of this only matters when there are multiple devices, OR when we're in a "the page is displayed on a different device than I will use".  So, Daydream/GearVR or  Desktop + connected HMD.  But if you're already in VR/AR, then it seems the mostly like device is the one your in.

**Comment by toji** [comment]
Relaying some of the results from yesterday's AR face-to-face discussion here. The high-level conclusions were:

- Everyone seems in favor of having an explicit AR mode to start with. It should be noted that this does not preclude us ever adding an inline AR mode in the future, but it will not be part of the initial spec.
- There's more mixed reactions about the use of DOM overlays, and it feels to me like support for the concept is going to largely come down to how the API surfaces the feature and what kind of guarantees we give developers.
  - On the one side there's some concerns about AR headsets potentially being forced to support DOM overlays when they would be difficult to make work well on the platform.
  - On the other hand there's a desire to let content authors have a "lowest common denominator" mode that makes content production as easy as possible. (Specifically: Not requiring WebGL for simple UI) and allowing some devices to opt out of showing the DOM would force developers to build their interaction model twice for the widest support.
 - Regardless of what direction we go, there appears to be general agreement that we should ensure that each form factor CAN be targeted by developers to create the best experience everywhere. (It's assumed that the right interaction model for phone AR is not the same one as for headset AR.)

Because of the concerns around DOM use, we'll split that specifically into a separate issue and move forward with the idea of an explicit AR mode in this one. I'll try to get a pull request up within the next day or so on that topic so we can iterate of the exact API shape, though I suspect the "modes" aspect is going to be pretty simple relative to the DOM interaction.

**Comment by ddorwin** [comment]
> Concrete IDL proposals are in the works, but at the moment I"m leaning towards a direction that would have you ask "I want immersive AR" and have the framework respond with something along the lines of "That's supported, will be displayed on a 2D screen, and is compatible with overlays." Give the developer enough info up front to decide if the content's presentation will match their requirements.

This pattern should work well for navigation too. The application can say it wants AR, VR, or either and (if a requested mode is supported) get an object for a configuration that the UA has decided (possibly based on the current state) is appropriate.

**Comment by blairmacintyre** [comment]
I think we need to simplify the DOM overlay discussion:  make it optional to support it, present it as a "should" or "must" be supported on handhelds but optional when it comes to HMDs or any "pure 3D presentation".   I felt that all of the discussion at the F2F focused on the HMD case, and I agree it's difficult.

**Comment by blairmacintyre** [comment]
Speaking for myself, a light bulb went on during the recent discussions, where we do not enumerate devices in the WebXR API, but rather let the UA (user) choose what device to use, or what their current default is.  This GREATLY simplifies things.  So, "I want immersive AR with features X/Y/Z" boils down to a query against the immersive AR device the user/UA choose, not "all possible AR devices available from this device".  Clean and simple!

**Comment by toji** [comment]
> I think we need to simplify the DOM overlay discussion: make it optional to support it, present it as a "should" or "must" be supported on handhelds but optional when it comes to HMDs or any "pure 3D presentation".

Agreed, and this is definitely the direction I'm leaning at this point. For me the larger question is if/how/when to communicate availability of DOM overlays it to developers.

**Comment by DrX3D** [comment]
>     I think we need to simplify the DOM overlay discussion: make it
>     optional to support it, present it as a "should" or "must" be
>     supported on handhelds but optional when it comes to HMDs or any
>     "pure 3D presentation".
>

I disagree. It is my understanding that this specification is being 
developed for use on the Web using WebGL in a User Agent. I know that 
not all User Agents are web browsers, but that distinction will be lost 
on most everyone. So I have what looks like a web browser because it can 
browse the web. It may present the material in 3D rather than a flat 
display/projection. It also has the capability of including physical 
world views and integrates them with computer generated graphics.

So it looks like a duck, browses like a duck, but it's not a duck.

Now you tell content developers that a DOM overlay (meaning HTML + CSS) 
may not work on all devices. That means they will need to develop two 
sets of UIs - one for DOM and one for non-DOM. Yeah, right.

There will be a proliferation of very poor 3D UI (because good UIs are 
hard, and 3D UIs are even harder). It will take a while (my guess is 2-4 
years) before some good libraries are available that provide more or 
less standard 3D UIs. You now have a 3D web that is rather disconnected 
from the existing 2D web.

I have yet to hear any good argument (to me) that certain HMDs need to 
exist in the Web space and cannot implement DOM overlays. I have heard 
reasons such as providing timely view matrix updates or the slowness of 
CSS to handle 3D rotations. From my observations, if those are critical; 
they will be improved to the extent needed. Perhaps the initial release 
only allows for a DOM plane at the near clipping distance and not at 
various scene depths.

The last thing that is needed is a lot of code to handle the continuum 
from non-existent DOM to full DOM overlay.


-- 
*Leonard Daly*
3D Systems & Cloud Consultant
LA ACM SIGGRAPH Past Chair
President, Daly Realism - /Creating the Future/

**Comment by DrX3D** [comment]
@blairmacintyre: This message addresses requirements of the IW 
environment. I have separate comments about the implementation items you 
raised. I will get to those later.


I wish to examine the domain of where the IW standards do apply. I think 
that may help in clarifying what results need to be specified and what 
is out of the domain (and out of scope). It appears that there are two 
issues (this - https://github.com/immersive-web/webxr/issues/394 and 
#400 - https://github.com/immersive-web/webxr/issues/400) both 
discussing the same topic. Perhaps things should be clarified a bit.

I think there is complete agreement that these standards apply to 
traditional web browsers running on the desktop/laptop or mobile device. 
If this statement is incorrect or needs further clarification please 
respond. I think this needs to be completely clear and agreed to by the WG.

The rest of the response assumes that there is not complete agreement 
when dealing with non-traditional web browsers and other user agents. 
 From a hardware perspective this seems mostly to apply to various 3D or 
HMD. This is longer than I wanted because I could not find documents 
that described the domain of applicability in W3C documents. Perhaps my 
search was not intensive enough.

I have seen many uses of the term 'User agent' to describe the target 
software platform for the IW specification. According to the W3C 
(https://www.w3.org/standards/agents/browsers) a user agent provides a 
human or machine interface to the web. It also implies that 'web 
browser' is a subset of UA (based on other W3C documents, e.g., 
https://www.w3.org/WAI/UA/work/wiki/Definition_of_User_Agent) because 
UAs also include media players. The use of the term 'User Agent' seems 
to be closely tied to the User Agent Accessibility Working Group. 
[Side-note: does that mean that accessibility needs to be considered for 
the IW specification?]

So does the IW specification run in the software environment of a User 
Agent?

I could not find an explicit statement that User Agents must support 
various W3C specifications such as HTML, DOM, CSS, etc. so the questions 
I have below. From everything I have read and heard, the IW 
specification will require the following software support. This is not 
intended to be an exhaustive list.

 1.   JavaScript
 2. WebGL
     1. WebGL adds interfaces to the DOM
        (https://www.khronos.org/registry/webgl/specs/latest/2.0/#3 -
        also in V1.0). Does that imply DOM is required?
     2. DOM includes a dependency on XML
        (https://www.w3.org/TR/domcore/#dependencies)

So if XML is required, I should be able to create DOM elements. It 
remains to be specified how they would appear in the display.

Looking at this going backwards, if I start with the assumption that 
there exists devices that can display IW content and are not a 
traditional browser (includes HTML, CSS, DOM, etc.), then either the UA 
is a media player or some other content-specific device that plays (and 
provides for interaction with) a particular set of file formats. As 
currently being defined, IW is an API; which implies that the file 
format is a ECMAScript (i.e., DOMless JavaScript) program.

I am concerned that if the domain of applicability or system 
dependencies are not clearly specified and include exactly what is 
required, then there major issues with adoption by developers.

-- 
*Leonard Daly*
3D Systems Architect & Cloud Consultant
President, Daly Realism - /Creating the Future/

**Comment by blairmacintyre** [comment]
@DrX3D sure, this should be made explicit in the WG description and charter.  I wouldn't disagree with that.  If you don't feel it is, perhaps suggest changes.

Independent of that clarification:  your previous post essentially said (to me, which is what I was replying to) that if we don't support putting HTML/CSS content in 3D, that the WebXR Device API is fundamentally broken, because we'll be requiring developers to create 3D UIs.  Perhaps I'm reading too much into it.

I guess I don't see the problem:  yes, there will be web pages that are designed for 3D and those that are designed for 2D.  There will definitely be ways of browsing 2D pages in 3D (see Edge, Firefox Reality and Helios as examples);  for some pages this will be "awkward, but usable if need be".

UIs for "3D" (AR/VR) applications on touch devices (holding a portal in my hand with a touch screen "mediating") will be different than UIs on head-worn devices (perceptually inside a 3D world with no obvious "screen" to mediate, no effective way to "touch", etc).  Any presentation of a DOM overlay designed for a touch screen inside a 3D world will be no less "awkward, but usable if need be" that display a full 2D page in 3D. 

Yes, it will take a while for good 3D UI toolkits to emerge.  Just like it took a while for 2D ones to emerge.  And, the web evolved with those toolkits as the tension between "simple web" (pure, simple tagged markup with no CSS or real layout control) and "design control" (designers wanting more control over layout and interaction) played out.  HTML5/CSS3 could not have be conceived of before we went through the disaster that was DHTML and IE6 plugins. 

In the end, it seems clear to me (based on experience with folks building handheld web-based AR over the last 10 years or so) that web devs will want, and benefit from, being able to create 2D UIs on touch screen-based AR.  The rest (2D elements in 3D in various ways, be it "iframes" or individual elements or whatever) is much less clear;  people might say they want it, but it's unclear if that's because it's the right solution or because the alternatives suck (i.e., there aren't good 3D toolkits yet)

**Comment by DrX3D** [comment]
@blairmacintyre: I'm not quite sure where to start. I don't really disagree with what you have stated - I think our approaches is to the same goal from different paths.

I don't know about the details of the WG charter. I have not read it for that level yet. For now working from memory, I sort-of suspect that the charter states that the WG will work with other W3C WGs to create consistent and compatible standards. I would be surprised if it goes really deep. The specification is another matter.

I see two cases.
1) The specification either by implicitly or explicitly requires DOM, CSS, HTML
2) It explicitly declines the requirement for DOM, CSS, HTML, though it may allow them to be used.

Case (1) can be tricky to follow, especially implicit requirements. I think that the document should be really clear on this so there is no confusion or misunderstanding. If there is a requirement for those technologies, then I would hope that the 3D device manufactures speak up soon. Creating an un-implementable specification is bad. I know there is a W3C requirement for having two implementations, but it could happen that the two implementations do not cover this (3D devices) situation. Perhaps that should be adopted by the WG to make sure there are no issues.

Case (2) explicitly declares that HTML is not required for this specification. I would not call this specification broken - I tend to reserve that term for specifications that are inconsistent or majorly incomplete. I would like to see as part of the official results of the WG how this is used and interacts within the larger web ecosystem. Right now I don't see how to do it; but that is probably more a function of my imagination.

Neither of us wants to see bad UIs, but I gather you think the best way to get to good UIs is open experimentation where there may be no 2D version to use. I would rather not force people to have to go without a net. Perhaps the deciding factor is market share of screen vs. screen-less (3D) devices. If the screen-less devices are <10%, then it might be much better to "remove the net" and let that segment work on the UIs for 3D.

I will take a detailed look at the charter to see if anything is implicitly required in this area. 


I would like to point out a few problems with incorporating HTML (or 2D) into the 3D display - independent of the device type. Some of these were previously listed (especially by @blairmacintyre)

1. How is the extent of the 2D content region specified. It's easy for a regular browser; but if the 2D content region occupies all of the horizontal (not just the visible part on the screen, but 360), what is done about wrap-around. The problem just gets worse in the vertical.

2. If the 2D content region is not all-inclusive, is it pinned to the screen, to the physical space, or to something else? This is equivalent to the situation of making a heads-up display vs. in-scene billboards.

3. Is there any limitation as to the type of elements that can be used in those content regions? I don't see a problem with standard text-type elements, and probably not with static images; but there are animated GIFs. What about other content such as SVG, movies, XR? If you limit what can be displayed, how is that propagated to content in an iframe. That content may have no connection the parent material and a perfectly good web page may fail because of some restriction it doesn't know about.

4. How do various dynamic elements that respond to user actions, e.g., touch, mouseover, etc. I suspect that this is one of the easier ones to solve, but I do not know what a "standard" solution would be.

**Comment by ddorwin** [comment]
This can be closed now that #419 landed?

**Comment by toji** [comment]
Yes, it should be. Thanks.
