### ISSUE TITLE
Is an XRFrame object valid after the frame it represents has elapsed?

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/webxr#403]
How do XRFrame objects work with respect to previous frames? Is it possible for XRFrames to store historical frame data? If so, does this mean underlying implementations NEED to store historical tracking data?

To put it another way, can XRFrame objects be stored outside of the callback in which they are issued?
Note: if XRFrame object is not valid outside of the callback, it would discourage us from using promises in any API that resolves with XRFrame objects. This might make us want to avoid promises entirely in the API to avoid inconsistency. This is a potential downside of such a decision since promises are a very common and friendly way of doing async APIs.

**Comment by NellWaliczek** [comment]
Hey Max, 
Is this issue covered by the discussion in https://github.com/immersive-web/webxr/issues/384 ?
Nell

**Comment by lincolnfrog** [comment]
@NellWaliczek I don't think its the same issue. They are definitely related, but this issue could be decided in several different ways without impacting #384 . 384 is about how XRFrames interact with XRCoordinateSystems, this issue is more about the lifetime of an XRFrame object itself and whether underlying implementations have to track historical data to support queries on previous frames.

**Comment by toji** [comment]
This was marked for discussion at TPAC, but [according to the minutes](https://www.w3.org/2018/10/25-immersive-web-minutes.html) it was deferred to the anchors discussion but then never revisited.

The opening comment mentioned that one of the primary reasons for wanting to keep `XRFrames` active outside the initial callback is so they can be used in promises, but as I've argued in #411 (which appears to have positive sentiment towards it) we shouldn't be using promises for timing sensitive data and I definitely view `XRFrame`s as pretty much the textbook definition of timing sensitve. As a result, if we subscribe to the guidelines I proposed in #411 they should be only handled in either callbacks or events. Happily that's already the case today!

As for the lifetime of the frames themselves, I would propose that a frame be given an explicit (but non-JS visible) "active" bit that is set just prior to the relevant callback being fired and then cleared as soon as control is returned to the browser. Since we can't stop users from actually holding onto the objects, we'll want to disable them outside of the desired valid context. If any of the query functions for the frame are called after the active bit has been cleared they would throw an exception. (We could be cute and throw a [TimeoutError](https://heycam.github.io/webidl/#timeouterror), but realistically a [NotAllowedError](https://heycam.github.io/webidl/#notallowederror) is probably a better fit.) That way we make it explicit that `XRFrame`s have a strict lifetime and there's no point to holding onto them once they've expired.

Happy to put together a pull request to add this to the explainer unless anyone strongly disagrees.

**Comment by lincolnfrog** [comment]
+1, but @thetuvix should weigh in - I think this meshes with windows mixed reality - it's important to know that an XRFrame object that gets passed into a controller event may represent an older state of the world than the one that happens in a RAF very shortly afterwards. As long as Apps don't try to reason about equality between XRFrames, this should be fine?

**Comment by toji** [comment]
Fixed by #428
