### ISSUE TITLE
Domevent can't track the object position and perform clickout.

### ISSUE THREAD

**Issue by TommyySin** [immersive-web/webxr#438]
I am currently doing a project which need to tap on the object and get response.
This is the immersive-AR side.
Anyone has any ideas?
Thanks

**Comment by toji** [comment]
The API doesn't provide a direct mechanism to detect which objects are being clicked on because it's use of WebGL means that the rendered images have no semantic context. It's assumed that applications will do their own collision detection logic to determine what the user is interacting with.

That's definitely not a trivial task for many developers, so I recommend looking into using a library like [Three.js](https://threejs.org/) if you're not already. It provides simple ways of detecting when [objects intersect with a ray](https://threejs.org/examples/#webvr_dragging), which is what most WebXR interaction is based on.
