### ISSUE TITLE
How does the identity reference space relate to any other space?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#478]
@RafaelCintron asked me a good question here that is underspecified.  What happens if an app attempts to relate the `"identity"` reference space to any other space?  I'd expect `getPose` to return null for that request, since a disconnected identity space is by definition not positioned with any stable relation to any real-world objects.  However, we should probably specify that explicitly.

_Originally posted by @thetuvix in https://github.com/immersive-web/webxr/pull/459/files_

**Comment by NellWaliczek** [comment]
Fix was removed from #491 because it was inadequate

**Comment by toji** [comment]
Coming back around and giving this some further thought: We probably need this to have more complex behavior than simply returning null for everything other than `getViewerPose`. The reason being that an `identity` reference space will be used primarily for `inline` sessions and in that context we still want to be able to properly process `screen` input sources so that click and tap interactions can continue using a unified model. That means the `targetRaySpace` needs to give a sensible result.

So that's a bit harder to explain cleanly than "It's null for pretty much everything." We could carve out screen input sources as a singular exception, I guess, but I'm not sure if that's sufficient. Alternately we could say that it should return all other poses relative to the viewer, but that actually means you could reasonably produce tracking values for pretty much everything, which grinds against the permissions model we want to have for `identity`, which is that it doesn't require permissions.

**Comment by Manishearth** [comment]
> Alternately we could say that it should return all other poses relative to the viewer, but that actually means you could reasonably produce tracking values for pretty much everything

Not necessarily, to query any space that can be related to identity in a way that requires tracking (e.g. `eye-level`) you'd need tracking permissions _anyway_, yes?

See also: https://github.com/immersive-web/webxr/issues/565 , where I was initially confused as to what identity actually _was_ since I assumed you could relate it to other spaces.

**Comment by cwilso** [comment]
Should be fixed by the fix for #597

**Comment by Manishearth** [comment]
See also: https://github.com/immersive-web/webxr/issues/623
