### ISSUE TITLE
XRRay constructor spec bugs

### ISSUE THREAD

**Issue by NellWaliczek** [immersive-web/webxr#490]
In the "construct-ray-origin-direction" algorithm, {x:0, y:0, z:0} doesn't represent a valid direction, so we shouldn't allow the XRRay to be constructed.

**Comment by NellWaliczek** [comment]
In the "construct-ray-transform" algorithm, these two steps don't save anything:
    1. Multiply |ray|'s {{XRRay/origin}} by the |transform|'s {{XRRigidTransform/matrix}}.
    1. Multiply |ray|'s {{XRRay/direction}} by the |transform|'s {{XRRigidTransform/matrix}}.

**Comment by kearwood** [comment]
Do we expect XRRay values to hold intermediate values passed around in JS?  If so, would it be more appropriate to validate and fail when the XRRay is being used somewhere?  (I wouldn't be opposed to either solution)

Some issues arise due to the nature of floating point precision.  A primary reason to reject 0,0,0 directions is to prevent division by zero when normalizing such vectors.  Due to floating point precision issues, it may still be possible to incur a division by zero with vector components very close to 0.0.

Typically, this is resolved by pre-determining an "Epsilon Value" (eg, 0.0000001) which can be used to define how close to zero a number must be to trigger the validation / fallback.  Unfortunately, it may be difficult to find such a number that is ideal for everyone.

An alternative that avoids this problem:

If we are validating the direction vector in the constructor, perhaps we could also require the XRRay constructor to normalize the direction vector and fail if either a division-by-zero occurs or all components are within epsilon from zero.  This way, it's not possible to create an XRRay that would later cause a division by zero when passed into other functions.

The counter argument for this would be that the cost of this validation and/or normalization may not be needed for intermediate calculations.  Normalizing intermediate results of calculations can also lead to loss of precision vs normalizing and validating at the latest possible moment.
