### ISSUE TITLE
9.1 Input.XRInputSource.XRHandedness enum : replace empty string by none

### ISSUE THREAD

**Issue by HyroVitalyProtago** [immersive-web/webxr#515]
The XRHandedness enum have currently 3 values : "", "left" and "right".
I think that "" (the empty string) is not a proper way to describe something, that's why I propose to replace it with "none".

**Comment by toji** [comment]
That's a valid observation. This is a pattern that we picked up from the Gamepad API's `GamepadMappingType` enum, but the context here is different enough that we don't have a pressing reason to follow that convention. While I don't personally see a strong need to change it, if there was consensus in the working group that a non-empty-string symbol would be better I certainly wouldn't oppose it. (In light of recent work done by @NellWaliczek on the gampad mapping schemas, I would maybe suggest `"neutral"` as the replacement symbol?)

**Comment by HyroVitalyProtago** [comment]
For sure, there isn't a strong need to change it. And _neutral_  is also a possibility.

**Comment by dontcallmedom** [comment]
for reference, both [the empty string](https://dontcallmedom.github.io/webidlpedia/?enums=#x-) and [`none`](https://dontcallmedom.github.io/webidlpedia/?enums=#x-none) are regularly used in other Web APIs

**Comment by toji** [comment]
That is an amazing list! Thanks for the links!

**Comment by kahunamoore** [comment]
Something you might want to consider is people who are amputees (like my wife.) It would be great if we could have apps respond appropriately when a user only has one arm/hand (e.g. an enum for "single" or "only"?). Not sure if this is the right place to address it but I'd like to see accessibility built-in to the framework level where we only have to solve it once, or at least a single source of truth, for all apps.

Could someone point me in the direction of where a good place to "handle" these kinds of issues? Thx.

**Comment by toji** [comment]
Thanks for the comment!

I agree that accessibility is a huge consideration for APIs like this, especially when app design suddenly has to consider so much about the user's physical form and abilities. Height matters in XR. Number of hands and their locomotion matter in XR. Physical mobility matters in XR. If we want XR to be successful and inclusive we need to consider all of those things.

There's a couple of antagonistic factors when considering accessibility, though. Primarily privacy and application ignorance. Both of them affect how I approach the discussion of accessibility in XR (though neither of them prevent it, I think).

First off: Privacy. It's reasonable to think that your spouse probably doesn't want to advertise to random sites that she visits that she's an amputee. At best they don't need to know or care and at worst that becomes one more piece of identifying information for advertisers and trackers. (And if she does want to communicate that, it should be an intentional act by her rather than an opaque side effect.) So generally we don't want to include something in the API that clearly implies a users physical attributes unless it's absolutely necessary. Indicating "single controller" when the typical configuration for a device is dual controllers may do just that.

Instead, if we simply expose the controller for a single hand without commenting on the status of the other hand (the current behavior of the API) we leave the reasons why ambiguous but still allow the app to dynamically adjust to the active configuration. Do I only have one controller because that's all the device supports (like Oculus Go?) Do I have two controllers but one of them is out of battery/broken/lost?  Or am I physically unable to use both controllers? To the app these scenarios can all be handled well with no knowledge of why the second controller is missing. That said, it's still important to communicate the handedness of the controller even if only one is in use, because that can affect the visualization of the device in XR, which is important for usability (especially among new users.) Similar considerations apply to other aspects of XR: Is the user's headset closer to the floor than expected because the user is sitting? In a wheelchair? A child? A person of short stature? The app doesn't need to know, it should ideally just adjust dynamically to fit the data it's being given.

Of course the word "ideally" is doing a lot of work in that sentence, and anyone familiar with software at large can tell you that applications don't follow even the most trivial of best practices with *extreme frequency*. It's expected that even if we DID advertise an explicit "single handed" state it would likely be ignored by the vast majority of software outside of more malicious uses, and thus we would have given up a small bit of user privacy for effectively nothing in return.

Fortunately, the web ecosystem gives us some excellent routes for addressing this in a way that's effectively invisible to apps. The user agent (browser) can intervene and modify much of the data that's surfaced to the page to compensate for any number of limitations (or to simply enhance the user's interactions regardless of ability.) A very simple example would be to instruct the browser to opaquely add a vertical offset to the viewer's height values. This would give the user a possibly unpleasant feeling of floating, but also enable some users to reach virtual items that otherwise would have been placed to high for them, which is probably a worthwhile tradeoff. In the specific case of adapting to applications that expect two handed interactions, the user agent could include a capability that lets the active virtual hand be switched at the push of a button, allowing the user to control both of them in turn. The inactive hand state could also be frozen when you switch away, enabling some gestures like "pinch/zoom" that would otherwise be impossible with a single controller.

Such enhancements could exist at a couple of different levels. With many browsers they could be implemented in a very lightweight fashion as extensions, which would probably allow them to be more responsive than if the same features were implemented natively in the browser. Even so, having some features implemented by the browser itself could also make sense, especially if it needed to access data beyond what the base API provides. Finally, there are XR platforms that also provide some limited input re-mapping capabilities, such as OpenVR, that enable things like mapping a VR controller button to a keyboard key. While less expressive, that also provides a certain level of accessibility for some user's needs.

Of course, no amount of platform tricks can adequately compensate for more direct accessibility considerations by the application itself. We never want to absolve developers from the need to consider accessibility as part of their design, but we recognize that no amount of advocacy will result in perfect software. So the ideal solution is a combination of each of the approaches discussed above:

  1) Expose enough data, in a privacy sensitive way, that applications are enabled to be accommodating to differences in capabilities, whether those differences are intrinsic to the hardware or the user.
  2) Document and promote best practices for accessibility. In cases where it's reasonable try and bake those practices into common libraries and application frameworks.
  3) Offer platform-level accessibility tools to compensate for times when the application's built-in considerations are inadequate.

**Comment by kahunamoore** [comment]
Wow! This is a very well considered approach. I had not considered the privacy issue but I think a lot of us would trade *some* privacy for accessibility -- if it actually happens. But as you said, unless addressing the issue is forced most apps will just take the easy path and ignore it. My main point was trying to get accessibility addressed, or at least sufficient mechanisms provided to apps, as low in the stack (e.g. by default) as possible will have the greatest impact. Unfortunately it isn't as easy as it sounds.

I was going to suggest the ability to swap left/right controllers at a logical level would enable many otherwise inaccessible interactions when both controllers aren't interchangeable (left vs right behavior) or two controllers are required. With the OpenVR mappings I can already do this statically but being dynamic is much more helpful. I really like your idea of "freezing" a controller so that two handed zoom gestures can be achieved. Another example is things like Tilt Brush where UI elements are anchored to one controller and pointed at with the other (palettes, tools, etc.)

In some apps, my wife is able to use a Vive Tracker to play Beat Saber because the UI elements can be driven with one controller and the tracker can communicate positional data for the saber slicing. Down the road eye tracking and voice commands may alleviate some of these issues. As you said, at some point the app has to do some of the work to consider these use cases. Sounds like an opportunity for a niche market in Accessible XR apps. :-)

All of this gets even more complicated when hand tracking is in play. I am developing an app using the Leap Motion and even *I* didn't consider how my wife would use the app (granted, it's not an app she'd be interested in so... yeah, kettle, meet black.)

I didn't mean to hijack this issue with a general accessibility discussion but thanks for being so considerate in your design thinking. Let me know if there is some way I can help.
