### ISSUE TITLE
Clarify when XRPose.emulatedPosition should be true

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#534]
A question that came up while reviewing some incoming Chrome code: If a viewer device only offers 3DoF tracking, does that imply that every `XRPose` queried by the system must report `emulatedPosition = true`?

A hypothetical scenario: You have a 3DoF VR headset, which obviously reports `emulatedPosition = true` when getting head poses. I create a `floor-level` and `eye-level` stationary frame of reference, where the `floor-level` is obviously using a height estimate to offset the headset pose. So lots of emulation going on all around. However, if I query `xrFrame.getPose(eyeLevelRefSpace, floorLevelRefSpace)` the relationship between those two spaces is fixed and can be reported with perfect accuracy... so does `emulatedPosition` apply or not? (You can also apply similar logic to two of the same type of reference space with different `originOffset`s or the relationship between a `gripSpace` and `tartgetRaySpace` on a controller.)

My instinct is to say that we shouldn't flag as `emulatedPosition` if the relationship between the spaces in question is fixed or otherwise known to a high degree of accuracy. I wanted to sanity check that here first, though, before adding any clarifying text to the spec.

**Comment by NellWaliczek** [comment]
Paging @thetuvix!  Any update on getting your proposal from the F2F into a PR?

**Comment by thetuvix** [comment]
Apologies for the delay!  As you can imagine, last week was quite busy for us 😄

These are interesting corner cases for `emulatedPosition`, especially given that apps will likely end up using it most of the time to reason about tracking state:
* For a 3DoF device, the distance from `eye-level` to `floor-level` may be **fixed**, in that it won't change its value.  However, being fixed is separate from being **tracked** vs. emulated.  For example, a 6DoF controller that leaves the FOV and drops to 3DoF may lock in place relative to the user's head.  An app that relates the `eye-level` space and the controller's grip space might also get a quite fixed answer at that moment, but the emulated guess being fixed is precisely what the app wants to be warned about when they check whether the position is now `emulated`.
* Another interesting case is a 6DoF headset that can track the user's position changes accurately, but which has no calibrated or detected notion of floor.  In that case, the UA may again run with an assumed floor height.  In that case, we could credibly defend `emulatedPosition` as true for all relations to the `floor-level` space, since we don't have any actual data about the floor position.  However, then the app has lost its ability to know when the headset itself moves from 6DoF to 3DoF tracking, since `emulatedPosition` would always be true unless the app separately checks the pose in the `eye-level` space.
* Regarding the relation between grip space and target ray space for a given controller, that feels like a clear case of `emulatedPosition` being false.  In contrast to the emulated floor height, there is nothing unknown here - the fixed relation between those spaces is manufactured into the plastic, and so there's no ambiguity left.

Given the above, perhaps we just define `emulatedPosition` as relating to the current positional tracking state (and perhaps capabilities if maxing out at 3DoF) of the spaces in question:
* If the UA knows this space relation at a high accuracy, whether fixed or tracked, `emulatedPosition` is false.
* If the UA can only provide this space relation at approximate accuracy, or if true positional tracking is not possible for this relation, `emulatedPosition` is true.

We could then have a special callout in the spec for UAs making assumptions about things like floor height, and how that does not cause `emulatedPosition` to become true if positional tracking is otherwise available for the space being related to the floor.  That definition might perhaps be a motivation for moving to the term **`estimatedPosition`** here instead, separating that notion from any emulation the UA elects to provide for the floor.

**Comment by NellWaliczek** [comment]
Related to #243 and #559

**Comment by thetuvix** [comment]
My latest spec text updates in #559 in response to @Manishearth's comments now explicitly refer to whether `space`'s pose in `baseSpace` is "actively tracked or statically known" by the underlying tracking system.

This resolves my bullet 3 above to return `false` when relating a controller's grip space and target ray space, since their true relationship is "statically known".

It should also resolve bullet 1 to return `true` when relating `local` and `local-floor` during floor emulation, since an emulated floor position is not "actively tracked".  Although, I suppose that comes down to whether one considers the relationship between `local` space and `local-floor` space to be "statically known" even if it's made up...  Perhaps there is a better term there that means "statically known to be true" :smile:

A question then would be whether bullet 2 is an issue.  An app relating `viewer` and `local-floor` would always get `false` if there's an emulated floor, meaning the app might always believe it's in 3DoF mode, even when the only thing unknown is the floor.  Is that OK?

**Comment by toji** [comment]
Closed by #559

**Comment by thetuvix** [comment]
@toji: There were some remaining questions called out in this thread that I believe we were intending to discuss after merging the core #559 change.

Specifically:
> A question then would be whether bullet 2 is an issue. An app relating viewer and local-floor would always get false if there's an emulated floor, meaning the app might always believe it's in 3DoF mode, even when the only thing unknown is the floor. Is that OK?

@NellWaliczek/@toji: How do you feel about that state of affairs?

**Comment by NellWaliczek** [comment]
I'd much prefer that not be the case.  If we're suggesting people look at that flag to know if tracking has been recovered without an origin discontinuuity, then they will not be able to use that signal if it is always reported as emulated.
