### ISSUE TITLE
What do the values of the depth buffer represent?

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#555]
In today's meeting, a question was raised what the values in the depth buffer stood for.

For Magic Leap, 0 represents that the content is on the near plane and 1 that it is on the far plane.
We interpolate linearly between those values
so if near = 1m and far = 11m a value of .5 would represent 6 meter

**Comment by toji** [comment]
Thanks for opening this, Rik! Probably worth stating that (to my understanding) the depth buffer interpretation described above is the default behavior for OpenGL/DirectX/Vulkan/Metal.

**Comment by thetuvix** [comment]
That is the same interpretation we use for Windows Mixed Reality, across HoloLens and the desktop headsets.  We should specify that interpretation in the WebXR spec, so apps know how runtimes will use `depthNear`/`depthFar` to interpret their depth buffer pixel values back to meters.

A related question is what happens if the app had called [WebGLRenderingContext.depthRange](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/depthRange) and chose values other than 0 and 1.  In Windows Mixed Reality, we support reversed-Z by apps swapping our equivalent of `depthNear` and `depthFar`, but we don't support arbitrary depth ranges.  I'm unclear when apps benefit from choosing a depth range smaller than [0, 1] in practice.

To provide conformance across UAs and XR platforms for WebXR 1.0, we could specify two extra things as part of #548:
* Your WebGL context must use a depth range of [0, 1] if `ignoreDepthValues` is `false`.
* To use reversed-Z, specify a `depthNear` value that is greater than `depthFar` on `XRRenderState`.

@cabanier: Does Magic Leap support reversed-Z?

**Comment by cabanier** [comment]
@thetuvix I will ask internally.
Is there a reason to invert the Z? Is it more convenient?

**Comment by cabanier** [comment]
@thetuvix do you know what the use case of the revert is?

**Comment by cabanier** [comment]
answer here: https://developer.nvidia.com/content/depth-precision-visualized :-)

**Comment by toji** [comment]
That post does call out a caveat that's particularly relevant to our case, though:

> OpenGL by default assumes a [-1, 1] post-projection depth range. This doesn't make a difference for integer formats, but with floating-point, all the precision is stuck uselessly in the middle. (The value gets mapped into [0, 1] for storage in the depth buffer later, but that doesn't help, since the initial mapping to [-1, 1] has already destroyed all the precision in the far half of the range.) And by symmetry, the reversed-Z trick will not do anything here.
>
> Fortunately, in desktop OpenGL you can fix this with the widely-supported ARB_clip_control extension (now also core in OpenGL 4.5 as glClipControl). **Unfortunately, in GL ES you're out of luck.**

Maybe WebGPU will fix that particular quirk? In any case, I don't see any benefit in *preventing* apps from using reversed-Z simply by specifying a `depthNear` that's greater than `depthFar` as Alex mentioned.

**Comment by thetuvix** [comment]
Thanks for the detail @cabanier!

@cabanier: If you're comfortable with the new language @toji added to #548, I think we're all aligned here:
> Depth values stored in the buffer are expected to be between <code>0.0</code> and <code>1.0</code>, with <code>0.0</code> representing the distance of `depthNear` and <code>1.0</code> representing the distance of `depthFar`, with intermediate values interpolated linearly. This is the default behavior of WebGL. (See documentation for the <a href="https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glDepthRangef.xml">depthRange function</a> for additional details.))

If we also expect some WebXR content to start trying out reversed-Z, I wonder if we should also specify that UAs **must** allow `depthNear` to be greater than `depthFar`, to avoid some UAs failing to render some scenes.

**Comment by toji** [comment]
Closed by merging #548.
