### ISSUE TITLE
Clarify cacheability of XRViews

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#572]
The Chromium impl currently seems to [cache XRViews on the session](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/xr/xr_viewer_pose.cc?gsn=%22third_party/blink/renderer/modules/xr/xr_viewer_pose.h%22&g=0&l=19). (I'm not completely familiar with the Chromium code so ICBW here, cc @klausw)

This does mean that `getViewerPose()` called twice with different spaces will overwrite the views from the first space.

This is definitely convenient -- avoiding per-frame allocations is nice -- but we should clarify if this optimization is allowed in the spec, perhaps with language like "the viewer pose requested by `getViewerPose() is only valid until the next call to `getViewerPose()`". I don't forsee people calling `getViewerPose()` with different spaces in a single frame, so this seems to be an acceptable optimization to make, but I'd be more comfortable with an explicit go-ahead to do it.

Alternatively, if we plan to go forth with "values are only valid between `getViewerPose()` calls", a better way to have this API is to make it an attribute:

```js
session.viewerPoseSpace = someSpace;
for (view of session.viewerPose.views) {
  // render
}
```

(unsure if `viewerPoseSpace` can be merged with `viewerSpace` here)

**Comment by toji** [comment]
The line of code you linked in Chrome actually performs a copy of the underlying view objects. (Which is *super duper* obvious to casual readers because C++. 🙄) And it's the intent of the code that the views are not re-used.

We could make an argument for language like the suggested "values only valid between..." if we felt that the performance hit we'd get from creating new objects is problematic, but I would personally rather avoid it unless absolutely necessary. In WebVR we took some steps to explicitly re-use objects frame to frame and got pretty strong feedback from the TAG and elsewhere that doing so was pretty un-web-like, and that we should generally be less concerned about the overhead of object creation. I still like to keep it in mind when thinking through API design, but if it comes at the expense of API clarity then clarity usually wins.

One thing that we could do pretty safely is allow for repeated calls to `getPose` and `getViewerPose` on the same frame and using the same spaces to return the same object. That would be useful if we expect to have multiple libraries all making their own calls to retrieve poses, but I'm not sure if the effort it would take to cache the results would be worth it?

**Comment by toji** [comment]
> Wait, including deep-cloning the javascript view objects?

Forgive my lack of expertise in this regard, but what I think happens here is that the native object is deep-copied, but the copy does not actually receive a JS wrapper until it's thrown across the native/JS boundary, at which point the wrapper will be associated with the native object for the remainder of it's lifetime but is a wholly new JS interface. TL;DR: Deep copying the native object will yield a different Javascript object with the same native values but none of the values patched in by the script.

> I think having session.setViewerSpace() followed by session.views might be a bit more web-like since it's clearer that views is probably reused.

I don't know if the assertion that only a single viewer space will be used per frame is a safe bet? Certainly it'll hold true for the majority of content, but we've also identified scenarios where it may be easier for developers to render things like head-locked HUD with one reference space and the world with another.

**Comment by Manishearth** [comment]
> Deep copying the native object will yield a different Javascript object with the same native values but none of the values patched in by the script.

Ah, interesting. It's still somewhat surprising to me that Chromium has an implicit copy constructor for DOM things that deep clones, that operation seems pretty rare to me (but easy to misuse).

Either way, all that's pretty off topic for this issue tracker :)

> Certainly it'll hold true for the majority of content, but we've also identified scenarios where it may be easier for developers to render things like head-locked HUD with one reference space and the world with another.

Oh, duh. I forgot about this use case. Though I guess in that case you don't need to query the session for anything for the HUD and will use your own view matrix (likely an identity matrix)?

(And in the case of things attached to input spaces, you'd be using `getPose` not `getViewerPose`)

**Comment by toji** [comment]
Going to close this issue for now, since I don't think anything needs to change. If you'd like to talk further to clarify anything feel free to reach out.
