### ISSUE TITLE
Should origin offset be a new reference space instead?

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#580]
See: https://github.com/immersive-web/webxr/pull/569#issuecomment-475823936

> FWIW, I think originOffset makes it difficult to explain reference spaces things clearly. An XRReferenceSpace basically consists of two XRSpaces that are transformed into each other by the originOffset, and it's hard to explain how that transform works when the two spaces don't have names. I've used the name "effective reference space" for the offset-modified externally visible space and "unmodified reference space" for the internal space corresponding to an identity originOffset, but that's clunky.

In today's call we discussed this a bit, an alternate model suggested by @klausw was to have might be to instead have a constructor for origin offsets, probably something like:

```webidl
[SecureContext, Exposed=Window,
 Constructor(XRReferenceSpace base, XRRigidTransform offset)]
interface XROffsetReferenceSpace : XRReferenceSpace {
  attribute XRRigidTransform offset;
  readonly attribute XRReferenceSpace base;
}
```

where if you want to apply an origin offset, you effectively construct a _new_ space wrapping over the space you have, and use it where you need the offset. This avoids having to maintain the clunky distinction in the spec, especially for things like input spaces.

**Comment by klausw** [comment]
I like it, and I think this solves the documentation issue since there's now a named "base" space to use in explanations.

This still leaves open the direction of "offset". The current originOffset is a transform from offset space to base space, and I think that seems a bit backwards in this proposed API. If we're making a breaking change anyway, should it be redefined to be a transform from base space to offset space instead? The arguments in issue #477 around the transform direction weren't strong either way, and the math needed to get teleport working correctly is moderately complex no matter which way around it's defined.

Is the `offset` attribute writable after construction? I think that would be useful, but it should be explicitly called out that this is supported and maintains the correct relation between the spaces after updates.

**Comment by Manishearth** [comment]
> should it be redefined to be a transform from base space to offset space instead

This was what I _assumed_ `originOffset` did when I first encountered it, so to me it reads as more natural, but I don't have a very strong preference here as long as we properly document this. As you said the arguments are not strong either way.

(We could also have an `optional preTransform = false` argument, or something, exposing both behaviors, though I'm not sure we need that.)

> Is the offset attribute writable after construction?

When I first typed this up I had marked it readonly, but I realized that this might be useful so I removed it. I have no strong opinion on this, but we should pick something 😄

**Comment by NellWaliczek** [comment]
I'm strongly inclined to readonly, otherwise we're right back to where we are today.  Should be low cost to create a new reference space like this too.

**Comment by klausw** [comment]
I think a "preTransform" boolean arg would itself be a bit confusing. If we do want to support both interpretations, we could expose a pair of mutually inverse writable attributes, where the user can set whichever one they prefer, and the other one is lazily set to its inverse. In that case, the constructor likely shouldn't take an offset argument and be initialized with an identity transform. Something like this?

```webidl
[SecureContext, Exposed=Window,
 Constructor(XRReferenceSpace base)]
interface XROffsetReferenceSpace : XRReferenceSpace {
  attribute XRRigidTransform offsetFromBase;
  attribute XRRigidTransform baseFromOffset;
  readonly attribute XRReferenceSpace base;
}
```

I went with "B from A" naming instead of "A to B" so that matrix math using this would look more natural:

```
let ref = new XROffsetReferenceSpace(baseSpace);
ref.baseFromOffset = legacyOriginOffsetTransform;
let pointInRefSpace = multiply(ref.offsetFromBase.matrix, pointInBaseSpace);
```

Seems a bit like overkill though since each of these transforms already has an inverse attribute. The single-attribute version looks simpler, and I think it may make sense to use the more descriptive attribute name to avoid confusion:

```webidl
[SecureContext, Exposed=Window,
 Constructor(XRReferenceSpace base, XRRigidTransform offsetFromBase)]
interface XROffsetReferenceSpace : XRReferenceSpace {
  attribute XRRigidTransform offsetFromBase;
  readonly attribute XRReferenceSpace base;
}
```

```
let ref = new XROffsetReferenceSpace(baseSpace, legacyOriginOffsetTransform.inverse);
let pointInRefSpace = multiply(ref.offsetFromBase.matrix, pointInBaseSpace);
```

**Comment by Manishearth** [comment]
Yeah, that does seem like overkill.

**Comment by klausw** [comment]
> I'm strongly inclined to readonly, otherwise we're right back to where we are today. Should be low cost to create a new reference space like this too.

@NellWaliczek - I think a writable attribute would be fine. The fundamental problem with the current situation is that originOffset was a transform between two unnamed spaces, so it was hard to explain. In this new API, we're creating an offset space from a base space, so both the source and destination of the transform exist independently and have names.

The spec text could be something like this: 

Old as proposed in #569 :
> The <dfn attribute for="XRReferenceSpace">originOffset</dfn> attribute is a settable {{XRRigidTransform}} that affects all poses queried using that {{XRReferenceSpace}}. It is a transform from the effective {{XRReferenceSpace}} to the underlying unmodified {{XRReferenceSpace}}, and is initially set to an [=identity transform=]. Changes to the {{originOffset}} take effect immediately, and subsequent poses queried with the {{XRReferenceSpace}} will use the effective reference space that takes into account the new transform, applying the inverse of the {{originOffset}} to the pose that would have been returned from the same reference space with an identity {{originOffset}}.

New (in proposed XROffsetReferenceSpace explanation):
> The <dfn attribute for="XROffsetReferenceSpace">offsetFromBase</dfn> attribute is a settable {{XRRigidTransform}} that is applied to all poses queried using that {{XROffsetReferenceSpace}}. It is a transform from the base {{XRReferenceSpace}} to the offset space. Changes to {{offsetFromBase}} take effect immediately, and subsequent poses queried with the {{XROffsetReferenceSpace}} are equivalent to queries in the base reference space with the current {{offsetFromBase}} transform applied to them.

**Comment by toji** [comment]
I agree with Nell that the offset does need to be readonly here for this to be a benefit. There's a small caveat on that which is that one of the intended uses of these offsets was to assist in click/drag navigation for identity reference space, which means you'd be creating new reference spaces at a rate of about one per frame. I don't think that should be a problem, it just means that multiprocess implementations like Chrome need to avoid doing IPC round trips with each instantiation.

That's a reasonable temptation since APIs like OpenXR expose, essentially, [this exact model](https://www.khronos.org/registry/OpenXR/specs/0.90/man/html/#_xrreferencespacecreateinfo_3). In OpenXR parlance `XrPosef` is equivalent to our `XRRigidTransform`, and thus `poseInReferenceSpace` is effectively the same as our origin offset.

**Comment by toji** [comment]
> @klausw: I think a writable attribute would be fine. The fundamental problem with the current situation is that originOffset was a transform between two unnamed spaces, so it was hard to explain.

I'd actually argue that wasn't the primary issue with a writable offset. We've encountered a couple of instances where changing the origin offset could lead to ambiguous results or more on-the-fly work than was desirable. For example, I have a half-written issue asking whether or not changing the originOffset should fire `reset` events, since it *does* represent a change in the origin. Also, it necessitates changing bounds geometry on the fly and makes hit test subscription more painful. I'd be fine with a model that only allowed offsets to be applied in the constructor.

One wrinkle it brings to mind, though: Would we allow a new `XRReferenceSpace` to be created from an `XRBoundedReferenceSpace`? (Assuming the simplification in #574 lands.) I guess I don't see why not, just feels a little odd to me. I presume we'd only allow offset `XRBoundedReferenceSpace`s to be constructed from other `XRBoundedReferenceSpace`s.

**Comment by klausw** [comment]
@toji, I'm fine with a read-only offset, especially if this simplifies other areas of the spec and implementations. 

I think we should explicitly include the transform direction in the name of the constructor arg and pick an appropriate attribute name to ensure it's unambiguous. Just "offset" is open to misinterpretation. 

> In OpenXR parlance `XrPosef` is equivalent to our `XRRigidTransform`, and thus `poseInReferenceSpace` is effectively the same as our origin offset.

We need to be careful here about directions. Can you please sanity check my interpretation here? `poseInReferenceSpace` is defined by OpenXR as _"the position and orientation of the new space’s origin within the natural reference frame of the reference space"_, so the `XRPose` equivalent would have a transform whose `position` component is the new space origin's coordinates in the reference space. That means its `XRRigidTransform` transforms from the new space to the base reference space. (Specifically, the origin of the new space with its all-zero coordinates is transformed to `poseInReferenceSpace.transform`'s `position` coordinates.) This matches the current interpretation of `originOffset` as agreed on in #477 and as I've attempted to clarify in #569, and we should *not* reverse the interpretation as proposed in my earlier comment https://github.com/immersive-web/webxr/issues/580#issuecomment-479111791 here.

How about this version?

```webidl
[SecureContext, Exposed=Window,
 Constructor(XRReferenceSpace base, XRRigidTransform transformIntoBaseSpace)]
interface XROffsetReferenceSpace : XRReferenceSpace {
  readonly attribute XRRigidTransform transform;
  readonly attribute XRReferenceSpace base;
}
```

Extended musings about the naming following, please feel free to skip this if you are OK with the above, but I do think we need to find something and stick with it to stabilize things.

I'd suggest the arg name `transformIntoBaseSpace`. It's intended to follow OpenXR's 'poseInReferenceSpace' example, with some tweaks. We shouldn't use 'ReferenceSpace' since it's ambiguous - both the arg and constructed object are reference spaces. `poseInBaseSpace` would be confusing since the arg is a transform, not a pose, and `transformInBaseSpace` looks strange. Hence `transformIntoBaseSpace' which seems to most clearly match how that transform works.

I'm not sure about the best name for the attribute. I'd prefer to avoid 'offset' variants due to their ambiguity. We could just go with `transformIntoBaseSpace` to keep it unambiguous, but I think we could go with `transform` since it acts just like an XRPose's transform, the offset space basically duck-types as an XRPose corresponding to the offset space's origin pose.

I'm starting to think that a core part of the confusion is that a tracked object's _XRPose_ has-a _XRRigidTransform_, and the transform's position component corresponds to the tracked object's coordinates in reference space as expected, but a _XRRigidTransform_ and its matrix are a transform from object space to reference space. That's internally consistent, but it's confusing when you supply a transform by itself as an argument (as in the constructor arg here) because it's easily interpreted as saying "please apply this transform" which would be backwards. In a way, OpenXR's approach of directly putting position + orientation on the pose objects helps avoid this ambiguity.

```js
  // This one pretty clearly means "place the offset space origin at this pose"
  let space = new XROffsetReferenceSpace(base, pose);

  // This one is equivalent...
  let space = new XROffsetReferenceSpace(base, pose.transform);

  // ... but this variant is easily misread as "please apply this transform to the base" 
  let space = new XROffsetReferenceSpace(base, transform);

  // This one pretty clearly seems to mean "please apply this offset to the base"
  let space = new XROffsetReferenceSpace(base, offset);
```

**Comment by DrX3D** [comment]
Perhaps this is clear to others, but it is not clear to me; though the last comment by @klausw may be shedding some light on it. Throughout most of the comments there is reference to an offset Transform. To me that implies a translation - no rotation, scaling, skewing, etc. Is that what is intended? If not, why not include rotation or scaling (see the novel and movie Fantastic Voyage where scaling could be important).

Also just to ask a really far out possibility, is time being considered at all in other reference spaces?

**Comment by klausw** [comment]
@DrX3D, `XRRigidTransform` consists of a rotation and translation, but does not support scaling. Scaling remains up to the application.

There isn't any specific time-related transform logic, but poses (represented by rigid transforms) are snapshots corresponding to the time of an `XRFrame`, so it's entirely possible to represent time-varying transforms that change during a sequence of animation frames. (I'm not sure if we currently have a good way of representing AR on a moving vehicle, where we'd want to separately track a world-stable reference and vehicle-relative reference, but we've got the general concepts in the spec in case we do want to support this at some point.)
