### ISSUE TITLE
Describe in detail the way used to obtain XRRay.matrix

### ISSUE THREAD

**Issue by bialpio** [immersive-web/webxr#582]
The way it's currently specified, the matrix that's supposed to be returned from XRRay.matrix is not unique - there are infinitely many ways of transforming one ray into another as the roll is not constrained in this problem. The specification should describe exactly how the XRRay.matrix should be calculated to prevent interoperability issues between different implementations.

**Comment by NellWaliczek** [comment]
@thetuvix IIRC, you shared a similar concern?  Would you mind elaborating on the explanation you gave me the other day?

**Comment by thetuvix** [comment]
My concern (https://github.com/immersive-web/webxr/pull/569#discussion_r277617621) has been more general, as to whether the WebXR `matrix` attributes are likely to create more convenience or confusion for applications.

Even among those of us who live and breathe the WebXR spec every day, I've seen us struggle on a regular basis to recall whether `matrix` attributes should be a **"transform from"** or a **"transform to"** among the two spaces in question.  This just came up again today in https://github.com/immersive-web/webxr/pull/649#issuecomment-492772969.  Meanwhile, I haven't seen such ambiguity around the `position`/`orientation` attributes on `XRRigidTransform` (in either WebXR or OpenXR) or the `origin`/`direction` attributes on `XRRay` - those are all just interpreted as **"coordinates in"** the base space.  Given this, I expect that any `matrix` convention that we choose and rigorously specify will create confusion as compared to `position`/`orientation` or `origin`/`direction`, unless we are following a strong existing convention used elsewhere on the web.

That said, it could still be worth introducing and strictly defining some convention for these `matrix` attributes if that then enabled apps to directly operate on the `Float32Array` more efficiently than creating a matrix from the `position` vector and `orientation` quaternion.  However, if we do define some WebXR matrix convention here, the representation we choose must then exactly match the internal matrix representation used by the app's 3D math library (left-handed vs. right-handed? column-major vs. row-major? Y-up vs. Z-up?) - otherwise, the app will need to transform the matrix data WebXR gives them anyway.

@toji mentioned in https://github.com/immersive-web/webxr/pull/609#discussion_r279578804 that WebGL does not specify any particular matrix representation.  However, the [following claim in the spec](https://github.com/immersive-web/webxr/blob/a3dd6831f383e8a8d1f6f070b31de0bca6ecc0e5/index.bs#L970) does assert that the format WebXR uses has significant alignment with WebGL, `DOMMatrix` and third-party math libraries:

> WebXR provides various transforms in the form of _matrices_. WebXR uses the WebGL conventions when communicating matrices, in which 4x4 matrices are given as 16 element `Float32Array`s with column major storage, and are applied to column vectors by premultiplying the matrix from the left. They may be passed directly to WebGL's `uniformMatrix4fv` function, used to create an equivalent `DOMMatrix`, or used with a variety of third party math libraries.

If apps end up needing to transform the `matrix` we provide to ingest it into their math library's matrix type anyway, they could just as well have ingested `position`/`orientation` or `origin`/`direction`, avoiding all of this ambiguity.  The key question to make `matrix` worth it is whether we expect WebXR's matrix representation to be canonical on the web so that many apps can directly ingest it.

@toji, @Manishearth, @klausw: Is WebXR's use of matrix canonical with how we expect matrices to be stored across the web?  Was the design of `DOMMatrix` intended to align with de facto conventions used in WebGL engines today?  If so, then maybe we're all good here, although should we then just return `DOMMatrix` here rather than `Float32Array`?  Or is that somehow less convenient/efficient to compose with WebGL/three.js/etc.?

**Comment by Manishearth** [comment]
Should I file a dedicated issue to consolidate all these discussions? I've been planning to fix the language with a PR anyway, just haven't had a chance yet.

**Comment by klausw** [comment]
@thetuvix , we had fairly extended discussions in this while reworking the spec. Technically, since WebGL is based on programmable shaders, applications are in theory free to use whatever math conventions they want, but there's a fairly strong pressure to follow the usual conventions of left-multiplying matrices onto column vectors, and storing matrices in column-major order when flattening them to one-dimensional arrays. Some WebGL API methods are opinionated, for example GLES [glUniformMatrix4fv](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glUniform.xml) requires column-major storage.

WebXR is already opinionated about some conventions, for example [XRReferenceSpace](https://immersive-web.github.io/webxr/#xrreferencespace-interface) _describes a coordinate system where +X is considered "Right", +Y is considered "Up", and -Z is considered "Forward"_. This locks in a right-handed coordinate system.

I don't know about the background of choosing a Float32Array instead of DOMMatrix, but it is compatible. DOMMatrix has `.ToFloat{32,64}Array()` methods and a sequence constructor that accepts a float array as input, and both of these use column-major storage. The `.translate()` method sets the fourth column which corresponds to a matrix that is intended to be left-multiplied onto a column vector.

Overall, I think it seems OK to use these usual conventions in the WebXR API, and to the best of my knowledge this is compatible with existing usage in libraries. Unless there's a specific counterexample, can we stick with this current approach and focus on clearly documenting it?

**Comment by Manishearth** [comment]
> Unless there's a specific counterexample, can we stick with this current approach and focus on clearly documenting it?

:+1:

**Comment by thetuvix** [comment]
Sounds good!  In that case, WebXR is indeed embracing what has emerged as canonical on the web due to the gravitational pull of WebGL.

That's more than we could say with OpenXR where we had to support not just left-handed and right-handed engines, but also Y-up and Z-up engines, as well as meter-unit and centimeter-unit engines! 
 While OpenXR is similarly opinionated about handedness and axes, basically all engines needed to then transform the matrices we'd been giving out, and so the value of providing those matrices directly ended up fairly low.

It sounds like on the web, most engines are Y-up and don't have a tradition of centimeters as their primary unit, and so the chance that the matrix can be directly used is far higher :smile:

**Comment by thetuvix** [comment]
Regarding `DOMMatrix`, using that well-defined type could make it more clear moving forward that we're following these standard matrix conventions.

Is it more expensive for WebXR to return `DOMMatrix` objects that wrap the `Float32Array` they'll then return through `ToFloat32Array`?
