### ISSUE TITLE
What happens if a canvas with an xrCompatible context is attached to the DOM?

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#603]
One of the examples in https://immersive-web.github.io/webxr/#contextcompatibility is:
```js
  let glCanvas = document.createElement("canvas");
  let gl = glCanvas.getContext("webgl", { xrCompatible: true });

  loadWebGLResources();

  xrSession.updateRenderState({ baseLayer: new XRWebGLLayer(xrSession, gl) });
```
On a device with a different GPU for 2D vs immersive content, this results in a canvas whose GL context is rendering to the GPU for immersive content. Now, what should happen if this canvas is attached to the DOM, which expects GL content to be using the other GPU?

**Comment by Manishearth** [comment]
I believe this is just implementation defined? `makeXRCompatible()` is supposed to set up the context for use on the new GPU, at which point the canvas won't be able to render to the DOM anymore. Should we just explicitly note that `makeXRCompatible()` may invalidate a canvas's ability to render in 2D?

**Comment by asajeffrey** [comment]
Is the expectation that if an xrComatible canvas is attached to the DOM then it will render and mirror the VR display? (The implementation will have to use a slow path for the mirroring, e.g. by copying image data via main memory.)

**Comment by toji** [comment]
The expectation is that an xrComatible canvas attached to the DOM will continue to function as a normal WebGL canvas, displaying the content of it's default backbuffer as usual. The content written to the XRWebGLLayer's framebuffer has no implicit mirroring mechanism at this point (it did previously, but we removed it due to developer confusion and spec bloat.) Instead if mirroring is desired most XR platforms have a native mechanism for doing so that accounts for scenarios that an in-page mirror could not, (such as casting from a mobile/standalone device). We may add a mirroring mechanism back in the future, but it would be seen as an advanced technique.

Because the layer framebuffer is distinct from the canvas default backbuffer it does allow for some interesting "spectator" effects if the developer wants to implement it. You can see a sample of this in action on this [WebXR sample page](https://immersive-web.github.io/webxr-samples/spectator-mode.html) (which works on desktop Chrome, and is naturally inaccessible on Android.)

In terms of how the UA should enable the canvas compositing once it's been made xrCompatible, that's up to the UA. In some cases (mobile/standalone) we can effectively guarantee that there's no secondary GPU and so xrCompatible is effectively a no-op. On Chrome's windows implementation we currently messily side-step the issue by replying on the fact that our mechanism for communicating D3D11 textures between processes will silently move them to the right GPU. (Yes, this introduces latency. It's a know issue but not our highest priority right now.) If you wanted to do the "right" thing you may have to move the entire browser's over to the XR compatible adapter, or do what Chrome does in reverse: Have just the GL context on the right adapter and accept a latency hit for the in-page canvas output. None of these scenarios seem particularly ideal, but that's simply the reality of working with multiple GPUs. (It's also why we have an explicit "xrCompatible" flag, because the side effects are potentially disruptive enough that we don't want to make the UA guess where the context should reside.)

**Comment by asajeffrey** [comment]
Yeah, I think what we'd have to do is build a new xrCompatible WebGL context using the XR GPU, then use the slow path to render the canvas.

For extra fun, once the XR API supports more than one simultaneous immersive session (multiplayer games anyone?) they'll be able to share a WebGL context (if they use the same canvas to get their GL context from) and then one of the XR devices will be on the slow path. Oh well, that's not a problem right now.

**Comment by kearwood** [comment]
We should be certain to review this with the WebGL group before closing this issue.

**Comment by Manishearth** [comment]
@asajeffrey are there any spec changes that need to be made here to support this? It seems like the additional framebuffer we have already solves this problem -- do we need to add a note somewhere?

**Comment by asajeffrey** [comment]
I'm not sure how to address this without making breaking changes to the existing API. The fundamental problem is using `canvas` elements for the source of XR-compatible GL contexts. and assuming that XR-compatible contexts can render to the browser's canvas.

As an extreme example of this, imagine the XR device is an external headset, using TCP to send WebGL commands. All fine and well, but getting texture data back off the device requires running readPixels and shipping the data back over TCP. At the moment such devices are imaginary (I think) but it's a pity that the WebXR spec is not set up for them.

The spec change would be that when a canvas creates an XR-compatible WebGL context, it creates a new one, but the existing non-XR-compatible context is still used for rendering to the canvas. This is a breaking change though.

**Comment by Manishearth** [comment]
> The spec change would be that when a canvas creates an XR-compatible WebGL context, it creates a new one, but the existing non-XR-compatible context is still used for rendering to the canvas. This is a breaking change though.

Worth noting: currently no browser actually implements makeXRCompatible as doing anything (There's a CL to add this to chrome, though). Would this make this breaking change possible?

**Comment by Manishearth** [comment]
So we discussed this a bit, and it's pretty clear that there are basically three options here:

 - UAs are given the option to make some XRCompatible contexts not work with canvases. This is breaking and would break a lot of content that's doing the "use 2d canvas when not in immersive mode" thing, like threejs' examples page and Hubs. 
 - UAs make two contexts. This is also breaking for the same reason
 - "Tough luck", i.e., browsers just have to support this.

An interesting thing @toji mentioned is that Chrome doesn't have this problem because whenever any page switches to a different GPU (via powerPreference or makeXRCompatible), the _whole browser_ switches over. This does make it even _harder_ to support such use cases but I guess Chrome is making the choice to not do so.

It seems like when powerPreference is used Servo will switch things for just the one context. I suspect Firefox is doing something similar.

I'm inclined to pick the "tough luck" option here and close this issue since I don't really see a viable route forward otherwise that does not break a lot of content.

Thoughts @asajeffrey ?

**Comment by asajeffrey** [comment]
Yeah, I think we have to go for "tough luck", in the absence of a time machine. 

The "move the whole browser" works for scenarios where the two GPUs share a CPU, but not for examples like the imaginary thin client in https://github.com/immersive-web/webxr/issues/603#issuecomment-616921006.

**Comment by Manishearth** [comment]
Closing as "tough luck".
