### ISSUE TITLE
We shouldn't default XREyes to left when they're unknown

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#620]
https://github.com/immersive-web/webxr/pull/614#discussion_r279926539

> We probably don't want CAVE systems reporting "left" for all n views

Reporting single-screen devices as "left" doesn't make much sense but sort of works. This falls apart more for multi-screen devices (especially where they have more than two screens) where every screen would be reported as "left", which might be misleading.

It's worth adding an Unknown/Other variant, or even making the eye an interface that lets us number them.

**Comment by toji** [comment]
We could add a new enum such as "unknown", sure. (OpenXR uses the term "both", which seems reasonable as well.) The thought process behind the current spec text is that the eye visibility should only really matter when displaying pre-rendered stereo content. In that scenario, the content will need to choose either the left or right eye's content to display, which is why it felt appropriate to simply choose one of the eyes to report in cases when neither was applicable.

The primary consequence of adding a third eye state would simply be moving that decision from the API to the developers code, which almost certainly would look like this:

```js
if(eye == 'right') {
  renderRightEyeContent();
} else {
  renderLeftEyeContent();
}
```

Which, really, is no different than the code in the two-enum case. So I'd mostly be interested in understanding what new uses cases reporting a third value would enable.

**Comment by toji** [comment]
Editors talked it over and decided we probably *do* want to introduce a third enum here. Major deciding factor is that even if we can't identify a specific use case for it now, if we do find one in the future it would be a reasonably significant breaking change to introduce a third state after shipping core.

As far as the verbiage goes, we think it would be best to simply mimic `XRHandedness` here, making the three enums `left`, `right`, and `none`.

**Comment by NellWaliczek** [comment]
@Manishearth Do you want to pick this one up?

**Comment by Manishearth** [comment]
Sure.
