### ISSUE TITLE
Does the "position-disabled" reference space still make physical sense?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#625]
Now that we're settling in on clean physically-based reference space definitions (which is great, especially for ensuring the associativity of space relationships!), I wonder if "position-disabled" reference spaces will operate as we intend for their 360-degree video scenarios when on stereo headsets.

Under this definition, `getViewerPose` would still return non-identity eye positions for each `XRView` relative to this reference space, since the eyes are indeed in physically different places.  That would cause the app to render each eye from some pose other than (0, 0, 0), leading to weird parallax artifacts relative to its finite-sized video sphere, which is the primary problem that "position-disabled" was trying to avoid.  I'd really hate to see us backpedal on the physically-based definitions and introduce some special case to `getViewerPose` for "position-disabled" spaces to magically zero out the `XRView` poses, since we should otherwise be fully clean on reference spaces behaving identically, just with differently-behaving origins.

Alternatively, **what if we just replaced the "position-disabled" reference space with a `disablePosition` option on `getViewerPose`**?  360-video apps could then just use the "eye-level" reference space like other seated experiences, with their one difference being a parameter they pass to one function whose behavior they actually wish to impact.  By adding the option to the affected method, all other use of reference spaces stays clean and easy to understand.

The simplest option here would just be to require that 360-video apps use a big enough video sphere (e.g. 1000m) that these parallax issues from neck modeling and stereo separation in "eye-level" spaces would fall away.  If we do that, **we could just cut the "position-disabled" space entirely**.  Perhaps in the interest of getting quickly to WebXR 1.0, that's the best answer?

_Originally posted by @thetuvix in https://github.com/immersive-web/webxr/pull/621/review_comment/create_

**Comment by Manishearth** [comment]
Coupled with #623 we can get rid of both of the spaces which have names that only make sense in the context of `getViewerSpace()` (`position-disabled` when related to other spaces is, confusingly, a space where orientation is constant and position moves around).

This nomenclature is what caused part of my confusion in https://github.com/immersive-web/webxr/issues/565 , since I interpreted identity and position-disabled as meaning two different things at once.

I'm not strongly in favor of this change, but I do think it simplifies _some_ things and avoids some potential confusions.

**Comment by blairmacintyre** [comment]
I like this.  

In general, I'd like to see us stop thinking about 360 viewers as orientation-only for a couple reasons:
- surprisingly (to me), 3DOF VR displays (e.g., GO, GearVR, Daydream) make me woozy, and I really notice this on 360 video when I move.  Having the video far away, with near-field objects that move as expected, is a much better experience for me (and thus, I assume, others).
- at the IEEE VR conference this year, there were a number of papers by people on extracting enough structure information from 360 video to support at least small head motion parallax.  

For both of these reasons, it's not inconceivable that we will someday have 360 video apps that want to support small motions, and nobody uses position-disabled.

**Comment by toji** [comment]
Thanks for making the case for this! Given the intent of `position-disabled` as a primarily enabling 360 media, I agree that the view offsets are problematic. It's also pretty trivial to strip positional data out of an `XRRigidTransform`, so it wouldn't be a huge hurdle to developers if we deferred or removed this functionality. A well-made sample showing how to properly display 360 media with, say, an `eye-level` reference space would go a long way.

If we do decide to take it out of the core spec I'd be in favor of simply removing the reference space type rather than adding an option to `getViewerPose()`.

**Comment by toji** [comment]
Put up a pull request that covers this and #624 to better facilitate discussion. (Assuming that it will need rebasing on top of #621, but that shouldn't change it's substance much.)
