### ISSUE TITLE
Do "eye-level" and "floor-level" fit with "bounded" and "unbounded"?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#633]
When seeing the simpler list of 5 reference spaces proposed in #626, it jumped out at me that `eye-level` and `floor-level` don't really fit as names in the same list with `bounded` and `unbounded`:

> There are several types of reference spaces: `viewer`, `eye-level`, `floor-level`, `bounded`, and `unbounded`.

For example, the `bounded` reference space is also a "floor level" space and the `unbounded` reference space is also an "eye level" space.  As a room-scale developer approaching this API fresh, how do I know if the reference space I want is `floor-level` or `bounded`, when what I really want is both?

It may make more sense in our recently-flattened reference space list to keep the term "stationary", so that it's clear how those two spaces differ from the other spaces.

_A strawman space list that keeps "stationary" and "floor" orthogonal, with "eye" as the implicit default:_
* `viewer`
* `stationary`
* `stationary-floor`
* `bounded-floor`
* `unbounded`

Independently, I'd shared the [spatial tracking explainer](https://github.com/immersive-web/webxr/blob/master/spatial-tracking-explainer.md) with @mattdatwork from Unity who expressed that the term "local" from OpenXR made more sense to him alongside "bounded" and "unbounded" than the term "stationary".

_If we went the "local" route, we'd end up with this strawman instead:_
* `viewer`
* `local`
* `local-floor`
* `bounded-floor`
* `unbounded`

Thoughts?

**Comment by thetuvix** [comment]
Pinging @NellWaliczek, @toji, @Manishearth, @klausw and @blairmacintyre to take a look here.

**Comment by thetuvix** [comment]
One potential advantage of the `local`/`local-floor` naming here would be if we had the spec specifically suggest that the local reference spaces follow platform conventions for experiences that should operate nearby the user.

For example, the spec currently states the following:

>   - Passing a type of <dfn enum-value for="XRReferenceSpaceType">eye-level</dfn> creates an {{XRReferenceSpace}} instance. It represents a tracking space with a [=native origin=] near the user's head at the time of creation. The exact position and orientation will be initialized based on the conventions of the underlying platform. ~~When using this reference space the user is not expected to move beyond their initial position much, if at all, and tracking is optimized for that purpose.~~ For devices with [=6DoF=] tracking, {{eye-level}} reference spaces should emphasize keeping the origin stable relative to the user's environment.

We could say the following instead:

>   - Passing a type of <dfn enum-value for="XRReferenceSpaceType">eye-level</dfn> creates an {{XRReferenceSpace}} instance. It represents a tracking space with a [=native origin=] near the user's head at the time of creation. The exact position and orientation will be initialized based on the conventions of the underlying platform **for local experiences that don't require the user to walk around**. For devices with [=6DoF=] tracking, {{eye-level}} reference spaces should emphasize keeping the origin stable relative to the user's environment.


That would create a stronger app-developer distinction about why they'd pick one vs. the other:
* Your app uses `local` or `local-floor` when your user will want to stay put, operating this **seated or standing experience** basically where they are (i.e. where they operate other seated/standing experiences on this device).  Some devices may have a user-recentered zero position to offer up here - other devices may just pick the user's starting head/foot position.
* Your app uses `bounded` when the user will want to walk to the center of the open space they pre-defined to use for **room-scale experiences**.  Devices that don't support pre-defining or auto-detecting such open XZ rectangles on the floor would fail to create a `bounded` reference space.

This is also explored in https://github.com/immersive-web/webxr/issues/579#issuecomment-490699670.

**Comment by toji** [comment]
I'm going to politely pretend I don't see Alex's not-so-secret plan to unite the verbiage of OpenXR and WebXR, and focus just on the merits of the names themselves. 😉 (It's not even necessarily a bad idea to try and use common language across the ecosystem, but we should at least make a good show of independently evaluating these things.) Also, I'd really *really* **really** like names to start settling down soon, but since we ARE contemplating the identity->viewer change I guess there's no better time for this discussion.

I'd be fine with either `stationary` or `local`, with `local` having two minor positives going for it: It's shorter and it seems to imply a bit more mobility, whereas I can see `stationary` being accidentally read to mean "3DoF" to a new developer. Like I said, though, those are minor nits and I don't think the API would be negatively impacted by choosing either term.

(Oh, and while we're talking terms I still have a small soft spot in my heart for `stage`, but I also think `bounded` is pretty descriptive and pairs nicely with `unbounded`, so I'm not gonna push it.)

I do like the reframing of `-floor` as a suffix, as it makes the pattern of what space aligns to what really clear. The biggest downside I can see is that it invites questions such as "If I have `bounded-floor`, why doesn't `bounded` work?" but... oh well? (And I guess that we COULD introduce a non-floor-aligned `bounded` later on if we found it to be in demand, but I don't really see that happening.)

I'm slightly concerned about leaving the origin of `*-level/stationary/local` spaces up to the UA/backend, because it's harder to build predictable experiences that way and we're bumping into some questions about how to implement it in a consistent manner in Chrome, but I also understand the desire to defer to the platform conventions and not do something that only applies to the web. So I'm conflicted. If nothing else I think we do need to make a consistent determination about whether or not creating a new stationary reference space is allowed to function as a software-driven recenter or if the origin for all stationary reference spaces is determined at session creation time (or similar). I'd hate to see developers implement an in-app recenter mechanism only to discover that it doesn't work on Oculus devices because they have an externally calibrated seated origin.

**Comment by thetuvix** [comment]
> I'm going to politely pretend I don't see Alex's not-so-secret plan to unite the verbiage of OpenXR and WebXR, and focus just on the merits of the names themselves. 😉

While we're not talking about it 😉, you may notice I didn't push us to go back to `stage` again.  For what it's worth, the feedback I heard from @mattdatwork of Unity (across WebXR and OpenXR) was that "local", "bounded", "unbounded" was the triple that made the most sense to him as a consumer of these APIs, so you could see WebXR as ending up with a naming scheme even more evolved than OpenXR here 😄

> I do like the reframing of -floor as a suffix, as it makes the pattern of what space aligns to what really clear. The biggest downside I can see is that it invites questions such as "If I have bounded-floor, why doesn't bounded work?" but... oh well? (And I guess that we COULD introduce a non-floor-aligned bounded later on if we found it to be in demand, but I don't really see that happening.)

The very fact that someone might then have enough clarity around the reference space system to ask that question means they understand the API better than they did with the old names.  If a straightforward API design leads folks to feel confident enough to clearly express future feature asks to us, I see that as a win.

> If nothing else I think we do need to make a consistent determination about whether or not creating a new stationary reference space is allowed to function as a software-driven recenter or if the origin for all stationary reference spaces is determined at session creation time (or similar).

In the Windows MR native APIs, creating another `SpatialStationaryFrameOfReference` (the equivalent of the `unbounded` reference space) _does_ implicitly center it again at your current position - however, the WinMR API doesn't support arbitrary `originOffset` values, and so that was the only way to get a recenter done.  In WebXR and OpenXR, apps can create new reference spaces at an offset from an existing reference space, and so having a common understanding of the origin across both spaces matters.  With the latest `getOffsetReferenceSpace` design in WebXR, we could get away with saying that recreating a reference space recenters it, but that seems less clear to me than just defining the physical location of each reference space type's natural origin once and sticking with it for the entire `XRSession`.

> I'd hate to see developers implement an in-app recenter mechanism only to discover that it doesn't work on Oculus devices because they have an externally calibrated seated origin.

If we go with the model where the native origin of any given reference space type is shared across all instances for the life of an `XRSession`, apps should end up consistently able to implement their own recentering, whether the underlying platform has an externally-calibrated origin or not:
* On a device with **no calibrated local origin** (e.g. Vive), the native origin of the `eye-level`/`stationary`/`local` reference space will be where the user's head was at the start of the session.  At the point that the app wants to recenter, the user's head will have moved some distance from that origin.  The app calls `myReferenceSpace.getOffsetReferenceSpace(viewerPose.transform)` and they receive a reference space recentered at the head's current pose.
* On a device with **an externally calibrated local origin** (e.g. Oculus Quest), the native origin of the `eye-level`/`stationary`/`local` reference space will be at some nearby location predefined by the user.  At the point that the app wants to recenter, the user's head will have moved some distance from that origin.  The app then calls `myReferenceSpace.getOffsetReferenceSpace(viewerPose.transform)` and they have their recentered reference space.

I believe that the combination of consistent native origins per reference space type and the availability of offset reference spaces puts us in a great place to allow `local` space to track either an arbitrary or pre-defined native origin, without confusing app-driven recentering logic.

The only observable difference then for apps is whether content they place around (0, 0, 0) at app startup will definitely be around the user's head or could be slightly off, if the user had walked away from their defined zero point.  This was discussed by @Artyom17, @casseverett and @speigg back in #389, specifically whether we needed an additional reference space to represent the platform's notion of where the user wants to operate "local" experiences.  The conclusion was that it's fine on the relevant platforms for `eye-level` space to just be that space... but that we should probably rename `eye-level` to `local` :smile:

**Comment by toji** [comment]
> I believe that the combination of consistent native origins per reference space type and the availability of offset reference spaces puts us in a great place to allow local space to track either an arbitrary or pre-defined native origin, without confusing app-driven recentering logic.

After reading through your comment I'm on-board with this approach!

> The only observable difference then for apps is whether content they place around (0, 0, 0) at app startup will definitely be around the user's head or could be slightly off, if the user had walked away from their defined zero point.

Given your previously defined model if this was of critical importance to the app wouldn't the recommended pattern be to get an `eye-level`/`local` reference space and then call `localReferenceSpace.getOffsetReferenceSpace(viewerPose.transform)` immediately?

**Comment by thetuvix** [comment]
> Given your previously defined model if this was of critical importance to the app wouldn't the recommended pattern be to get an eye-level/local reference space and then call localReferenceSpace.getOffsetReferenceSpace(viewerPose.transform) immediately?

Yep!  If an app absolutely must be centered around the user's head position under all circumstances, it can request `local` and then recenter immediately.

**Comment by Manishearth** [comment]
FWIW I do agree that the current names are a bit confusing (I've been confused by them before). When first trying to understand the spec I got quite confused as to the precise nature of eye-level and floor-level. A lot of the root causes behind this (identity being confusing, native origins not having been specced) have since been fixed, though. I'm not sure if I'd still be confused with the current names.

The proposed names do look better to me, especially with the consistency between stationary and bounded spaces wrt floors. I don't have strong opinions on stationary vs local though.

**Comment by casseveritt** [comment]
I'd be careful about calling a frame "stationary" without being very clear about what that means.  Perhaps world-stationary would be what's meant, but even that would be hard to asserting for frames like "local" when used on a plane, bus, cruise ship, etc. No reason to over-promise and have the name be a misnomer.

**Comment by toji** [comment]
That's an excellent point, @casseveritt, thanks! And that does tip the scales for me away from favoring the term `stationary`.

**Comment by chris-little** [comment]
Apologies for a naive question from a lurking newbie, but how do the reference space types fit with the AR use case of someone in a terrain, with a size of several kilometres across, looking at, for example, weather info, like wind arrows in a head-up type display? Experience from protoyping this resulted in having a changeable 'eye level' of say 100m above the surface, so that one can 'look down' at the 10m altitude wind arrows or Open Street Map imposed on the ground.

**Comment by toji** [comment]
@chris-little: I'm not sure if I fully understand the scale of the application you describe, but I think it fits into one of two categories, so I'll answer for both.

In one version your goal may be to superimpose weather data onto the real-world at 1:1 scale. Something that looks a bit like Google Maps AR feature:

![AR_Maps_P3a_transparent_2x](https://user-images.githubusercontent.com/805273/57797803-21a9eb00-7700-11e9-90ab-045129e4a1d2.gif)

In that case you would want to use a `unbounded` reference space, since your virtual content will be spread over a large area and that's exactly what `unbounded` is meant to handle. Note that you'd need some additional API surface that we haven't fully defined yet to really pull this effect off. At the very least you'd want anchors to keep the virtual element positions stable, and you'd likely need some interaction with geolocation APIs to determine where to place the content in the first place.

The other possibility is that you want to have a miniature map of an area, Google Earth-style, that you display the weather data over the top of:

![1301239129111696555](https://user-images.githubusercontent.com/805273/57798424-929dd280-7701-11e9-8545-d1206dd6b940.gif)
 
In this case you could still use an `unbounded` reference space if you wanted (and had anchors to pin the content to, say, a table) but you could also use a `bounded-floor` or `local-floor` space if it's sufficient to simply place the map at the floor or a fixed distance above it. Those reference spaces would likely have wider device support than `unbounded`, and would allow your content to work with a wider range of VR hardware as well as AR.

If you'd like some more information about what each of these reference spaces represent and the type of content they support, I suggest reading the [Spatial Tracking Explainer](https://github.com/immersive-web/webxr/blob/master/spatial-tracking-explainer.md)

**Comment by chris-little** [comment]
@toji Thnk you for the clear explanation and examples. Our use case is close to the first example, but we did have to stretch/alter the vertical cooordinates in the country-side with low orography. Determinisitic weather forecasts in city street canyons are probably still decades away, if at all. (Turbulence has a lot to answer for!) We had assumed we could seamlessly unzoom into the second case. Please keep up the good work!
