### ISSUE TITLE
The processing model text for requestPresent should describe behavior or leftBounds and rightBounds attributes

### ISSUE THREAD

**Issue by kearwood** [immersive-web/webxr#66]
The processing model text at https://w3c.github.io/webvr/#dom-vrdisplay-requestpresent should describe the use of the VRLayer's leftBounds and rightBounds attributes.

Additionally, it should describe what will happen if the leftBounds or rightBounds attributes are null, empty, or an incorrect length.

**Comment by bzbarsky** [comment]
Why would they ever be null?

**Comment by toji** [comment]
`null` is a convenience notation for "the default bounds" in this case, which is `[0.0, 0.0, 0.5, 1.0]` for `leftBounds` and `[0.5, 0.0, 0.5, 1.0]` for `rightBounds`. This is described in the documentation for the VRLayer. @kearwood's issue pertains to the text describing what happens when requestPresent is called.

**Comment by bzbarsky** [comment]
My point is that it doesn't make sense to allow `null` here at all.  See https://bugzilla.mozilla.org/show_bug.cgi?id=1250244#c316 for details.  And yes, I know what the issue is about; it's filed because I asked for it to be filed!

**Comment by kearwood** [comment]
I have added a separate issue to capture a proposed change to the webidl and processing model to replace the null values:

https://github.com/w3c/webvr/issues/71

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#3
