### ISSUE TITLE
Should requestReferenceSpace() wait until getViewerPose() won't be null?

### ISSUE THREAD

**Issue by thetuvix** [immersive-web/webxr#674]
@NellWaliczek had an interesting idea for `requestReferenceSpace()` to wait until the viewer pose won't be null.  I do wonder, however, if that won't cause other problems in apps that were tested on systems where this continues immediately.

Thoughts?

_Originally posted by @thetuvix in https://github.com/immersive-web/webxr/pull/559/review_comment/create_

**Comment by cwilso** [comment]
Blocked on finishing #243.

**Comment by klausw** [comment]
This is important for smartphone AR, where there may be several seconds delay between session start and establishing tracking for valid poses. If the `requestReferenceSpace()` response is delayed, the application would need to restructure the main drawing loop to either work without a reference space, or use a separate `viewer` reference space, if it wants to draw before getting a pose.

On the flip side, a delayed response could potentially mean that poses are effectively never null on some platforms, so apps assuming that may no longer cope well with tracking loss or transient null poses.

(Overall, I think either approach would work, it's mainly a matter of clearly documenting and establishing best practices for apps.)

**Comment by thetuvix** [comment]
Alternatively, for smartphone AR, the origin of a `local` reference space is arbitrary anyway, and would likely just end up at the position of the first 6DoF pose generated by the device.  Could a `local` reference space just start tracking right away with live orientation but an `emulated` position at the origin, and then set `emulated` to false once 6DoF tracking is established?  Or is even orientation tracking not available for those few seconds?

**Comment by klausw** [comment]
@thetuvix wrote:
> Could a local reference space just start tracking right away with live orientation but an emulated position at the origin

Interesting idea, but this seems to add a fair amount of complexity to the implementation, especially if it would require using a separate source of orientation data if the underlying AR platform doesn't deliver any pose information at all before 6DoF tracking is established.

A typical use case is that an AR app may want to start drawing instructions or a non-world-attached intro banner on startup, then waiting for a signal that tracking got established. Currently, that signal is generally poses becoming non-null, and in the alternate proposal it would be getting a reference space. A switch from emulated to non-emulated position seems a bit odd to me, but I don't have a strong opinion as long as the behavior is sufficiently clearly documented to avoid implementation differences.

**Comment by NellWaliczek** [comment]
I'm not 100% clear why this problem is unique to establishing tracking?  I mean... requestReferenceSpace() returns a promise with no guarantee of when it will actually complete.  If the page wants to render something before spatial tracking is established, can't it use a viewer reference space since that would return the fastest?

**Comment by klausw** [comment]
This is also an interesting question for bounded reference spaces, especially for platforms where the device may go through a state where it already returns 6DoF poses but doesn't know the boundary location yet. That state might last for a couple of seconds until it recognizes the room, or potentially longer if it is waiting for the user to define bounds or move to a previously-mapped location.

Is the expectation that the `requestReferenceSpace('bounded-floor')` promise should remain unresolved until nontrivial bounds are available? 

Alternatively, since the bounds can vary per-frame, the promise could resolve immediately and return an empty or trivial bounds list (i.e. a 1-foot square around the current location) that then gets updated later, though that doesn't seem particularly helpful to applications. It seems that the spec doesn't technically require a minimum point count or area, though a zero-point polygon would be a stretch of the "MAY be convex or concave" description.

Applications could prompt the user to move to a larger bounded space when the current bounds are unexpectedly small, and this sounds useful for multi-room-capable untethered VR systems where the user could choose to move to a larger room, but it seems weird to do this from the start to get around temporarily unknown bounds.

In any case, am I understanding the spec correctly that requesting `bounded-floor` spaces requires that the app must first ask for the `bounded-floor` feature as either a required or optional feature in its `requestSession` call? But even if it's in `requiredFeatures`, the session could still be established if the hardware in general supports it and there's consent, but there's no guarantee that the bounded reference space will actually become available in a timely manner, with useful bounds, or at all. Does that sound right?

**Comment by toji** [comment]
/agenda to try and clear out some of the older pre-CR issues.

**Comment by Manishearth** [comment]
I don't see a pressing need to _require_ UAs to withhold reference spaces until they have tracking. UAs should definitely be _allowed_ to do so, e.g. if a reference space internally requires the creation of an anchor in the backend.

It would also be weird if this only happens at the beginning of the session -- what makes the lack of tracking at the beginning of the session special? OTOH, it's also weird if we make this happen during all tracking loss situations, because you could have obtained the reference space earlier if you wanted.

Apps need to learn to handle null poses either way, so I'd rather go with the fully general "you may be able to get a reference space before it is able to return non-null poses" so that people will write code that can handle null poses.


------

As for the boundsGeometry thing, I feel like `requestReferenceSpace("bounded-floor")` should only return when it's able to provide _some_ nonempty bounds geometry, but it's okay for the UA to initially return a small set of bounds and then trigger a reset event with the actual bounds.

**Comment by thetuvix** [comment]
> Apps need to learn to handle null poses either way, so I'd rather go with the fully general "you may be able to get a reference space before it is able to return non-null poses" so that people will write code that can handle null poses.

I believe this assertion is where the tension comes from.

With the design we currently have specified for [populating a pose](https://immersive-web.github.io/webxr/#populate-the-pose), the only situation where an app would receive a null pose when relating two spaces is "if `space`’s pose relative to `baseSpace` has never been determined.":
> Else if `space`’s pose relative to `baseSpace` has never been determined:
> - Set `pose` to `null`.

After that relationship is first established, it's the job of the underlying XR platform (or else the UA), to use "the last known position/orientation of `space`’s effective origin in `baseSpace`’s coordinate system", using `emulatedPosition` to reason about whether the anchor can be found right now.  This means that if we can somehow get past the initial warmup period for locating a given space, an app would never need to reason about poses in that space being null again, especially if the app only encountered null on some UAs and not others.

At the same time, if some UAs or some platforms surprise apps by not giving back the reference space for many seconds, that could also cause app compat issues for apps that always saw such spaces coming back within a few frames.  If an app only tested on platforms that quickly yield a reference space, it's unlikely to have built some pre-6DoF fallback experience in `"viewer"` space.

My instinct is that the most compatible path here is for world-locked reference spaces to be returned to apps ASAP, but start out initially with the camera at position (0, 0, 0), updating only the orientation.  @klausw pointed out above that this could be a problem for UAs built on underlying XR platforms that do not offer any orientation updates until positional tracking is first established. 
 However, is ARCore such a system?

For example, [`ArCamera_GetPose`](https://developers.google.com/ar/reference/c/group/camera#arcamera_getpose) unconditionally gets the camera pose in raw world coordinates, with the following caveat noted:

> Note: This pose is only useful when ArCamera_getTrackingState() returns AR_TRACKING_STATE_TRACKING and otherwise should not be used.

However, the definition for [`AR_TRACKING_STATE_PAUSED`](https://developers.google.com/ar/reference/c/group/common#artrackingstate) says:
> ARCore has paused tracking this object, but may resume tracking it in the future.
> 
> This can happen if device tracking is lost, if the user enters a new space, or if the Session is currently paused. When in this state, the positional properties of the object may be wildly inaccurate and should not be used.

Specifically, it notes that the positional properties of the object may be wildly inaccurate.  However, does that apply to the orientational properties of the object?  If not, that orientation plus a (0, 0, 0) position could serve as the bootup `emulatedPosition` = true pose for the `"local"` reference space, which can then transition into the headset seamlessly moving away from (0, 0, 0) once 6DoF tracking is established by recording whatever transform is needed on the first frame of tracking to position the camera at (0, 0, 0) facing in the same heading that frame.

This is a somewhat increased ask to place on UAs, but if possible it could help eliminate an entire class of divergent app behavior across platforms.

**Comment by Manishearth** [comment]
> if `space`’s pose relative to `baseSpace` has never been determined.":

Hmm, fair. I kinda wish we hadn't picked this route, but too late for that.

**Comment by Manishearth** [comment]
Related: https://github.com/immersive-web/webxr/issues/1042

**Comment by Manishearth** [comment]
Thinking about this more, while `getPose()` should definitely be allowed to return null mid-session (see https://github.com/immersive-web/webxr/issues/1042), we can still require that _for reference spaces_, "populate the pose" always returns a valid pose.

**Comment by Manishearth** [comment]
> I somewhat feel like it's better to have the freedom to return null here, though. There can also be cases involving security: e.g. stuff involving user focus where we might want to return null.

Yeah, so it seems like the "document is hidden" case is one where we probably want to return a null pose

**Comment by Manishearth** [comment]
I've included these changes in https://github.com/immersive-web/webxr/pull/1058 . With that PR, `getPose()` continues to have the ability to return null, however `getViewerPose()` is forced to emulate whenever tracking is lost. `requestReferenceSpace()` now waits for tracking to have been established.

**Comment by Manishearth** [comment]
/agenda to discuss the choice between #1068 and #1070 for this

This has been discussed a couple times already and I _think_ folks in general prefer #1070, but I just want to have a quick check in a call
