### ISSUE TITLE
WebGL context compatibility for devices where inline and immersive have different requirements

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#675]
In https://www.w3.org/TR/webxr/#contextcompatibility, there is discussion of when a WebGL context is XR-compatible. This is a flag, which can be initialized as `true` by requesting an xrCompatible context from a canvas, or by calling `makeXRCompatible()` on an existing context.

This assumes that XR compatibility doesn't depend on the XR session mode, and in particular assumes that immersive and inline sessions have the same notion of compatibility.\

Should this property be an `XRSessionMode?` rather than a boolean?

**Comment by asajeffrey** [comment]
Related to #653.

**Comment by cwilso** [comment]
Possibly tied to fingerprinting.

**Comment by toji** [comment]
I thinks this can safely be closed now that #705 has landed, since it removes the requirement for inline sessions to pass the compatibility check. Inline sessions no longer rely on the XRSession to provide compositing (that may return in a later spec level or module) and simply pass the commands through to the WebGL context like any other WebGL app, so the "compatibility" of the context is moot as long as it can display on the page.

Any issues that may arise from attaching an XRCompatible context to the DOM should be addressed in #603.
