### ISSUE TITLE
Consider moving baseLayer from XRRenderState[Init] to XRSession

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#680]
As mentioned in https://github.com/immersive-web/webxr/issues/677, the members of `XRRenderState[Init]` were grouped together because they are applied at the same time. This makes sense for the doubles, but should `baseLayer` be grouped in with them?

Consider:
* `baseLayer` is the only interface member in these objects (after #656).
* The current for XRRenderState [says](https://immersive-web.github.io/webxr/#xrrenderstate-interface), "values that developers can configure which affect how the session’s output is composited," which doesn't seem to describe `baseLayer`.
* Layers may eventually become much more complex (see https://github.com/immersive-web/webxr/issues/670), and it may be problematic to group layers in with `XRRenderState` or to train developers to think about layers in this way.
  * Supporting or polyfilling (as discussed in https://github.com/immersive-web/webxr/issues/670#issuecomment-497863931) `baseLayer` may be more difficult if `baseLayer` is set through this mechanism if we want to manage layers at the `XRSession` level.

One possible solution - without trying to address multiple layers now - would be to add `void updateBaseLayer(XRLayer baseLayer);` to `XRSession`. The timing for when the new layer gets applied would be the same as `updateRenderState()`. (Per #513, we probably don't need to expose the current value.)

**Comment by toji** [comment]
Since the render state is all about making frame-aligned state changes, and the layers are absolutely something we want frame aligned, this attribute will stay put. Future layer designs that expand the number of layers we can work against will also be set on this structure.

Simply put, we don't want to do unnecessary spec work to synchronize multiple pieces of state from an array of functions when we can ensure that all frame-aligned state changes are funneled through a single function instead.
