### ISSUE TITLE
Decide on test API to match "VR complete" and update Web Platform Tests

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#691]
Web Platform Tests (WPTs) are critical to increasing the likelihood of interoperability, especially with so many early implementations in the works. Tests are also an important part of showing [implementation experience](https://www.w3.org/2019/Process-20190301/#implementation-experience), which is required to move the spec through the W3C process. In order for the WPTs to be effective, we need to ensure they are written in a way that is compatible with the various implementations and that there is good coverage for the specification's algorithms.

Given the changes to the WebXR Device API in the last year, the proposed [test API](https://github.com/immersive-web/webxr-test-api) should probably be revisited to ensure it aligns with the concepts in the spec. (@Manishearth has proposed some such changes in https://github.com/immersive-web/webxr-test-api/pull/10.) This is especially importance since Servo and Gecko are currently using a different version of the API than Chrome, meaning tests can't currently be shared across implementations.

I'm filing this issue to ensure this important work is tracked and to raise its visibility (very few people are currently watching the [webxr-test-api](https://github.com/immersive-web/webxr-test-api) repo). I think the next steps are to drive updates and stabilization of the Test API then migrate browsers and tests to the new API and ensure all such tests are uploaded to the [shared WPT repo](https://github.com/web-platform-tests/wpt/tree/master/webxr).

Those that are interested in interoperable tests, please subscribe to this issue and watch the https://github.com/immersive-web/webxr-test-api repo. We can discuss specific Test API changes in issues there. In addition, it probably makes sense for the WG to track overall progress alongside the main spec.

/cc @Manishearth, @alcooper91

**Comment by Manishearth** [comment]
Some more context: as discussed at the face-to-face, folks are interested in non-conservative changes to the test API. https://github.com/immersive-web/webxr-test-api/pull/10 was written with the goal of changing as little as possible, but given this guidance I'm hoping to come up with a fresh from-scratch proposal.

I'm planning on working on a strawman proposal for this next, and posting it as an issue on the repo. We can collaborate on it from there!

**Comment by ddorwin** [comment]
Thanks for the additional context and update! Sounds good. Do you have an ETA for an initial proposal?

**Comment by Manishearth** [comment]
I've got a WIP, I can probably finish it up today.

**Comment by Manishearth** [comment]
Updated https://github.com/immersive-web/webxr-test-api/pull/10 with my strawman proposal. Please comment on it there. Once we've pinned down the API I can fill in the explainer text.

**Comment by Manishearth** [comment]
Should we be putting this on a meeting agenda? I'm not sure if there's much to _discuss_ in the meeting aside from "please look at this proposal and leave comments". I would like for us to be able to start implementing this and migrating the tests soon, if possible :smile: 

cc @AdaRoseCannon

**Comment by alcooper91** [comment]
I mentioned this on immersive-web/webxr-test-api#10, but I think it may be better to merge that PR, close out the old issues and direct people to the open issues (or to open new issues), just so that we can clearly isolate/manage the conversations and show a more clear diff (with that PR being the "reset" so to speak)

**Comment by Manishearth** [comment]
Agreed, we've got a reasonable amount of agreement on that PR, most issues are minor, and we should at least merge it so that we can talk about it easily.

I'm not precisely sure when we should start implementing it -- I'd like all the implementations (right now, Chrome and Servo) to upgrade simultaneously, but I don't know what level of signals from other browsers we need before doing so. Does anyone know what Chrome's plan is here? My plan for Servo is to implement the test API when Chrome decides to do it, and work together on upgrading the tests.

**Comment by Manishearth** [comment]
As discussed in the meeting today we're hoping to get feedback this week, and hopefully start implementing next week. Since @ddorwin is on vacation Brandon said @johnpallett would likely know what Chrome's timeline on this is. John, can you give us an idea of when y'all would be comfortable implementing the test API? I can work with y'all and simultaneously update servo, as well as work on fixing all the tests.

**Comment by alcooper91** [comment]
I think that plan makes sense.  I'll need to talk to a few people to get a better sense of when we'd be able to get to this work, and can hopefully give you an answer later today or tomorrow.
Is your plan to update servo and break the tests and then bring them back to working, or to implement both APIs and then switch the tests over, hopefully working all the time?

**Comment by Manishearth** [comment]
Servo doesn't use the WPT tests yet, since Servo directly implemented the API I had prototyped in the first version of https://github.com/immersive-web/webxr-test-api/pull/10 . Servo has its own tests (not in WPT, but using the same harness) for now.


My plan is to update Servo to the latest API, update Servo's builtin tests, and then try and move over the main WPT tests. The last step can't be landed without coordination with Chrome :smile: 

Currently Chrome is the only user of the WPT tests, so it's entirely up to y'all when and how to do that migration. I can help once I've got the new API implemented in servo.

**Comment by Manishearth** [comment]
I've got a PR for implementing the basics of the new API in servo [here](https://github.com/servo/servo/pull/23641). Input isn't included yet, and we don't yet support bounded/unbounded spaces so a bunch of other stuff is ignored.

**Comment by alcooper91** [comment]
To clarify: We think that it should be okay to update the existing tests at the same time that Chrome updates our implementation then, since we're the only one running them actively?
I think it's reasonable for us to try to get the test updates done in M77 (branch is in ~a month), once we feel confident enough in the test API.  I filed an umbrella bug for this work [here](http://crbug.com/979275).  We have some internal input tests, but I think I'd consider the input work to be the last of the updates that we make.

**Comment by Manishearth** [comment]
> To clarify: We think that it should be okay to update the existing tests at the same time that Chrome updates our implementation then, since we're the only one running them actively?

Yes. Because of how WPT vendoring works this basically means that Chrome can update the tests and implementation simultaneously. Until they do, other browsers can't update the tests without breaking Chrome.

**Comment by NellWaliczek** [comment]
Closing in favor of tracking this work in the webxr-test-api repo now that the "/agenda" bot works across all repo in our org
