### ISSUE TITLE
What types of capabilities should applications be allowed to request?

### ISSUE THREAD

**Issue by ddorwin** [immersive-web/webxr#727]
In addition to specifying when (#720) and how (i.e., #723) applications can request capabilities/features, we will need to determine what are the actual capabilities/features to be exposed. Before we get to that, though, it probably makes sense to explore the categories or dimensions of capabilities that should be exposed. Although the focus has been on consent, there _may_ be other reasons that applications should request capabilities up front (see #723).

The privacy design (#638) details various threats and why consent might be required, but further work is necessary to determine how many different dimensions of consent make sense and what they should be.

As said in response to question 7 in https://github.com/immersive-web/webxr/pull/689#issuecomment-502262866, IMO, something like "spatial-tracking-unbounded" is probably too granular and would become difficult for developers to use. IMO, it probably makes more sense to define what the user is giving up, which may not map 1:1 to a single concept in the API surface.

**Comment by NellWaliczek** [comment]
It's funny, I was actually thinking in a very different direction with #723, though I can see why you'd prefer to separate this discussion from that one.

Do you have a specific proposal for what "defining the user is giving up" would mean?  Are you optimizing for developer difficulty or end-user difficulty?  Because my original though on the topic is developers might find it less confusing if they just indicated which APIs they plan on calling, which is even more granular.  So i'm really interested in seeing what your alternative might look like.

**Comment by NellWaliczek** [comment]
In terms of the way these consent prompts are communicated to the users, I totally agree that the api-level granularity doesn't make much sense.  However, from a developer's perspective of knowing how to ensure necessary prompts are displayed, it does.  In my proposal in #739, the communication from the developer to the UA is done granularly, but because it's all done up front the UA has the option to explain things in the way they thing will make the most sense to their users.

**Comment by johnpallett** [comment]
For context, here is a [suggested list of privacy-sensitive features and associated user communications](https://github.com/immersive-web/webxr/blob/67b0c0992e7d82c383d619900ef110a36c3bfade/designdocs/privacy-design.md#user-communication).

**Comment by NellWaliczek** [comment]
Closed by #739
