### ISSUE TITLE
Wording for updateRenderState implies required fields are optional

### ISSUE THREAD

**Issue by jacobcdewitt** [immersive-web/webxr#759]
In the spec at https://immersive-web.github.io/webxr/#dom-xrsession-updaterenderstate , it says "If newState’s depthNear value is set, set session’s pending render state's depthNear to newState’s depthNear."

This implies that XRRenderState.depthNear is nullable even though it is not, according to https://immersive-web.github.io/webxr/#xrrenderstate . There is the same issue for depthFar.

**Comment by toji** [comment]
This is admittedly a little weird in terms of spec text, because it LOOKS like it should be an area where the dictionary should have default values, where in actuality that would be bad. It becomes significantly less confusing when you look at the actual use, though.

All values in the dictionary passed to `updateRenderState()` are unset (will report `undefined`) by default, which is distinct from being set to `null` by default. Only values that are explicitly filled out will be considered "set", which is the state the algorithm is testing for. Since it tests or that state on every value what it means in effect is that calling this function will only modify the values that the developer explicitly sets. Consider the following:

```js
// initial internal state: { depthNear: 0.01, depthFar: 1000, baseLayer: null }

session.updateRenderState({ baseLayer: webglLayer });
// internal state on the next frame: { depthNear: 0.01, depthFar: 1000, baseLayer: webglLayer }

session.updateRenderState({ depthNear: 1, depthFar: 100 });
// internal state on the next frame: { depthNear: 1, depthFar: 100, baseLayer: webglLayer }
```

It would be surprising for most developers if the second call to `updateRenderState()` ended up reverting `baseLayer` to `null` because it wasn't explicitly set as part of the dictionary that specified the depth range. Especially considering that the two calls are likely to be made in different areas of the code. This problem would become worse as the API evolves and new values are added to the render state which older applications did not anticipate.

The end result of the above is that none of the dictionary values are required because that would force developers to overwrite the value every time they called `updateRenderState`.
