### ISSUE TITLE
Should XRWebGLLayers clear/invalidate their framebuffers prior to each frame

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#775]
I'm relatively certain that we've had this conversation before and that the consensus was "yes, they should" but I can't find any record of it (which is a fail on my part) so let's get this done properly!

We should explicitly state whether or not framebuffers provided by `XRWebGLLayer` (and in the future similar layer sources) should be invalidated or cleared by the WebXR implementation prior to each frame. My recollection is that on some platforms the target buffers provided by the native API will be invalidated by default, and as such forcing web apps to do an explicit clear each frame "just in case" is a waste of fillrate in a situation where we have very little to spare. As such the spec should probably just specify that framebuffers are "ready to go" at the start of each frame so that developers can skip the clear step with confidence.

Any objections?

(I **definitely** recall that we made the explicit decision to leave the `preserveDrawingBuffer` option off of the `XRWebGLLayer` for similar reasons, so we don't ever need to worry about needing to preserve the content of the buffer for more than a frame.)

**Comment by toji** [comment]
Oh, and to be clear: I don't see this as a backwards compatibility-breaking change. If we decided that yes, everything should be cleared then the worst that we do in introduce some unnecessary overhead for early apps that assumed a clear was necessary, but no content will break.

**Comment by klausw** [comment]
Somewhat related, if the spec adds new optional features that supply color or depth buffers to the app, i.e. pose-aligned AR camera frames or occlusion data, would this potentially use prepopulated attachments to the webxr framebuffer? That's a separate decision, but I think that requiring UA-provided ready-to-use framebuffers and discouraging apps from calling `glClear` would help add flexibility for this in the future.

For background (no pun intended), the experimental `legacy-inline-ar` implementation in Chromium had been using a color buffer prefilled with camera data instead of being blank, so a `glClear` from the app would break AR mode by erasing the camera image. The current `immersive-ar` implementation no longer does this since it composites the app-drawn image as a separate step, and adding camera frame access may be more useful as a separate texture anyway, but a hypothetical prepopulated depth buffer might be most convenient if it's directly available without copying.

**Comment by asajeffrey** [comment]
For the Servo implementation of WebXR, it doesn't make a huge amount of difference whether user code calls `clear` or the device driver does. I'm not sure which clear colour would be used if it's the device driver though, are we going to say that it's the clear colour of the WebGL context for the WebXR content?

**Comment by toji** [comment]
I think we'd want to specify it as transparent or opaque black, depending on whether or not the framebuffer has an alpha channel.

**Comment by asajeffrey** [comment]
That would certainly be the easiest to implement.

**Comment by cabanier** [comment]
> The only buffers the WebXR API should lazy clear are ones it specifically hands out to web developers. In the future, the plan is to have XR WebGL layers supply just a texture array to the web developer that they can use in any framebuffer of their choosing. 

I have not heard about such a proposal. Is this for a new WebXR spec?

**Comment by RafaelCintron** [comment]
@cabanier , the issue I was referring to was the [Use Texture Arrays with WebGL 2](https://github.com/immersive-web/layers/issues/8) one. It will be part of the layers module.

**Comment by toji** [comment]
Put up a pull request to fix this at #866. Don't think it'll be controversial, but please take a look!
