### ISSUE TITLE
When is getFrameData/getPose allowed to query new values when not presenting?

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#81]
According to the current spec language for `getFrameData`:

> Subsequent calls to `getFrameData()` MUST provide the same values until the next call to `submitFrame()`.

But if the user is calling `getFrameData` and doesn't need call `submitFrame` (For example: A magic window preview of the content before presenting.) It seems like the data should be allowed to update at some point. 

I can think of a few possible resolutions:
- When not presenting `getFrameData` is not rate limited. This will cause some discrepancies in apps that query the frame data multiple times in different locations (Every Three.js VR app) and cause the non-presenting case to potentially do more work since those repeated calls can't early terminate.
- Require that `getFrameData` (and probably `submitFrame` while we're at it) be called in a VRDisplay.requestAnimationFrame callback, which allows us to reset the dirty bit at the top of every rAF. 
- Go back to making the value stay the same for the duration of the javascript callback. I don't recall what prompted Mozilla to want to change that language. I'm probably overlooking a problem with it. I have recently had comments in a code review that indicate that in Chrome this is somewhat expensive to track.

Thoughts?

**Comment by ssylvan** [comment]
Tying it to the RAF (2nd bullet) is not a bad idea IMO. It makes things nice and buttoned up in terms of the flow of applications.

We could also say that getFrameData _must_ return fresh data if possible (i.e. if your device only updates pose data at N Hz, it may give the same data if you call it twice in a row, but as soon as it is able to compute new data it must do so). I.e. rather than remove the rate limit (and having different behavior when presenting or not presenting) we say that this is the function that goes off and computes a new pose - you should cache the data in typical operation. Maybe the name "get" is too mild and it should be computeFrameData or something to imply that there's some work involved to do this.

**Comment by toji** [comment]
I should point of that the purpose of the rate limit was to ensure that a frame stays in sync no matter who does the getPose/getFrameData call. We saw several uses of the library where the pose was being queried several times from several different files and/or libraries and all used as part of the same frame. For example: In Three.js the WebVR support is split across two files: VRControls, which effectively moves an object (like the camera) in sync with the headset, and VREffect, which actually handles rendering the scene  in stereo. Both of them query the frame data independently, but VRControls typically does so at the beginning of a frame while VREffect does so near the end of it. If we allow the call to potentially pick up new data every time there may be some weird disparities in the render because of it.

(It would be even worse in something like a library that was superimposing elements like UI over the top of a scene that's rendered by a completely separate library.)

It would, of course, be valid for us to determine that this is the app's problem. We could absolutely say "No, the correct pattern is that you query once and pass the frame data into anything that needs it." But that does mean it's easier to do it wrong, and in general I prefer methods that are harder to misuse when it's sensible to do so. I do think that having these methods return the same value for the duration of a "frame" falls into that category. I'm also willing to be swayed if someone feels strongly otherwise.

That aside, I'm growing more fond of tying this to the vrDisplay rAF, and overall I think that there's a few benefits that could come from more strictly enforcing "Frame query/submit must happen in a VR rAF."

**Comment by ssylvan** [comment]
Ah okay, yeah I think I agree that it makes sense to keep the return value the same for the duration of the RAF in that case.

**Comment by brianchirls** [comment]
I think it's not a bad idea to force the data returned to be synced with a frame, but disallowing the method calls outside of rAF could cause trouble. I can imagine some uses for that data outside of rendering. For example: rendering an on-screen preview of the headset view in `window.requestAnimationFrame` while the display is not presenting; checking whether the headset is moving or not to affect simulation states, like showing an on-screen prompt when the headset is picked up (i.e. starts moving).

**Comment by toji** [comment]
Brian: `vrDisplay.requestAnimationFrame` is already specced to be equivalent to calling `window.requestAnimationFrame` when the display is not presenting, so that would resolve that particular issue. Still could be valid use cases for querying the value outside of a rAF, though.

**Comment by brianchirls** [comment]
Thanks, @toji. That's good to know about the different rAF's.

**Comment by RafaelCintron** [comment]
I understand that the current rationale for having getFrameData be frame limited is to make things easier for third party libraries. 

I am not intimately familiar with how the third party libraries in question work.  However, presumably, they have a piece of code that runs at the beginning, a piece of code that runs at the end and calls submitFrame (or not), and code in between that calls getFrameData all over the place.

Suppose we change the API so that getFrameData becomes computeFrameData and returns data with new prediction as Sebastian suggests.  There is nothing stopping third party libraries from adding a function to VRDisplay called getFrameData which, during the "piece of code that runs at the beginning" section I referred to above, calls computeFrameData and caches it in an expando on the object. This way, the library does not have to pass the cached frame data into every helper function and we leave it up to them to manage things however they please.  Of course, the libraries in question would have to agree on what convention to use if there is more than one.

Changing getFrameData to computeFrameData also opens the door for improved libraries than can handle dealing with mid-frame updated predictions.  For instance, if you have a long running simulation loop, it may make sense to have the simulation run with different prediction than rendering even though both items are in the same frame.  

Going with Brandon's third bullet point (values stay the same for the entire callback) means that the second call to submitFrame would have to throw an exception or at least be thrown away.

**Comment by mkeblx** [comment]
I don't see why `getFrameData` has to be constant per rAF. Is there a problem with having `getFrameData` have the behavior of the former `getImmediatePose` in all cases whether presenting or not, i.e. latest data (but, incorporating prediction, at UA discretion)? Did take out `getImmediatePose` as virtually no one was using but just because `getPose` was shorter/easier.

As @toji says can leave up to the app. Libraries that need the same value for all or part of render loop should have the responsibility to cache/pass around internally. In the Three.js case where calling 2x per frame instead of 1x, likely not that big of an issue work wise in either case. I think it makes sense to put more responsibility on libraries which can eventually handle mid-frame updates, ~late-latching, etc. (Plus likely that VR rendering will be incorporated more directly into renderer and not separate effect + controls, etc).

There are going to be cases where multiple separate libraries active on page trying to access frame data (https://twitter.com/thespite/status/774648210711318528) so would have data (pose) discrepancies (maybe not really be consequential though). But probably not more than a 2~3 though (Although someone is probably going to have a big grid of `allowvr` iframes with every one calling `getFrameData` at 60Hz+ each.)

A lot of this comes down to how WebVR is going to handle prediction..

**Comment by mkeblx** [comment]
Actually the more I think about it I like the two function approach instead of trying to make work with only one. `getFrameData` constant per frame and an `computeFrameData` (or `updatePrediction`) to update. Do we need only one function?

**Comment by toji** [comment]
I guess the question then becomes who calls `computeFrameData?` If your app has composed together several different libraries that are all independently fetching the frameData won't each of them end up calling `computeFrameData` "Just in case?" Then whoever calls it last "wins" and the rendering results for everything else that has come before are out of sync.

**Comment by brianchirls** [comment]
@toji Right. At that point, you may as well just have the one function `getFrameData` give you the current data, since you've gotta do the coordinating across your application anyway.

**Comment by mkeblx** [comment]
Ah right... can get rid of one side effect but doesn't handle out of sync issue. Ideally a single renderer but can't enforce. I haven't seen any superimposing UI libraries though and somewhat hard to imagine soon as even a library just doing a static centered cursor (or an in-VR stats lib) for three.js would be tough as tightly coupled to app, rendering state, 3D depth issues, etc. And probably done on separate VRLayer.

@RafaelCintron Do you know how Hololens handles say two separate applications that are each handling their own rendering and querying of frameData equivalent (and thus able to get different values if can do mid-frame update) of what would be two boxes directly against each other? If different values used could see in-world separation or overlay between them.

But handling of prediction & updates (and maybe related VRLayer handling) could be kicked down road to 1.1/1.2.

**Comment by mkeblx** [comment]
@brianchirls Well it does make coordination at least a bit easier in say a three.js context where could use `getFrameData` in multiple spots without needing to pass into i.e. a `VRControls`, with convention of really only final render doing a `computeFrameData` update at final stage.

If thinking ahead.. is this way would (want to) do multiple libraries actually doing rendering, to different layers?:

```js
// lib1
var layers = display.getLayers(); // if 1st => []
layers.push( { source: canvas1 } );
display.requestPresent( layers );
display.requestAnimationFrame(function r(){
  display.requestAnimationFrame(r);
  display.submitFrame();
});
```
```js
// lib2
var layers = display.getLayers();
layers.push( { source: canvas2 } );
display.requestPresent( layers ); // update layers
display.requestAnimationFrame(function r(){
  display.requestAnimationFrame(r);
  display.submitFrame();
});
```

Who does `submitFrame`, how do coordinate that happening once per frame?

> submitFrame() Captures the current state of the VRLayer currently being presented and displays it on the VRDisplay.

(Also, singular `VRLayer`.)

**Comment by ssylvan** [comment]
Quick question: How do these 3rd party libraries know which canvas to render to? Presumably the "main" app has to provide that? Or is there a global way to access the "current" WebGL context or something? Sorry if this is a dubm question, I'm a Hololens guy, not a web guy :)

In the Hololens APIs we sort of avoid this issue by API design by having the system provide the render target to the app bundled up into the equivalent of VRFrameData (HolographicFrame). Thus, when the main app wants to let a third party do some rendering, it kinda _has_ to pass the HolographicFrame anyway in order to give it somewhere to draw to, and as a result it would also get the same view matrices etc.. Each lib getting its own HolographicFrame just isn't a thing they would do because it would be very obviously broken (since they would then also get the their own render target etc. and not render to the same place the main app is rendering to).

**Comment by toji** [comment]
3rd party libs could conceivably query `vrDisplay.getLayers()` to retrieve the `VRLayers` passed to `requestPresent`, then grab the source canvas off of that. I imagine it's far easier for most apps to require that the target WebGL context be passed in during init, though.

**Comment by RafaelCintron** [comment]
@mkeblx The [App Views on HoloLens](https://developer.microsoft.com/en-us/windows/holographic/app_views_on_hololens) article goes into detail on how applications create views and how those views are managed by the HoloLens shell.  In summary, only one application at a time can have a Holographic view that renders 3D content, including the shell itself. Applications can have one more more slate views that are renderd by the shell in the world.  

Back to the web: Yes, any given site can use helper libraries.  However, there ultimately has be code in charge of the world that makes decisions like "OK everyone, we're now going to do a simulation loop with these parameters", and "OK, everyone, we're now going to render all the things to this here canvas" and, finally "OK, now that everyone is done rendering, I'm going to call submitFrame." This in-charge-of-the-world code is what would be responsible for calling updateFrame or updateCurrentPrediction or some other API (we can call it what we want) that sets up a new prediction even though the frame may not be submitted yet.  

Updating prediction can be for a future version of the WebVR spec but I think it would be beneficial for applications that have non-trivial simulation loops.  The [Rendering in DirectX](https://developer.microsoft.com/en-us/windows/holographic/rendering_in_directx) article provides more information on setting up the rendering loop and incorporating updateCurrentPrediction into your application.

**Comment by toji** [comment]
This issue has been solved by ensuring poses are delivered in sync with XRSession frames. Closing.
