### ISSUE TITLE
No way to get individual attachments out of the opaque framebuffer

### ISSUE THREAD

**Issue by magcius** [immersive-web/webxr#896]
This seems to be intentional considering how much spec verbiage is dedicated to the concept, but I urge to reconsider.

The concept of a "GL Framebuffer" is a very bizarre concept that has been ditched in most modern APIs, instead allowing individual attachments to be bound directly to the render pass. Many engines use techniques like multiple-render-targets, or HDR/LDR buffers, where targets are used in many different cases, and framebuffers are an unnatural fit.

For instance, my graphics API ditches the concept of framebuffers entirely, and has a single framebuffer where attachments are swapped out before being drawn. This is not expensive on any OpenGL implementation that I am aware of. https://github.com/magcius/noclip.website/blob/94a763b9cb311e823b0b08d03c0eade34087f3c7/src/gfx/platform/GfxPlatformWebGL2.ts#L1443-L1480

Supporting rendering to a single opaque framebuffer is awkward in this engine. I would likely do all my rendering offscreen, and then use a single blitFramebuffer, or draw, to copy the contents over to the opaque buffer. I also don't know how a depth buffer would work in this scheme. Currently, it is impossible to glBlitFramebuffer any multi-sampled buffer (this is a very bizarre GLES limitation, I have never understood it), so it's impossible to copy a depth renderbuffer that's multi-sampled. Ultimately, this means that I cannot render a depth buffer into WebXR's depth buffer, which is something WebXR recommends against. I could investigate doing a resolve with gl_FragDepth, but that wouldn't provide a multi-sampled depth buffer to the operating system.

As we venture into WebGPU, we again don't have the concept of an opaque framebuffer and instead require the user to set up a list of attachments to render into when creating render passes. See: https://gpuweb.github.io/gpuweb/#render-pass-encoder-creation

**Comment by magcius** [comment]
I've been told that the reason that GLES 3.0 doesn't support blitting to multisampled buffers is because some mobile chips only support multisampling in tiled memory, and you can't copy tiled memory, only resolve it.

From this perspective, in order to render multiple color attachments with the same depth buffer (something required for several effects that I've implemented), I would need to be able to steal the depth attachment from the opaque framebuffer and apply it to my own color buffers.

**Comment by toji** [comment]
This is definitely intentional, and this specific limitation is almost certainly not going to be lifted. **BUT**, it also is not intended to remain the only method of rendering to WebXR for very long.

First, the brief history lesson: VR, as a general rule, looks absolutely _awful_ without multisampling. So  we all agreed pretty early on that it was of utmost importance to ensure that was supported. Also, WebGL 2 is unevenly distributed and we didn't want to force people to use it for XR things on the Web (this has been improved a bit since that time, but there's still an unfortunate number of incompatible devices and Apple still doesn't support it at all.) WebGL 1.0, of course, doesn't support multisampling to anything but the default backbuffer. So we figured that we could either: Lobby for a whole slew of complicated new extensions to WebGL 1.0 to enable multisampled render to texture, which would in turn not be compatible with most people's existing WebGL 1.0 rendering pipelines OR cheat just a tiny bit and fake another "default framebuffer". 🤷‍♀ As you can tell we went with the latter because while it absolutely has annoying limitations it also matches the mental model for how many people use WebGL closely and allows a couple of nice implementation tricks to boot.

So that's the annoying present. Lets talk about the future:

We want to allow for far more flexibility as well as render paths that more closely mimic the underlying web and native APIs. To achieve this we're planning on introducing new layer types beyond `XRWebGLLayer` that can be used as the `baseLayer` (and eventually allow multiple layers to be composited as well.) For example: We want to introduce a layer that produces a swap chain of array textures instead of the opaque framebuffer concept for WebGL 2.0 (`XRWebGLLayer` is and will continue to be usable with WebGL 2.0) This would expose both the color and depth/stencil buffers as array textures, one element per view, and rely on the application to bind them appropriately for rendering. (We need to have the WebXR API produce the textures because that aligns with how the native APIs work and reduces overhead.) Not only will that allow more flexibility for the app but it would also allow us to take advantage of the [OVR_multiview2](https://www.khronos.org/registry/webgl/extensions/OVR_multiview2/) extension for more efficient rendering. (And yes, there's work in progress to allow multiview, multisampled rendering.

Similarly with WebGPU, the integration would be a new layer type that likely also be a [GPUSwapChain](https://gpuweb.github.io/gpuweb/#gpuswapchain), which would mimic normal WebGPU usage very well.

So, with all that said (and I do feel it was useful to type it out in one place for future reference) I'm going to close this issue, because the opaque framebuffer decision is not something we're really interested in re-evaluating at this point, I'd rather focus on enabling more new layer types faster.

**Comment by magcius** [comment]
New layer types that provide non-opaque framebuffers sound good. Thank you.
