### ISSUE TITLE
In some gfx APIs, depth/alpha/stencil are properties of the GL context, not the surface

### ISSUE THREAD

**Issue by asajeffrey** [immersive-web/webxr#899]
In WebXR, the depth, alpha and stencil attributes of the WebXR opaque framebuffer are independent of the attributes for the canvas. Some gfx APIs (notably WGL and EGL) do not support this, so this is a source of friction between WebGL/WebXR and the underlying GL implementation. It is not obvious how to implement WebXR on platforms where depth, alpha and stencil are properties of the context rather than the surface.

**Comment by toji** [comment]
I'm not sure if I'm clear on if this is limitation that actually affects WebXR? WebXR requires WebGL support, and WebGL is an implementation of OpenGL ES 2.0. OpenGL 2.0 supports depth/stencil in framebuffers via `glRenderbufferStorage()`, and that should be sufficient to implement the opaque framebuffer as described by WebXR? (Note that WebXR does not _require_ multisampling, but it's highly recommended that UAs implement it.)

**Comment by toji** [comment]
I'm not sure if I'm clear on if this is limitation that actually affects WebXR? WebXR requires WebGL support, and WebGL is an implementation of OpenGL ES 2.0. OpenGL 2.0 supports depth/stencil in framebuffers via `glRenderbufferStorage()`, and that should be sufficient to implement the opaque framebuffer as described by WebXR? (Note that WebXR does not _require_ multisampling, but it's highly recommended that UAs implement it.)

**Comment by asajeffrey** [comment]
The problem with renderbuffers is that they're not thread-safe, so we use whatever thread-safe surface API the platform provides. For WebGL this is fine, because the only surface that has to be thread-safe is the default framebuffer, and there's only one of those per context. For WebXR this is a problem, as we need the WebXR framebuffer to be thread-safe as well, since the WebGL thread that handles rendering is not the same as the WebXR thread that handles presentation.

**Comment by toji** [comment]
Thanks for the additional context! I wasn't familiar with that limitation of renderbuffers.

I still feel like this is workable for WebXR because the renderbuffer shouldn't be required to be used cross-thread. While we allow the depth buffer to be used by the compositor [if the content author allows it](https://immersive-web.github.io/webxr/#dom-xrwebgllayer-ignoredepthvalues), the compositor is not _required_ to make use of it, and as a result the renderbuffers can restrict their use to the main javascript thread since only the color buffer needs to be synchronized with the compositor.

**Comment by asajeffrey** [comment]
Yes, we could set things up so in the WebGL thread, we render into a renderbuffer (with depth info) then blit into a thread-safe surface, send the surface to the WebXR thread for presentation (which will normally mean another blit into the device). This does mean an extra blit though.

**Comment by toji** [comment]
I feel as though I'm missing an understanding of some key part of your architecture that would help me understand the concern better. Maybe if we could sketch out the high level architecture a bit more clearly?

My (almost certainly flawed) mental model is that you have two threads, each with it's own GL context (JS Main and WebXR Compositing). If the threads are within the same process, I would imagine that you'd set them up as part of the same share group, and as such texture handles and such should be relatively easy to pass back and forth, assuming you're being careful with your flush/finishes. Since many APIs provide you the texture(s) they would prefer that you render into via their own swapchain-like interface the ideal scenario is that you pass those API-allocated textures to the JS thread. Depending on the GPU/OS/available extensions multisampling may throw a wrench into that and force a blit no matter what, but maybe we're lucky and we can bind them directly as the framebuffer color buffer. After which we signal the XR thread that the rendering is complete and submit that texture into the API's presentation method. Fetch a new color buffer off the swap chain and repeat.

FWIW Chrome doesn't do that, as our rendering and compositing happen in different processes for sandboxing purposes. As such we are relying on platform-specific surface sync mechanisms to shuffle the output images back and forth from the GPU process to the XR compositor process. We're currently forcing at least one blit as part of this because it was easier to manage, but I don't think that's a hard limit for us and is simply a matter of allocating engineering effort to sharing the API swapchain-produced surfaces across processes to reduce the number of blits.

In any case, I'd love to get a better understanding of where my very handwavy musing of your potential pipeline are disconnected from reality so that we're not accidentally talking past eachother. :)

**Comment by asajeffrey** [comment]
Okay, the relevant bit of the architecture is that there's three threads: the JS thread, the WebGL thread and the WebXR thread. The JS thread lives in its own process and has no GL context, but communicates via IPC with the other two threads. The WebGL thread has a GL context, and is responsible for rendering WebGL commands. The WebXR thread has a different GL context, and is responsible for presenting the GL images to the device.

Our first shot at this was using GL texture sharing, having the two contexts share GL objects and use GLSync objects to synchronize the accesses to texture data. The problem we hit with this approach is that drivers were not thread-safe, and we were seeing unexpected behaviour. Also, not all platforms (notably MacOS) support multithreaded texture sharing, so we ended up having to use readback via main memory, which was unusably slow.

So rather than texture sharing, we're now using surfaces, which are implemented differently on each platform, e.g. using `IOSurface` on MacOS. This works, and is fast and reliable, but on some platforms (e.g. WGL and EGL) surfaces do not have independent depth/stencil/alpha, and instead inherit them from the producer context (in this case the WebGL context). Which is where we came in :)

I hope this helps!

**Comment by toji** [comment]
> I hope this helps!

Immensely, thank you! Interestingly this means that it's extremely similar to Chrome's architecture.

**Comment by asajeffrey** [comment]
Not too surprising :) Do you know how Chrome gets round this issue?

**Comment by toji** [comment]
We're doing a blit. 😅 Additionally, though, we only have the compositing pipeline set up on Windows and Android. For Windows we're bouncing through a D3D11 context for the texture IPC, which I think is more flexible than WGL and might allow us to skip the blit, we just haven't dug into it very deeply.

**Comment by klausw** [comment]
Chrome's WebXR implementation also supports a shared buffer mode that removes a blit. In that mode, the opaque framebuffer is backed by a cross-process shared image based on Chrome's GpuMemoryBuffer abstraction. That's currently only used on Android using AHardwareBuffer-backed GpuMemoryBuffer objects, but other platforms have their own GpuMemoryBuffer or shared image flavors as far as I know.

See https://cs.chromium.org/chromium/src/third_party/blink/renderer/platform/graphics/gpu/xr_webgl_drawing_buffer.cc?l=278&rcl=92f2c1471e2cc54b72813e6856055ed065f20c2e for an example of the code setting this up in Blink.

The CHROMIUM extension used for that is documented here: https://cs.chromium.org/chromium/src/gpu/GLES2/extensions/CHROMIUM/CHROMIUM_shared_image.txt

The shared image needs to be used together with an appropriate cross-process-transportable GL fence, in this case a GpuFence: https://chromium.googlesource.com/chromium/src/+/HEAD/docs/design/gpu_synchronization.md

**Comment by klausw** [comment]
BTW, my description above assumes you're doing cross-process image transport, as used in Chrome. If it's multiple threads within the same context, it potentially gets easier, i.e. plain GL fences should work for synchronization if you are using contexts in a share group.

**Comment by asajeffrey** [comment]
That's pretty similar to servo's setup. The cross-platform shared buffers are `Surface`s in https://github.com/pcwalton/surfman, but the problem we've hit is that on some plaforms, the depth/alpha/stencil attributes are per-context, not per-surface. Android isn't one of the affected plaforms though.

It's unfortunate that the WebXR API design requires an extra blit, due to opaque framebuffers sharing a WebGL context which may have different depth/alpha/stencil attributes.

**Comment by toji** [comment]
Coming back around to this 7 months and one pandemic later. Sorry for the gap! It's just a tricky issue to reason through.

First off, I think it's worth stating that I feel like allowing the format of the XR framebuffer to differ, at least in declaration, from that of the default framebuffer is important. For example, frequently content on the page is content to operate without an alpha channel but when you switch to rendering in AR having an alpha channel is pretty much a necessity. 

A potential way to work with any platform limitations that arise could be to approach the framebuffer allocation similarly to how Chrome handles alpha channels on certain intel architectures: It's a known issue that buffers allocated without an alpha channel perform significantly slower than those that have one, even if the alpha component is never used. As such, we have a path that allocates RGBA all the time and uses some internal masking tricks to prevent the alpha component from ever being anything other than 1,0. I'd be mildly surprised if Firefox didn't have a similar path already in place, and would guess that Servo will bump into the need for such a thing at some point. Given that we're told at content creation time that the context needs to be XR compatible, (or at least given the opportunity to lose and recreate the context when that attribute is set) perhaps it's worthwhile to simply allocate the framebuffer with alpha implicitly enabled and masked for the default framebuffer in anticipation that XR may need alpha as well. (Ideally depth/stencil isn't an issue here because communicating those to the compositing thread is optional.)

Of course, introducing a blit may be simpler than state manipulation shenanigans. In that case, I don't think there's any harm in having the browser issue a console warning to developers stating that using different buffer properties between the default framebuffer and XR framebuffers may result in degraded performance. It's not ideal, obviously, but in the event that a blit ends up being required it's a reasonable approach to try and nudge devs back onto the fast path.

Finally, while I feel like we may be a bit too late to do much for this particular interface we have an opportunity to take another crack at it both with the upcoming [more generalized layers module](https://immersive-web.github.io/layers/) and with WebGPU integration further down the line from that. It's my hope that the structure of those APIs won't necessitate the same sort of considerations as we've been going over in this thread. Please take a look when you have the time and let us know what you think!

**Comment by asajeffrey** [comment]
I think I can see how to do this now, by always using contexts and surfaces with alpha/depth/stencil, and then faking layers that don't have those in WebGL by using appropriate masks.

The layers API helps, but it's still non-trivial because the layers API requires textures to be `GL_TEXTURE_2D`, but the textures we get from surfaces on MacOS are `GL_TEXTURE_RECTANGLE`s. I think I can see how to get round this by allocating `GL_TEXTURE_2D`s on the WebGL thread, then doing the compositing into a surface on that thread, and shipping the surface to the main GUI thread for display. This is still guesswork though.

**Comment by cabanier** [comment]
Is there anything that we can do in the WebXR Layers spec to make you life easier?
We still need to define exact texture behavior so we can add constraints if needed.

**Comment by toji** [comment]
Sounds like we can close this issue, then? Feel free to let me know if you think there's more to discuss and we can re-open.
