### ISSUE TITLE
Clean up XRFrame's animationFrame boolean

### ISSUE THREAD

**Issue by lojjic** [immersive-web/webxr#905]
Originally from PR #903 -- converting to an issue due to IPR policy and to allow for alternate solutions.

XRFrame currently defines an `animationFrame boolean`, which is checked during calls to `getViewerPose`. It is initially `false`, and is set to `true` in the `XR animation frame` algorithm. However it is never set back to false.

@toji correctly pointed out that the current logic will still result in the expected `InvalidStateError` if `getViewerPose` is called outside the animation frame, due to its companion `active boolean` having similar logic, so perhaps the `animationFrame boolean` is redundant and could just be removed. But if it's there as a hook for future algorithms to rely on, then it's probably best to define it being returned to `false` at the end of the frame.

**Comment by lojjic** [comment]
Upon further reflection, the algorithm as is makes sense if the intent of the `animationFrame` boolean is to distinguish an `XRFrame` instance's _provenance_ rather than current timing -- "this `XRFrame` was created during an animationFrame" vs. "we are currently in an animationFrame." In that case it's sensible to leave it set to `true` after the frame callback completes since it remains an accurate description of where it was created.

(I wasn't able to see that interpretation before because it depends on new `XRFrame` instances being created each place they're used (frame callbacks, `select*` events, etc.), which is not currently the case in the webxr-polyfill where I was looking into this behavior. In that polyfill a single `XRFrame` instance is shared across all frame and event callbacks fired by an XRSession, which is pretty clearly a bug on its own.)

**Comment by toji** [comment]
> Upon further reflection, the algorithm as is makes sense if the intent of the animationFrame boolean is to distinguish an XRFrame instance's provenance rather than current timing

That is indeed the intent of the boolean, as an XRFrame is effectively either an animation frame or not for it's entire lifetime. It won't hurt anything to set the boolean to false after it's no longer active, but that's can't be observed in any way either.

>In that polyfill a single XRFrame instance is shared across all frame and event callbacks fired by an XRSession, which is pretty clearly a bug on its own.

Agreed. Filed https://github.com/immersive-web/webxr-polyfill/issues/114 in response.

Since there's no functional changes that need to be made to the spec here, I'm going to close this. Thank you for raising the question and validating the behavior, however, as well as identifying the polyfill issue!
