### ISSUE TITLE
"ensures an immersive XR device" is being used in weird ways

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#909]
https://immersive-web.github.io/webxr/#ensures-an-immersive-xr-device-is-selected talks about "context object's immersive XR device", where the latter links to <https://immersive-web.github.io/webxr/#xr-immersive-xr-device>.  That seems to assume that the "context object" is an "XR" instance.  But this algorithm is called into from places where the "context object" is `HTMLCanvasElement` (e.g. the `getContext` modifications) or where there is no "context object" at all (the various parallel sections).

**Comment by kearwood** [comment]
Perhaps some indirection is not being well articulated in the spec text.

In this case, rather than the "context object" having an "immersive XR device" directly, the "context object"'s relationship with the "immersive XR device" is due to the physical connection of the headset plugged into a video card that is associated with the WebGLContext's GPU.

Of course, replacement text would need to be written in a way that doesn't assume that the headset is external to the computer (eg, it can be a stand-alone headset with no separate computer).  It is also possible that the connection between the headset and a computer is wireless.

**Comment by bzbarsky** [comment]
Right, the point is I would like the spec to define which exact "immersive XR device" is meant and how it's related to the place where it's trying to be used.

(e.g. I don't see anything preventing there being multiple headsets involved too, right?)
