### ISSUE TITLE
What happens in getContext if there is no immersive XR device?

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#910]
If after "Ensure an immersive XR device is selected" the immersive XR device is null, what should happen?  Should the result still return a WebGL context with the "XR compatible" boolean set to true?  That seems pretty odd, but is what's specced right now...

**Comment by toji** [comment]
That's an acceptable behavior, because when an immersive XR device is selected (for example, is connected after the context is created) it should trigger the algorithm to [select an immersive device](https://www.w3.org/TR/webxr/#select-an-immersive-xr-device) (which I'm aware you have separate issues with, but I am sadly a single-core entity and cannot respond to issues in parallel). That algorithm will force the `XR Compatible` flags of any existing contexts to `false`.

So it doesn't make much difference what it's set to initially in that case. I do think there's an argument to be made that setting it to false in the case of a null device may read more clearly, though.

**Comment by bzbarsky** [comment]
I guess it just confused me that I can get a context with the "XR compatible" boolean set to true when there are no immersive devices to be had at all.  That, and the behavior difference with `makeXRCompatible`, which sets the boolean to false if there are no immersive XR devices.

**Comment by toji** [comment]
It's a legitimate concern, and a simple enough change that I think we should just do it.
