### ISSUE TITLE
makeXRCompatible doesn't specify what task source its task uses

### ISSUE THREAD

**Issue by bzbarsky** [immersive-web/webxr#912]
https://immersive-web.github.io/webxr/#dom-webglrenderingcontextbase-makexrcompatible step 1.8 says nothing about the task source.  It should.  It should also say something about the document association.

This is a general problem through the whole spec: none of the task bits say what sources are used.

**Comment by toji** [comment]
This is an area that I'm unfamiliar with, so thanks for bringing it to our attention.

Given that this specific task deals with modifying and inspecting the internals of the WebGL context, it seems like the [WebGL Task Source](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.15) would be the appropriate one to use? If not that then it seems like the generic [DOM manipulation task source](https://html.spec.whatwg.org/multipage/webappapis.html#dom-manipulation-task-source) could maybe be applicable if you squint really hard, but otherwise perhaps we just need a new WebXR-specific source. Other tasks throughout the spec will also have to be evaluated individually to see which task sources would be most applicable.

For the sake of the editor's education, do you know of any resources that describe the reasoning behind task source selection? The spec is fairly dense and while the generic sources outline what each should be used for it's not entirely clear to me why they shouldn't all be in one big task queue. I'm sure there's a very good reason for it that I'm missing the background for.

**Comment by bzbarsky** [comment]
> do you know of any resources that describe the reasoning behind task source selection

I am not aware of anything offhand.  @annevk @domenic do you know of anything?  I agree that this is a problem....

> it's not entirely clear to me why they shouldn't all be in one big task queue

Primarily because this allows the UA to schedule them independently, which gives the UA more flexibility in terms of what it prioritizes (e.g. in the case of the generic task sources the "user interaction" task source can be treated as higher priority than the others).

**Comment by domenic** [comment]
There are no good resources on this, but there should be. Adding such a guide is somewhere on my long backlog.

I guess my general advice would be, are there any relevant constraints that should be imposed? E.g. if some other Web GL operation queues a task, then WebXR does, do you care that those run in FIFO order? Or can the UA reorder them? You might gain some insight into this by inspecting existing WebXR or WebVR implementations and which task sources they use in their implementation.

If there are no relevant constraints, then minting a new task source would give the most flexibility.
