### ISSUE TITLE
Input (mouse/keyboard) behavior while presenting

### ISSUE THREAD

**Issue by mkeblx** [immersive-web/webxr#93]
When in a VR headset you can't see your hands or monitor but may want to use the keyboard and mouse for input which can be a challenge, leading to problems of losing input if click outside window unintentionally, etc. A difference in handling of these standard inputs when presenting in VR could make a lot of sense. 

Note that there is probably a significant difference in how would handle depending on `hasExternalDisplay`, i.e. for a desktop system with the VR headset as an external display would want to support scenarios where 2D webpage can still be interacted with as normal for another user at the keyboard.

What should happen? Should nothing different specifically happen, leaving end developer to handle with things like [pointerlock](https://www.w3.org/TR/2016/PR-pointerlock-20160830/)?

**Comment by toji** [comment]
I've generally assumed that developers that want keyboard/mouse input in VR would be using pointerlock, since that gives devs the flexibility to decide if and how they want to restrict the cursor. (Pages with an external "Demo giver's" UI won't want it. A flight simulator would.) Keyboard focus is an interesting question, but I'm not sure how much can/should be done to prevent it from escaping. Seems like an abuse vector.

**Comment by brianchirls** [comment]
I agree with @toji on this one. Yes, I imagine it could be an abuse vector. And there is no standard behavior to enforce - most of the native Oculus stuff I've seen that uses the keyboard or mouse completely fail at this.

For a Web VR experience that requires mouse or keyboard, I can imagine using pointer lock and/or full screen, and/or pausing the experience and showing an in-headset warning if the browser window/tab loses focus.

**Comment by toji** [comment]
This issue was moved to immersive-web/webvr#16
