### ISSUE TITLE
Use a longer name for the XR interface?

### ISSUE THREAD

**Issue by toji** [immersive-web/webxr#936]
This issue courtesy of a day's worth of debugging time from @NellWaliczek, thanks!

In Nell's scenario she was attempting to use the WebXR Polyfill on a page which happened to use a minified library which just so happened to select `XR` as the name of one of its minified globabl functions. This added the `XR` function to `window`, which then conflicted with trying to polyfill the `XR` interface and subsequently caused the polyfill to fail. That specific failure has been fixed in the polyfill, but even in native implementations the accidental overwriting of the `XR` interface could cause some minor issues, primarily for tests, polyfills, or extensions.

For example, a script that tests to ensure that `navigator.xr` is available and of the right type may call:

```js
if (navigator.xr instanceof XR) {
  //...
}
```

Which would fail if the `XR` interface had been accidentally replaced (though calls to `navigator.xr` will continue to function normally.)

This leads to the question of if we should potentially rename the `XR` interface to something longer to avoid potential conflicts. For example: `XRNavigator` or `XRSessionManager`. This would potentially cause some _very_ minor backwards compat issues, but since most pages are expected to only interact with the `navigator.xr` instance changing the interface name should leave 99.999% of WebXR code intact. The question is if we feel like the potential for such a short name to conflict with minified libraries is enough of a problem for us to bother with a change.

(To be clear: I am **not** suggesting that the `navigator.xr` object be changed, since that would be a major backwards compatibility break on a now-shipped API.)

**Comment by Manishearth** [comment]
We can also, for the time being, ship XRSessionManager with `window.XR = XRSessionManager`, and deprecate it.

**Comment by nbutko** [comment]
+1

**Comment by nbutko** [comment]
XrSystem might be a good choice.

**Comment by nbutko** [comment]
It's worth noting that previous versions of 8th Wall XR were added to the window as window.XR.  We have since moved this to window.XR8 to avoid conflicts with the currently proposed window.XR, and all of our documentation and examples have been updated to use window.XR8.  However, there are still an unknown amount of existing customers and software that refer to our deprecated API, and our library still writes window.XR (with a deprecation warning getter) to support these customers.

As a common web idiom, third party libraries are usually installed on the global scope as window.ALLCAPSCASE, for example window.THREE, window.AFRAME, window.BABYLON and in our historical case, window.XR. It would be nice to see if there is some sort of thought or consensus around avoiding window.ALLCAPSCASE for new W3C apis (reserving them for third party use). It looks like prior to window.XR, there were exactly 4 (of roughly 1000) window properties that were ALLCAPSCASE: 

```
Object.getOwnPropertyNames(window).filter(p => p.match(/^[A-Z]+$/)).filter(p => p !== 'XR')
(4) ["JSON", "URL", "CSS", "USB"] 
```

Of these, USB is experimental and recently added.
