### ISSUE TITLE
Browser not supported 

### ISSUE THREAD

**Issue by rohanbhatia-nag** [immersive-web/webxr#951]
I am trying to run webxr AR on chrome 76 but the browser says unsupported browser. I have enabled all the XR related flags of chrome. I am using Samsung Galaxy Tab S4 which is an ARCore enable device. Please let me know what am i missing out on.
Thanks

**Comment by DsRQuicke** [comment]
Hi,
I'm not 100% sure, but you might also still need an origin trial in Chrome 76 to use the AR module.

I would suggest that, if possible, you upgrade your chrome version (or try the developer version of Chrome), and see if your code works there.

**Comment by klausw** [comment]
Chrome 76 is old. Try current stable v79? Earlier versions required Android O and may be outdated in other respects also. There's no longer any origin trial, these have expired now that WebXR VR mode has launched to stable. (AR still needs flags).

FYI, this issue tracker is intended for the specification itself, not specific implementations in browsers. However, there's unfortunately still a lack of good general resources. You could try https://crbug.com for Chrome issues, but since there's no way to make fixes in versions other than current stable releases the likely response would be to ask to upgrade. Or stack overflow with a [WebXR] tag, but that is intended for specific coding questions and not a good forum for "it's not working" issues. @AdaRoseCannon , would it help to add a FAQ at https://immersiveweb.dev/ and maybe link to that in a "new issue" template in this repo?
