### ISSUE TITLE
Add a type property to XRReferenceSpace

### ISSUE THREAD

**Issue by a2sheppy** [immersive-web/webxr#954]
It seems to me both as someone documenting WebXR and someone trying to write code using WebXR that it would be useful if there were a `type` property on the `XRReferenceSpace` interface:

```
readonly attribute XRReferenceSpaceType type;
```

This would make it easier to write code that needed to support multiple reference space types, either because of fallback space support or because it's generic library code that needs to work in various spaces yet needs to handle things differently (especially in bounded vs unbounded cases).

**Comment by Manishearth** [comment]
I can't find where this was mentioned but a lot of such things were removed last year because "we shouldn't expose data that the user already has". E.g. the session mode, the reference space type, etc. Both of these are things that the user set when requesting, and can pass around if they want. This may be a TAG guideline, I'm not sure.

**Comment by a2sheppy** [comment]
How is exposing the reference type a concern, though? Is it really something user-specified (beyond choosing whether they want an immersive versus an inline mode, which would impact the reference space type chosen, but not to the extent that it's giving anything crucial away)?

From a sheer perspective of data encapsulated and object-oriented design, it seems very odd that a crucial piece of the puzzle around the behavior of the reference space can't be accessed from the reference space object, especially when you need to know the type in order to properly render content if the scene could be getting rendered in one of  more than one space types.

While it's true that the type _could_ be stored and passed around separately, it would  be substantially more efficient and consistent with OOP practices to not have to do so.

**Comment by Manishearth** [comment]
Aha, it was done here: https://github.com/immersive-web/webxr/issues/513

I think in typical usage you only have one reference space in your application, so it's easy to store this info.

**Comment by toji** [comment]
While developing the spec I consulted frequently with @bfgeek about API ergonomics, to try and ensure WebXR meshed with the web platform as a whole. One of the principles that came out of those conversations was exactly what @Manishearth stated: we shouldn't expose data that the user already has access to.

This manifested as the removal of several similar properties throughout the API, and in this specific instance meant dropping an explicit `type` attribute. The logic is that the developer is the one that requested the reference space, and the user agent has no freedom to deliver them something other than what they asked for, so simply restating a value passed into a constructor didn't hold much value. If that information is important to the developer, Javascript allows them to easily add it at runtime like so:

```js
let referenceSpace = await session.requestReferenceSpace('local-floor');
referenceSpace.type = 'local-floor';
```

To be honest I personally did find it convenient when we had that type data as part of the API, but not so much so that I felt it was worth pushing back on established web platform patterns to keep.
