### ISSUE TITLE
Visibility state behavior is not clearly specified for inline sessions

### ISSUE THREAD

**Issue by cabanier** [immersive-web/webxr#956]
From reading the spec, it is unclear what events should trigger on inline session.
For head mounted devices, should inline session become hidden when going immersive?
Should inline sessions be marked as hidden when they scroll out of view?

**Comment by Manishearth** [comment]
On one hand I feel like it would be weird for a specific 2D web API to have this, I don't see inline sessions as very different from other 2D web systems (like canvas). Also, https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API exists.

On the other hand it's weird for us to have this attribute on inline sessions but not do anything with it.

**Comment by cabanier** [comment]
> On the other hand it's weird for us to have this attribute on inline sessions but not do anything with it.

I agree. I suspect that some content might break if we start firing the right events on the inline session (ie some experience might stop media playback if the session is hidden)
The spec should call out what to do with inline sessions. Right now it implies that they should get the events.

**Comment by Manishearth** [comment]
Oh hmm. Perhaps we should declare that these events don't exist for inline sessions, and the attribute is null.

**Comment by cabanier** [comment]
I would support that change.

**Comment by AdaRoseCannon** [comment]
Is this still wanted for the call, I can't find the orignal comment which added the label?

**Comment by cabanier** [comment]
Yes. I deleted the comment since al it had was the agenda label.

**Comment by AdaRoseCannon** [comment]
Cool, thanks! in the future you can add some text after '/agenda' to say what you want to get out of the cool and it will be included in the agenda notes.

**Comment by AdaRoseCannon** [comment]
Is it okay if we delay this til next week? there is currently nothing else on the agenda.

**Comment by cabanier** [comment]
Possibly. I'm going to file another issue today so there will be at least 2 :-)

**Comment by toji** [comment]
After discussing on the call today, it looks like there's two general approaches that can be taken here, neither of which received strong opposition:

 1. As Manish said above, we could update the spec to state that `inline` sessions do not fire `visibilitystatechange` events and the `XRSession.visibilityState` attribute would be changed to report some sort of `null`-like value. Note that actually making it nullable requires a minor IDL change, but also that it's ever so slightly weird to have a nullable enum, so instead we may want to introduce an additional enum value along the lines of `inline` or `page` to indicate that developers should defer to the [Page Visibility API](https://www.w3.org/TR/page-visibility/) to determine if the page, and thus the inline session, are visible.
 2. As I suggested on the call, we could instead spec that `inline` sessions continue to report `visibilitystatechange` events and the `XRSession.visibilityState` attribute, but make it explicit that these just mirror the page visibility state. This may be nice for some developers because it means that this API can be referred to consistently for both `inline` and `immersive` sessions, and it also requires no IDL changes. But it also means that we're basically surfacing another place to get the same data as the Page Visibility API in the `inline` case, which feels like a bit of an anti-pattern.

Neither case strikes me as particularly problematic, though if I were forced to choose I'd have a slight preference for option 2. A straw poll on the call indicated that most participants felt relatively neutral about it and the individuals who did express an opinion were pretty evenly balanced between both approaches. As such we're putting both approaches up in this issue to see if there's any external feedback to be gathered outside of the call.

We'll probably make a decision one way or the other within a week or so, even if there's no additional feedback. Either outcome is workable, so it may come down to a simple matter of the preference of whoever puts together a PR.

**Comment by cabanier** [comment]
Thinking about it some more, I prefer the simplicity of option 1 and never change the status for inline session and leaving it up the UA to decide when to fire the raf.. 

If we go with something like option 2, we should update the spec specifically for inline session because:
- Even on headset, we don't change the page visibility state so inline sessions would still be marked as visible even though they won't run raf and aren't visible.
- visible-blurred should be set if the element does not have focus. Does that make sense for inline sessions?
- Chrome currently marks inline sessions as hidden if the tab is not in focus (= the session stops if you click outside the window)

**Comment by cabanier** [comment]
@toji I believe we decided on the call to go with option 2.
When should we update the spec to make that clear?

**Comment by Manishearth** [comment]
Make a PR? I also recall us mostly choosing to go with 2.

**Comment by toji** [comment]
Yes, I agree. Let's go with #2.
