### ISSUE TITLE
Chroma Key on VideoNode

### ISSUE THREAD

**Issue by brazaoo4** [immersive-web/webxr#957]
Hi, I'm working on a project where I need to play videos and remove the green background (example below) but I can't seem to find anything related to this (only found stuff where they use canvas, but I can't use that since I'm on an AR session).  I'm using VideoNode to play the video.
Does anyone have an idea on how I could achieve this? Any help is appreciated, thanks in advance!

![Screenshot_20200204-173411](https://user-images.githubusercontent.com/52158560/73770964-473ac100-4775-11ea-881f-e0176d7642c7.jpg)

**Comment by klausw** [comment]
Assuming this is using DOM Overlay in immersive-ar mode, the expectation is that transparency for DOM elements is respected, but green isn't transparent, so I think the components are all working as expected.

Can you preprocess the video to use actual transparency instead of green? I haven't tried this myself, but according to https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video this should be possible?

Alternatively, I think you could use the video as a texture and do color replacement in a shader.

If there aren't any alternatives that work, and if this is a common use case, I think it would be worth revisiting if there should be direct chroma key support, but that may be more difficult, and it may be more appropriate at a layer other than WebXR.

**Comment by mkungla** [comment]
> Can you preprocess the video to use actual transparency instead of green?

I would say that this is not something to even consider as part of WebXR Device API.
For particular case video should be either preprocessed or use something like https://github.com/brianchirls/Seriously.js as middleware.

**Comment by klausw** [comment]
> (only found stuff where they use canvas, but I can't use that since I'm on an AR session)

WebGL-based methods should continue to work normally in an immersive-ar session. As usual, you need to draw to the XRSession's baseLayer.framebuffer via `gl.bindFramebuffer` to have output showing on the AR output device (instead of the default framebuffer for content that would normally be displayed in the canvas), but your library/framework should already have that set up for you.

**Comment by cabanier** [comment]
@Manishearth should we close this topic since it doesn't apply to WebXR?
