### ISSUE TITLE
Add a `refreshRate` getter

### ISSUE THREAD

**Issue by a2sheppy** [immersive-web/webxr#963]
There are a few scenarios in which it would be useful to be able to determine what the refresh rate of the XR device is, through a `refreshRate` getter on either `XRSystem` or `XRWebGLLayer`, depending on how it makes the most sense to implement it.

IMHO the biggest and best reason it would be useful to be able to determine the refresh rate of the display (60 Hz, 90 Hz, 120 Hz, whatever) is this:

To allow the app to configure the renderer based on the estimated time available to render each animation frame. Think of all those games that let you adjust graphics options that also have an option to automatically adjust the settings for your hardware. Having an estimated refresh rate available would make it possible to tune things like the FPS cap, texture size, color depth, and even select models of different poly counts based on how fast each frame needs to be produced.

This information could also be used to let a renderer do something like this in their renderer:

```
let now = performance.now();
let renderHalfTime = now + (xr.refreshRate * 0.4);
let renderFinalizeTime = now + xr.refreshRate * 0.8;

renderCharacter(player);
renderVisibleCharacters();
renderObjects({quality: qualityBest, minDepth: 0, maxDepth: 25});
if (performance.now() > renderHalfTime) {
  renderObjects({quality: qualityLow, minDepth: 25, maxDepth: 50});
} else {
  renderObjects({quality: qualityMedium, minDepth: 25, maxdepth: 50});
}

if (performance.now() > renderFinalizeTime) {
  renderObjects({quality: qualityMinimum, minDepth: 50, maxDepth: 75});
} else {
  renderObjects({quality: qualityLow, minDepth: 50, maxDepth: 100});
}
```

Something along those general lines, anyway. Adjusting the output as you go based on the performance you're getting from the system and the refresh rate.

By using a combination of a routine that estimates system performance and the frame rate, along with knowledge of how complex your imagery is, you can tune your graphics engine accordingly. This would be a huge quality of life win for users but also for developers.

**Comment by cabanier** [comment]
This seems like a reasonable request. 
It seems that this should also apply to regular webgl sessions and it might be more appropriate to have it as a general property. 
Was this ever proposed? If so, it would be good to know why it was rejected.

**Comment by klausw** [comment]
That proposed render loop wouldn't work as expected. If the `renderObjects` call submits WebGL commands, a typical implementation just adds them to a command queue, it doesn't wait for them to complete. You'd need to use `gl.finish()` to wait for completion, but that's not recommended since it introduces render pipeline bubbles. (AFAIK Chrome actually treats `gl.finish()` as `gl.flush()` internally and doesn't wait.) On mobile GPUs, it's quite common that the previous frame is still finishing rendering while you're sending draw calls for the current frame in the rAF callback.

Apart from that, most modern GPUs don't really execute draw calls as sequential steps, they reorder them and do other optimizations that have the same end results. Mobile GPUs often use tiling to work on sub-rectangles at a time.

Instead of doing estimates on the current frame's rendering, you'd want to collect timing information for previous frames, and use that to tune rendering for the current frame. For some architectures, even the previous frame may not be complete yet, and you'd only have information from two frames back.

While I'm not opposed to providing the refresh rate, it's somewhat tricky to use this correctly in applications. The refresh rate may not be constant, and may also be different from the recommended rendering rate. If I remember right, PSVR often runs applications at 60fps with a 120fps display refresh, using reprojection to fill in every second frame.

See also https://github.com/immersive-web/webxr/issues/347 which discussed this in more detail, including a XRFrameTiming proposal: 

```webidl
// WARNING! NOT ACTUALLY BASED ON API RESEARCH!
interface XRFrameTiming {
  readonly attribute DOMHighResTimeStamp frameStart;
  readonly attribute DOMHighResTimeStamp targetFrameDuration;
  readonly attribute unsigned int droppedFrames;
}
```

**Comment by klausw** [comment]
And just to make things more complicated, even a "the previous frame took N milliseconds to render" counter wouldn't necessarily be useful. Mobile GPUs generally do very aggressive clock speed adjustments to save power, so it's entirely possible that you'd get a roughly 16ms time on a 60fps display for a wide variety of quality settings due to the GPU adjusting itself to match the work required, until you suddenly start dropping frames as it runs into limits.

It would be nice if WebXR could report a value such as "fraction of available render budget used", but I don't know how feasible it would be to surface this information.

**Comment by cabanier** [comment]
> And just to make things more complicated, even a "the previous frame took N milliseconds to render" counter wouldn't necessarily be useful. 

Yes, performance timing is a very hard problem to solve. Even native apps give the user options.
If we just provided the refresh rate, could the author determine that the scene is too complicated by measuring the time between Raf callbacks?

>  If I remember right, PSVR often runs applications at 60fps with a 120fps display refresh, using reprojection to fill in every second frame.

For such systems, `refreshRate` should return the lower fps.
Typically, the system will infer the missing frame using the depth buffer.

**Comment by a2sheppy** [comment]
It occurs to me that not only could this be useful for WebGL, but could potentially have other use cases as well, and might even make sense to put it all the way out in the [`Screen`](https://drafts.csswg.org/cssom-view/#the-screen-interface) interface, though WebGL would likely be just about as good a place.

@klausw is right that the pseudocode I posted wouldn't really work. I meant it more as a way to make a point than to actually suggest it as a specific algorithm that might be used. Sorry for that confusion!

The points about the variations and whatnot that can occur makes me wonder... would it instead make sense to offer something with some set of values you can capture about the performance of the WebXR environment, both for testing but also to provide the ability to make useful adjustments to algorithms, offer user agency in configuring the engine, etc.


```
dictionary XRStatistics {
  /* Renderer statistics */
  unsigjned long droppedFrames; /* the number of dropped frames this session */
  unsigned long lastRenderTimer; /* how long the last frame render took */
  unsigned long minRenderTimer; /* the shortest time it took to render a frame */
  unsigned long maxRenderTimer; /* the longest time it took to render a frame */

  /* Frame rate statistics */
  unsigned double minFrameRate; /* the lowest frame rate recorded so far */
  unsigned double maxFrameRate; /* the highest frame rate recorded so far */
  unsigned double medianFrameRate; /* the median frame rate overall */
}

partial interface XRSystem {
  readonly attribute XRStatistics? statistics;
  attribute boolean statisticsEnabled = false; /* toggles stats gathering overall on/off */
  attribute boolean renderStatisticsEnabled = false;
  attribute boolean frameStatisticsEnabled = false;
};
```

With really even just a few bits of data like these, the app gains a great deal of power to make intelligent decisions or advise the user about changes they make to the settings, such as providing a warning icon if they try to crank settings higher than are likely to work.

**Comment by klausw** [comment]
I agree that it would be useful to have more data available here, but I'm unsure what would be the best way to expose it.

WebGL implementations can support the [EXT_disjoint_timer_query](https://developer.mozilla.org/en-US/docs/Web/API/EXT_disjoint_timer_query) extension, but according to [this test page](https://www.khronos.org/registry/webgl/sdk/tests/conformance2/extensions/ext-disjoint-timer-query-webgl2.html?webglVersion=2&quiet=0&quick=1) it's not reporting any values on my Android phone. 

I'd still be in favor of exposing a render load ratio, something along the lines of `avg_render_time * current_GPU_clock / max_GPU_clock`, but I assume this would need to be handled with care to avoid timing attacks or related information leaks.

**Comment by cabanier** [comment]
> I agree that it would be useful to have more data available here, but I'm unsure what would be the best way to expose it.

We should expose as little as possible. Some of @a2sheppy 's proposed idl could be calculated by the JS framework.
Desired framerate is easy to return from the UA so I think that's an easy win with not much information leakage. 
Dropped frames could also be useful but maybe authors could detect this already.

**Comment by a2sheppy** [comment]
I suppose yeah, realistically, just having some kind of "here's a number that tells you how well you're hitting your frames" figure would be good, regardless of what that number is. Beyond that, it would just be icing on the cake.

**Comment by toji** [comment]
We've talked about similar values in the past, as suggested by the thread that Klaus linked (#347). Unfortunately that's missing some of the follow up discussion that we had that caused us to drop the idea for the time being, much of which I think is still relevant today. I'll try to give a quick recap:

The number one issue we face with any API like this is simply identifying which numbers we can confidently expose across all the known native APIs we want to make use of, and evaluating how useful those will actually be for developers. Last time we discussed this I recall that the single common value I could find was "framesMissed", which simply indicated how many times the XR device had to reproject your content since the last frame. This seemed like it could be useful, but after looking at the OpenXR spec it's not clear that it has a mechanism for reporting even that.

Additionally, there's complication regarding how to differentiate between the highest available framerate for the hardware vs the most stable one for your content. Oculus Quest/Go can render at 72Hz, but will fall back to a steady 60Hz if you're not making framerate, and that's OK! PSVR does something similar because 120Hz is unrealistic for most content, even though the headset can technically support it.

To be clear, I would love to deliver more useful information to developer regarding performance. If we can work out what that should look like in this thread then that fantastic! It's a bit more complicated than it might seem at first glance, though, which is why we don't have it already.

**Comment by cabanier** [comment]
> Additionally, there's complication regarding how to differentiate between the highest available framerate for the hardware vs the most stable one for your content. Oculus Quest/Go can render at 72Hz, but will fall back to a steady 60Hz if you're not making framerate, and that's OK! 

Actually, it's not great if you can't render at the full refresh rate. Yes, it will reproject but animations will run slower and you will see weird black artifacts at the edges.

> To be clear, I would love to deliver more useful information to developer regarding performance. If we can work out what that should look like in this thread then that fantastic! It's a bit more complicated than it might seem at first glance, though, which is why we don't have it already.

The target framerate is an easy to understand value that is readily available to UAs. I doubt that a more complex performance oriented API will be better.

**Comment by Maksims** [comment]
In reality, stable framerates are rarely a thing, and the way most applications go around it, is to calculate variable delta time based on timings of previous frame.

This ensures that time based logic will behave well on higher and lower framerates, regardless of performance and hardware capabilities.

Although one use case I can see for access to platform maximum refresh rate - is when fixed delta time used. Quick example would be some implementations of GPU based particles, where each simulation is performed for fixed delta time. So if such system designed with fixed delta time of 60Hz (16.66ms), and then it runs on 72Hz platform, we have issue where some frames we should run simulation twice and some frames skip it completely. This leads to stutters.

**Comment by bjornbytes** [comment]
It seems like there are 2 things being discussed here:

- Rendering performance stats: Approximately how long it's taking to render frames, and whether you're causing frame drops/reprojections.
- Display refresh rate: A static property of the display hardware indicating the rate at which it presents new images.

I think (1) is kinda difficult to get right (as the discussion here indicates), but I've found (2) useful for making rendering decisions, especially when you're on a display that supports multiple refresh rates.

OpenVR, OVR, and VrApi all expose the display refresh rate.  On displays that support multiple refresh rates (Oculus Go, Valve Index), an array of supported refresh rates can be queried (`VRAPI_SYS_PROP_SUPPORTED_DISPLAY_REFRESH_RATES` and `ETrackedDeviceProperty_Prop_DisplayAvailableFrameRates_Float_Array`), as well as the current refresh rate in use.

The VR engine I'm working on exposes display refresh rates, but in the WebXR backend it currently just returns 0.  Personally I think it would be awesome if it could start returning data!

One thing I'm curious about is whether there are fingerprinting concerns with exposing the refresh rate, but I don't have good intuition in this area.

**Comment by cabanier** [comment]
@bjornbytes I agree. Returning the desired refresh rate is not the best solution but it can provide some guidance.

>One thing I'm curious about is whether there are fingerprinting concerns with exposing the refresh rate, but I don't have good intuition in this area.

I don't see why exposing the refresh rate has security concern. After all, a page could easily get the refresh by looking how quickly a regular or WebXR Raf fires.

**Comment by cabanier** [comment]
#1193 will solve this issue. @toji, can we close this one?
