### ISSUE TITLE
Add x,y coordinates to input source events for screen-space

### ISSUE THREAD

**Issue by Manishearth** [immersive-web/webxr#978]
Currently if a handheld AR session gets a `screen` touch event, the `x, y` coordinates of the event aren't surfaced [without doing some backcalculation](https://github.com/immersive-web/webxr/issues/977#issuecomment-595364947)

We should perhaps add something like `readonly double? x; readonly double? y;` to `InputSourceEvent` (or make a subclass) so that this can be surfaced directly.

This could potentially also be useful for touch events on layers (https://github.com/immersive-web/layers/issues/21)

See https://github.com/immersive-web/webxr/issues/977

cc @toji @cabanier

**Comment by klausw** [comment]
What's the coordinate space for the proposed x/y values? DOM pixels with origin at top left of the screen, or a normalized 0..1 or -1..1 range?

Alternatively, would it make sense to require UAs to emit gamepad.axes values for the screen input source? Chrome currently exposes them since it seemed to fit the spirit of the API, but this would be more generally useful if it reliably worked cross-platform. A side benefit of this approach is that applications that just need an analog control stick equivalent can work with both handheld AR and a motion controller's joystick/trackpad even without special-cased logic for form factors. While this wouldn't result in the most elegant experience, I think it may be a useful fallback for compatibility.

(FWIW, the current Chrome immersive-ar mode already internally transfers DOM pixel coordinates from the device side to Blink for use in DOM Overlay input processing, so this would be very easy to expose to JS.)

**Comment by Manishearth** [comment]
Hmm, I'm not sure. `gamepad.axes` is a useful way of surfacing it.

**Comment by Manishearth** [comment]
/agenda To figure out how people feel about adding this

**Comment by Manishearth** [comment]
Put out a strawman proposal: https://github.com/immersive-web/webxr/pull/980

**Comment by Manishearth** [comment]
So I was going to try and write something for this in the gamepads spec and I realized [this input profile had already been defined](https://github.com/immersive-web/webxr-input-profiles/pull/144).

@toji given this, do you think we can perhaps just add a note mentioning this and close this out?

**Comment by Manishearth** [comment]
Actually I'm not really sure where a note would _go_.

**Comment by Manishearth** [comment]
I'm just going to close this as resolved. @bialpio, do you have an idea where a note mentioning this would be best situated?

**Comment by JakeJustLearning** [comment]
THIS WOULD BE REALLY HELPFUL! the frame.getPose of targetRaySpace doesn't work it would be super dope if you just surfaced the XY values of the dom element.
