### ISSUE TITLE
Adjust VR scaling

### ISSUE THREAD

**Issue by stefandouw** [immersive-web/webxr#989]
Hello everyone, I have a question about integrating VR into our project. The project I'm working on is already years in development and they decided at the start that everything in our ThreeJS scene is scale x100. Out of the box that means putting on a VR headset makes me a mouse crawling around the scene. How would I go about adjusting everything for it to be the same scaling as in the ThreeJS scene?

**Comment by toji** [comment]
There's a high likelyhood that your issue will involve Three.js-specific logic, and as such this probably isn't the best forum to help with your question, since we're primarily focused on issues with the WebXR specification itself and not library integrations. Any of the links under the "Community" section of https://threejs.org/ are going to put you in touch with people that have more expertise in the library than we do.

That said, it sounds like the main issue is that WebXR's transforms are all specified in a space where 1 unit = 1 real world meter, and in order to accommodate that either your scene needs to be sized appropriately for WebXR's native scale or you need to scale all the transforms you get out of WebXR to match your scene's scale. (Which is a library-specific operation.) I tend to find the former approach is easier, but it depends on the project and obviously is a hard change to make late in a project's dev cycle. Off the top of my head I would suggest attaching the camera to a `THREE.Group` with a scaling value applied to it, but I'm not sure if that would actually give the desired results in your situation.

Good luck!
